// Code generated by skelc. DO NOT EDIT.

/**
 * Link application instance information registered with Hub.
 */
export type AppRegistration = {
  /**
   * Application name.
   */
  name:            string;
  /**
   * Application instance ID.
   */
  instanceId:      string;
  /**
   * Application version.
   */
  version:         string;
  /**
   * Application access address (e.g. "http://10.1.2.3:23001").
   */
  endpoint:        string;
  /**
   * List of Rpc service processing capabilities provided by the application.
   */
  serviceHandlers: Array<ServiceHandlerRegistration>;
  /**
   * List of web processing capabilities provided by the application.
   */
  webHandlers:     Array<WebHandlerRegistration>;
  /**
   * List of event listening capabilities provided by the application.
   */
  eventListeners:  Array<EventListenerRegistration>;
  /**
   * List of task execution capabilities provided by the application.
   */
  taskRunners:     Array<TaskRunnerRegistration>;
  /**
   * List of all DomainSchemas registered by the application.
   */
  domainSchemas:   Array<string>;
}
/**
 * Application instance status information, used for heartbeat refresh.
 */
export type AppStatus = {
  /**
   * Application name.
   */
  name:       string;
  /**
   * Application instance ID.
   */
  instanceId: string;
}
/**
 * Event listening capability registration information provided by the application.
 */
export type EventListenerRegistration = {
  /**
   * Event Skel name.
   */
  eventSkelName: string;
  /**
   * Event schema hash.
   */
  schemaHash:    string;
  /**
   * Execution timeout, in milliseconds.
   */
  timeoutMs:     number;
  /**
   * Maximum concurrency.
   */
  concurrency:   number;
  /**
   * Whether to disallow retrying after failure.
   */
  noRetry:       boolean;
}
/**
 * Hub information.
 */
export type Info = {
  /**
   * Control API service port.
   */
  apiPort:    number;
  /**
   * Redis service port.
   */
  redisPort:  number;
  /**
   * NATS service port.
   */
  natsPort:   number;
  /**
   * Standalone MQ service address.
   */
  mqEndpoint: string;
}
/**
 * Rpc service processing capability registration information provided by the application.
 */
export type ServiceHandlerRegistration = {
  /**
   * Service Skel name.
   */
  serviceSkelName: string;
  /**
   * Service schema hash.
   */
  schemaHash:      string;
  /**
   * Service agent access address.
   */
  endpoint:        string;
}
/**
 * Task execution Cron schedule.
 */
export type TaskRunnerCronScheduler = {
  /**
   * Trigger Skel name.
   */
  triggerSkelName: string;
  /**
   * Cron expression.
   */
  cronExpr:        string;
}
/**
 * Task execution capability registration information provided by the application.
 */
export type TaskRunnerRegistration = {
  /**
   * Task Skel name.
   */
  taskSkelName:   string;
  /**
   * Task schema hash.
   */
  schemaHash:     string;
  /**
   * Execution timeout, in milliseconds.
   */
  timeoutMs:      number;
  /**
   * Maximum concurrency.
   */
  concurrency:    number;
  /**
   * Whether to disallow retrying after failure.
   */
  noRetry:        boolean;
  /**
   * Cron schedule list.
   */
  cronSchedulers: Array<TaskRunnerCronScheduler>;
}
/**
 * Web processing capability registration information provided by the application.
 */
export type WebHandlerRegistration = {
  /**
   * Web Skel name.
   */
  webSkelName: string;
  /**
   * Web schema hash.
   */
  schemaHash:  string;
  /**
   * Web proxy access address.
   */
  endpoint:    string;
}
export {};
