package skel

import "go.yorun.ai/vine/util/vpre"

type AuthMode string

const (
	// AuthModeInherit uses the enclosing service authentication mode and is valid only on methods.
	AuthModeInherit   AuthMode = "inherit"
	AuthModeRequired  AuthMode = "required"
	AuthModeOptional  AuthMode = "optional"
	AuthModeAnonymous AuthMode = "anonymous"
	AuthModeOff       AuthMode = "off"
)

// Legacy values remain readable from previously generated contracts.
const (
	// AuthModeUnset is the legacy unspecified authentication mode.
	//
	// Deprecated: Use AuthModeInherit for methods or AuthModeRequired for services and web.
	AuthModeUnset AuthMode = "unset"
	// AuthModeAuth is the legacy spelling of AuthModeRequired.
	//
	// Deprecated: Use AuthModeRequired instead.
	AuthModeAuth AuthMode = "auth"
	// AuthModeNoAuth is the legacy anonymous-access mode.
	//
	// Deprecated: Use AuthModeOptional for Rpc or AuthModeOff for Web.
	AuthModeNoAuth AuthMode = "noauth"
)

// IsValid reports whether the mode is one of the canonical authentication modes.
// Declaration-specific restrictions are checked during schema registration.
func (mode AuthMode) IsValid() bool {
	switch mode {
	case AuthModeRequired, AuthModeOptional, AuthModeAnonymous, AuthModeOff, AuthModeInherit:
		return true
	default:
		return false
	}
}

func checkAuthMode(mode AuthMode, owner string) {
	vpre.Check(mode.IsValid() || mode == "" || mode == AuthModeUnset || mode == AuthModeAuth || mode == AuthModeNoAuth,
		"skel: %s has invalid auth mode %q", owner, mode)
}

// ConvertLegacyAuthModes validates and converts auth modes at schema registration
// so code generated by older skelc versions remains usable without regeneration.
// Empty and legacy unset values become required on services and web, or inherit
// on methods. Legacy auth becomes required; noauth becomes optional on Rpc and
// off on web. This preserves registration compatibility, not all prior admission
// behavior: web without an auth mode now requires authentication.
// Hashes remain the identifiers supplied by the generating compiler.
func ConvertLegacyAuthModes(schema *DomainSchema) {
	// Validate before conversion so invalid contracts are not partially rewritten.
	for _, service := range schema.Services {
		checkRpcServiceAuthModes(service)
	}
	for _, web := range schema.Webs {
		checkAuthMode(web.AuthMode, "web "+web.SkelName)
		vpre.Check(web.AuthMode != AuthModeInherit, "skel: web %s cannot use auth inherit; only methods can inherit authentication", web.SkelName)
	}
	for _, actor := range schema.Actors {
		checkRpcServiceAuthModes(actor.AuthService)
		checkRpcServiceAuthModes(actor.PermService)
		checkRpcMethodAuthMode(actor.AuthMethod, actor.SkelName)
		checkRpcMethodAuthMode(actor.PermMethod, actor.SkelName)
	}
	for _, resource := range schema.Resources {
		checkRpcServiceAuthModes(resource.CheckService)
	}
	for _, service := range schema.Services {
		convertLegacyServiceAuthModes(service)
	}
	for _, web := range schema.Webs {
		convertLegacyAuthMode(&web.AuthMode, AuthModeOff)
		if web.AuthMode == "" || web.AuthMode == AuthModeUnset {
			web.AuthMode = AuthModeRequired
		}
	}
	for _, actor := range schema.Actors {
		convertLegacyServiceAuthModes(actor.AuthService)
		convertLegacyServiceAuthModes(actor.PermService)
		if actor.AuthMethod != nil {
			convertLegacyMethodAuthMode(actor.AuthMethod)
		}
		if actor.PermMethod != nil {
			convertLegacyMethodAuthMode(actor.PermMethod)
		}
	}
	for _, resource := range schema.Resources {
		convertLegacyServiceAuthModes(resource.CheckService)
	}
}

func convertLegacyServiceAuthModes(service *ServiceSchema) {
	if service == nil {
		return
	}
	convertLegacyAuthMode(&service.AuthMode, AuthModeOptional)
	if service.AuthMode == "" || service.AuthMode == AuthModeUnset {
		service.AuthMode = AuthModeRequired
	}
	for _, method := range service.Methods {
		convertLegacyMethodAuthMode(method)
	}
}

func convertLegacyMethodAuthMode(method *MethodSchema) {
	convertLegacyAuthMode(&method.AuthMode, AuthModeOptional)
	if method.AuthMode == "" || method.AuthMode == AuthModeUnset {
		method.AuthMode = AuthModeInherit
	}
}

func convertLegacyAuthMode(mode *AuthMode, noAuthMode AuthMode) {
	switch *mode {
	case AuthModeAuth:
		*mode = AuthModeRequired
	case AuthModeNoAuth:
		*mode = noAuthMode
	}
}

func checkRpcServiceAuthModes(service *ServiceSchema) {
	if service == nil {
		return
	}
	checkAuthMode(service.AuthMode, "Rpc service "+service.SkelName)
	vpre.Check(service.AuthMode != AuthModeInherit, "skel: Rpc service %s cannot use auth inherit; only methods can inherit authentication", service.SkelName)
	vpre.Check(service.AuthMode != AuthModeOff, "skel: Rpc service %s cannot use auth off; use auth optional for anonymous access", service.SkelName)
	for _, method := range service.Methods {
		checkRpcMethodAuthMode(method, service.SkelName)
	}
}

func checkRpcMethodAuthMode(method *MethodSchema, ownerName string) {
	if method == nil {
		return
	}
	checkAuthMode(method.AuthMode, "Rpc method "+ownerName+"/"+method.SkelName)
	vpre.Check(method.AuthMode != AuthModeOff, "skel: Rpc method %s/%s cannot use auth off; use auth optional for anonymous access", ownerName, method.SkelName)
}
