package skel

import (
	"strings"
	"testing"
)

func TestRegisterDomainSchemaPanicsOnDuplicatePartialDomain(t *testing.T) {
	schemasByDomain = map[string]*DomainSchema{}

	RegisterDomainSchema(&DomainSchema{
		Domain:    "demo.user",
		Hash:      "first-partial-hash",
		Generated: validGeneratedInfoForTest(),
		Services: []*ServiceSchema{
			{SkelName: "demo.user.PublicService"},
		},
	})

	defer func() {
		if recover() == nil {
			t.Fatal("expected duplicate partial domain to panic")
		}
	}()
	RegisterDomainSchema(&DomainSchema{
		Domain:    "demo.user",
		Hash:      "next-partial-hash",
		Generated: validGeneratedInfoForTest(),
		Actors: []*ActorSchema{
			{SkelName: "demo.user.ClientActor"},
		},
	})
}

func TestRegisterDomainSchemaFullOverridesRegisteredDomain(t *testing.T) {
	schemasByDomain = map[string]*DomainSchema{}

	RegisterDomainSchema(&DomainSchema{
		Domain:    "demo.user",
		Hash:      "pub-hash",
		Generated: validGeneratedInfoForTest(),
		Services: []*ServiceSchema{
			{SkelName: "demo.user.PublicService"},
		},
	})
	RegisterDomainSchema(&DomainSchema{
		Domain:    "demo.user",
		Hash:      "full-hash",
		Full:      true,
		Generated: validGeneratedInfoForTest(),
		Actors: []*ActorSchema{
			{SkelName: "demo.user.ClientActor"},
		},
	})

	schemas := RegisteredDomainSchemas()
	if len(schemas) != 1 || schemas[0].Hash != "full-hash" {
		t.Fatalf("expected full schema to override partial schema, got %+v", schemas)
	}
}

func TestRegisteredDomainSchemasReturnsDomainSortedSchemas(t *testing.T) {
	schemasByDomain = map[string]*DomainSchema{}

	RegisterDomainSchema(&DomainSchema{
		Domain:    "demo.user",
		Hash:      "user-hash",
		Generated: validGeneratedInfoForTest(),
	})
	RegisterDomainSchema(&DomainSchema{
		Domain:    "demo.booker",
		Hash:      "booker-hash",
		Generated: validGeneratedInfoForTest(),
	})
	RegisterDomainSchema(&DomainSchema{
		Domain:    "demo.base",
		Hash:      "base-hash",
		Generated: validGeneratedInfoForTest(),
	})

	schemas := RegisteredDomainSchemas()
	if len(schemas) != 3 {
		t.Fatalf("unexpected registered schemas count: %d", len(schemas))
	}
	if schemas[0].Domain != "demo.base" || schemas[1].Domain != "demo.booker" || schemas[2].Domain != "demo.user" {
		t.Fatalf("unexpected schema order: %s, %s, %s", schemas[0].Domain, schemas[1].Domain, schemas[2].Domain)
	}
}

func TestServiceSchemaHasAudienceMatchesActorVia(t *testing.T) {
	service := &ServiceSchema{Audiences: []*ActorAudienceSchema{
		{SkelName: "demo.user.UserActor", Via: ActorViaAgent},
		{SkelName: "demo.admin.AdminActor"},
	}}

	if !service.HasAudience("demo.user.UserActor", ActorViaAgent) {
		t.Fatal("expected exact actor via to match")
	}
	if service.HasAudience("demo.user.UserActor", ActorViaClient) {
		t.Fatal("expected different actor via not to match")
	}
	if !service.HasAudience("demo.admin.AdminActor", ActorViaClient) {
		t.Fatal("expected empty audience via to match every actor via")
	}
	if service.HasAudience("demo.missing.MissingActor", ActorViaAgent) {
		t.Fatal("expected different actor not to match")
	}
}

func TestRegisterDomainSchemaPanicsOnDuplicateFullDomain(t *testing.T) {
	schemasByDomain = map[string]*DomainSchema{}

	RegisterDomainSchema(&DomainSchema{
		Domain:    "demo.user",
		Hash:      "full-hash",
		Full:      true,
		Generated: validGeneratedInfoForTest(),
	})

	defer func() {
		if recover() == nil {
			t.Fatal("expected duplicate full domain to panic")
		}
	}()
	RegisterDomainSchema(&DomainSchema{
		Domain:    "demo.user",
		Hash:      "next-full-hash",
		Full:      true,
		Generated: validGeneratedInfoForTest(),
	})
}

func validGeneratedInfoForTest() *GeneratedInfo {
	return &GeneratedInfo{CompilerVersion: "v99.0.0"}
}

func TestRegisterDomainSchemaPanicsOnLowCompilerVersion(t *testing.T) {
	schemasByDomain = map[string]*DomainSchema{}

	defer func() {
		value := recover()
		if value == nil {
			t.Fatal("expected low compiler version to panic")
		}
		if !strings.Contains(value.(error).Error(), "generated by skelc v0.8.9 is lower than Vine required skelc version") {
			t.Fatalf("unexpected panic: %v", value)
		}
	}()
	RegisterDomainSchema(&DomainSchema{
		Domain: "demo.user",
		Hash:   "full-hash",
		Generated: &GeneratedInfo{
			CompilerVersion: "v0.8.9",
		},
	})
}

func TestRegisterDomainSchemaPanicsOnMissingCompilerVersion(t *testing.T) {
	schemasByDomain = map[string]*DomainSchema{}

	defer func() {
		value := recover()
		if value == nil {
			t.Fatal("expected missing compiler version to panic")
		}
		if !strings.Contains(value.(error).Error(), "missing generated compiler version") {
			t.Fatalf("unexpected panic: %v", value)
		}
	}()
	RegisterDomainSchema(&DomainSchema{
		Domain: "demo.user",
		Hash:   "full-hash",
	})
}
