// Code generated by skelc. DO NOT EDIT.

package skeled

import (
	"go.yorun.ai/skel/descriptor"
	"go.yorun.ai/vine/core/skel"
)

func init() {
	skel.RegisterDomainDescriptor(_DomainDescriptor)
}

var _DomainDescriptor = &descriptor.Domain{
	Name:        "vine.link",
	Description: "Internal API for Vine Link",
	Hash:        "4fe38e57",
	Full:        true,
	Generated:   &descriptor.GeneratedInfo{CompilerVersion: "v0.30.1-0.20261006195103-dedd0501f1ce"},

	Data: []*descriptor.Data{
		{Name: "AppRegistration", SkelName: "vine.link.AppRegistration", Description: "Application information registered by App to Link", Hash: "c2ed015d", Members: []*descriptor.Member{
			{Name: "consoleEndpoint", Description: "Console access endpoint of the current application", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "serviceEndpoint", Description: "The Rpc service access endpoint of the current application", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "webEndpointPrefix", Description: "Web access endpoint prefix of the current application", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "eventEndpoint", Description: "The event processing access endpoint of the current application", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "taskEndpoint", Description: "The task execution endpoint of the current application", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "serviceHandlers", Description: "List of Rpc service processing capabilities provided by the current application", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "ServiceHandlerRegistration", SkelName: "vine.link.ServiceHandlerRegistration"}}},
			{Name: "webHandlers", Description: "List of web processing capabilities provided by the current application", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "WebHandlerRegistration", SkelName: "vine.link.WebHandlerRegistration"}}},
			{Name: "eventListeners", Description: "List of event listening capabilities provided by the current application", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "EventListenerRegistration", SkelName: "vine.link.EventListenerRegistration"}}},
			{Name: "taskRunners", Description: "List of task execution capabilities provided by the current application", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "TaskRunnerRegistration", SkelName: "vine.link.TaskRunnerRegistration"}}},
			{Name: "domainDescriptors", Description: "List of all domain descriptors registered by the current application", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarJSON}}},
			{Name: "domainSchemas", Description: "Legacy schema registration input", Deprecated: true, DeprecatedReason: "Use domainDescriptors instead", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarJSON}}},
		}},
		{Name: "BootInfo", SkelName: "vine.link.BootInfo", Description: "Key information obtained from Link when the App starts", Hash: "b76cdd7a", Members: []*descriptor.Member{
			{Name: "rpcProxyEndpointPath", Description: "The endpoint path that should be accessed when the current application initiates Rpc", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "skipDomainDescriptors", Description: "Whether to skip descriptor when app is registered", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}},
		}},
		{Name: "EventEmission", SkelName: "vine.link.EventEmission", Description: "Event dispatch information sent from App to Link", Hash: "ae1412d6", Members: []*descriptor.Member{
			{Name: "metadata", Description: "Event meta information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "EventEmissionMeta", SkelName: "vine.link.EventEmissionMeta"}},
			{Name: "eventSkelName", Description: "Event Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "eventJson", Description: "Event JSON", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
		{Name: "EventEmissionMeta", SkelName: "vine.link.EventEmissionMeta", Description: "Meta information carried when App initiates event sending to Link", Hash: "2d0ec63d", Members: []*descriptor.Member{
			{Name: "traceId", Description: "Trace ID of the current calling link", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "traceSpan", Description: "Trace Span of the current calling link", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appName", Description: "The application name that sent the event", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appVersion", Description: "The application version that sent the event", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appInstanceId", Description: "The application instance ID that sent the event", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarUUID}},
		}},
		{Name: "EventListenerRegistration", SkelName: "vine.link.EventListenerRegistration", Description: "Event listening capability registration information provided by the application", Hash: "68ee9fd3", Members: []*descriptor.Member{
			{Name: "eventSkelName", Description: "Event Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "descriptorHash", Description: "Event descriptor hash", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "timeoutMs", Description: "Execution timeout, in milliseconds", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "concurrency", Description: "Maximum concurrency", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "noRetry", Description: "Whether to disallow retrying after failure", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}},
		}},
		{Name: "ServiceHandlerRegistration", SkelName: "vine.link.ServiceHandlerRegistration", Description: "Rpc service processing capability registration information provided by the application", Hash: "052e69ed", Members: []*descriptor.Member{
			{Name: "serviceSkelName", Description: "Service Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "descriptorHash", Description: "Service descriptor hash", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
		{Name: "TaskLaunch", SkelName: "vine.link.TaskLaunch", Description: "Task trigger information initiated by App to Link", Hash: "2de22603", Members: []*descriptor.Member{
			{Name: "metadata", Description: "Task trigger meta information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "TaskLaunchMeta", SkelName: "vine.link.TaskLaunchMeta"}},
			{Name: "taskSkelName", Description: "Task Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "triggerSkelName", Description: "Task trigger Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "argumentsJson", Description: "Task parameters JSON", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
		{Name: "TaskLaunchMeta", SkelName: "vine.link.TaskLaunchMeta", Description: "The meta information carried when the App initiates a task to Link", Hash: "c7f14ff5", Members: []*descriptor.Member{
			{Name: "traceId", Description: "Trace ID of the current calling link", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "traceSpan", Description: "Trace Span of the current calling link", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appName", Description: "Application name that initiated the task", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appVersion", Description: "The application version that initiated the task", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appInstanceId", Description: "The application instance ID that initiated the task", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarUUID}},
		}},
		{Name: "TaskRunnerCronScheduler", SkelName: "vine.link.TaskRunnerCronScheduler", Description: "Task execution Cron schedule", Hash: "66cfc915", Members: []*descriptor.Member{
			{Name: "triggerSkelName", Description: "Trigger Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "cronExpr", Description: "Cron expression", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
		{Name: "TaskRunnerRegistration", SkelName: "vine.link.TaskRunnerRegistration", Description: "Task execution capability registration information provided by the application", Hash: "bd9dab40", Members: []*descriptor.Member{
			{Name: "taskSkelName", Description: "Task Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "descriptorHash", Description: "Task descriptor hash", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "timeoutMs", Description: "Execution timeout, in milliseconds", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "concurrency", Description: "Maximum concurrency", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "noRetry", Description: "Whether to disallow retrying after failure", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}},
			{Name: "cronSchedulers", Description: "Cron schedule list", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "TaskRunnerCronScheduler", SkelName: "vine.link.TaskRunnerCronScheduler"}}},
		}},
		{Name: "WebHandlerRegistration", SkelName: "vine.link.WebHandlerRegistration", Description: "Web processing capability registration information provided by the application", Hash: "91b1693c", Members: []*descriptor.Member{
			{Name: "webSkelName", Description: "Web Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "descriptorHash", Description: "Web descriptor hash", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
	},

	Services: []*descriptor.Service{
		{Name: "BootService", SkelName: "vine.link.BootService", Description: "Link's startup information service, called by the App", Hash: "c5600d90", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "getInfo", SkelName: "getInfo", Description: "Get key startup information", Hash: "b8887b35", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, ResultType: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "BootInfo", SkelName: "vine.link.BootInfo"}},
		}},
		{Name: "ConfigService", SkelName: "vine.link.ConfigService", Description: "Link's application configuration service, called by the App", Hash: "420d2cb7", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "getEternal", SkelName: "getEternal", Description: "Read Eternal configuration", Hash: "0b48886e", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, OutputDescription: "Configuration JSON", ResultType: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}, Arguments: []*descriptor.Member{
				{Name: "key", Description: "Configuration key", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			}},
			{Name: "getInstant", SkelName: "getInstant", Description: "Read Instant configuration", Hash: "50b06f0e", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, OutputDescription: "Configuration JSON", ResultType: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}, Arguments: []*descriptor.Member{
				{Name: "key", Description: "Configuration key", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			}},
		}},
		{Name: "EventService", SkelName: "vine.link.EventService", Description: "Link's event service, called by App", Hash: "f1d171cc", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "emitEvent", SkelName: "emitEvent", Description: "Send event", Hash: "0cdc54cf", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, Arguments: []*descriptor.Member{
				{Name: "emission", Description: "Event sending information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "EventEmission", SkelName: "vine.link.EventEmission"}},
			}},
		}},
		{Name: "LockService", SkelName: "vine.link.LockService", Description: "Distributed lease lock service", Hash: "8d360286", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "acquire", SkelName: "acquire", Description: "Acquire a lock using a unique attempt token", Hash: "f085a1e5", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, ResultType: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}, Arguments: []*descriptor.Member{
				{Name: "key", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "token", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "ttlMillis", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			}},
			{Name: "renew", SkelName: "renew", Description: "Renew a lock owned by the token", Hash: "1b8b3625", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, ResultType: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}, Arguments: []*descriptor.Member{
				{Name: "key", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "token", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "ttlMillis", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			}},
			{Name: "release", SkelName: "release", Description: "Release a lock owned by the token", Hash: "2da2617f", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, ResultType: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}, Arguments: []*descriptor.Member{
				{Name: "key", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "token", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			}},
		}},
		{Name: "RegistryService", SkelName: "vine.link.RegistryService", Description: "Link's application registration service, called by the App", Hash: "a07517dc", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "register", SkelName: "register", Description: "Register the currently running application", Hash: "93b0cb7e", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, Arguments: []*descriptor.Member{
				{Name: "registration", Description: "Application instance registration information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "AppRegistration", SkelName: "vine.link.AppRegistration"}},
			}},
			{Name: "unregister", SkelName: "unregister", Description: "Log out of the currently running application and prepare to exit gracefully. This call may block until the current instance's in-progress work on the Link side is drained, or until the wait times out", Hash: "3914ba71", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired},
		}},
		{Name: "TaskService", SkelName: "vine.link.TaskService", Description: "Link's task service, called by the App", Hash: "26a1aef1", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "launchTask", SkelName: "launchTask", Description: "Start a task", Hash: "ea8345fb", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, Arguments: []*descriptor.Member{
				{Name: "launch", Description: "Task trigger information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "TaskLaunch", SkelName: "vine.link.TaskLaunch"}},
			}},
		}},
	},
}
