// Code generated by skelc. DO NOT EDIT.

package admin

import "go.yorun.ai/vine/core/meta"

func init() {
	meta.RegisterActor(meta.ActorSpec{
		Name:     "AdminActor",
		SkelName: "vine.hub.admin.AdminActor",
		Hash:     "c70b3174",
	})
}
