// Code generated by skelc. DO NOT EDIT.

package admin

import (
	"go.yorun.ai/skel/descriptor"
	"go.yorun.ai/vine/core/meta"
	"go.yorun.ai/vine/core/skel"
)

func init() {
	meta.RegisterActor(meta.ActorSpec{
		Name:     "AdminActor",
		SkelName: "vine.hub.admin.AdminActor",
		Hash:     "c70b3174",
	})
}

// AdminActor Hub operator using the Dashboard on the admin listener
type AdminActor struct {
	skel.ActorBase
}

func (AdminActor) Name() string {
	return "AdminActor"
}

func (AdminActor) SkelName() string {
	return "vine.hub.admin.AdminActor"
}

func (AdminActor) Vias() []descriptor.ActorViaKind {
	return []descriptor.ActorViaKind{
		descriptor.ActorViaClient,
	}
}
