// Code generated by skelc. DO NOT EDIT.

package admin

import "go.yorun.ai/vine/internal/core/skel"

// AppConfigCreation Configuration creation parameters
type AppConfigCreation struct {
	// SkelName Configuration Skel name
	SkelName string `json:"skelName"`
	// Value Configuration JSON
	Value string `json:"value"`
}

// AppConfigItem Configuration items
type AppConfigItem struct {
	// Id Configuration ID
	Id int `json:"id"`
	// Key Configuration key
	Key string `json:"key"`
	// Status Configuration status
	Status string `json:"status"`
	// Lifecycle Configuration lifecycle
	Lifecycle string `json:"lifecycle"`
	// Value Configuration JSON
	Value string `json:"value"`
	// Schema Configuration schema
	Schema *AppConfigSchema `json:"schema"`
	// FieldSources Field sources; only returned by get, create and update
	FieldSources []FieldSource `json:"fieldSources"`
}

// AppConfigListItem Configuration item list item
type AppConfigListItem struct {
	// Id Configuration ID
	Id int `json:"id"`
	// Key Configuration key
	Key string `json:"key"`
	// Status Configuration status
	Status string `json:"status"`
	// Lifecycle Configuration lifecycle
	Lifecycle string `json:"lifecycle"`
	// SchemaName Configuration schema name; empty when no schema matches
	SchemaName string `json:"schemaName"`
	// SchemaSkelName Configuration schema Skel name; empty when no schema matches
	SchemaSkelName string `json:"schemaSkelName"`
}

// AppConfigSchema Configuration schema items
type AppConfigSchema struct {
	// SkelName Configuration Skel name
	SkelName string `json:"skelName"`
	// Name Configuration name
	Name string `json:"name"`
	// Description Configuration description
	Description string `json:"description"`
	// Deprecated Whether the configuration is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Configuration deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Lifecycle Configuration lifecycle
	Lifecycle string `json:"lifecycle"`
	// Fields Configuration field list
	Fields []AppConfigSchemaField `json:"fields"`
}

// AppConfigSchemaEnumItem Configuration schema enumeration options
type AppConfigSchemaEnumItem struct {
	// Name Enum option name
	Name string `json:"name"`
	// Description Enumeration options description
	Description string `json:"description"`
	// Deprecated Whether the enumeration option is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Enumeration option deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
}

// AppConfigSchemaField Configuration schema fields
type AppConfigSchemaField struct {
	// Name Field name
	Name string `json:"name"`
	// Type Field type
	Type string `json:"type"`
	// Description Field description
	Description string `json:"description"`
	// Deprecated Whether the field is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Field deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// EnumItems Enumeration options list
	EnumItems []AppConfigSchemaEnumItem `json:"enumItems"`
	// MapKeyEnumItems Map key enumeration options
	MapKeyEnumItems []AppConfigSchemaEnumItem `json:"mapKeyEnumItems"`
	// MapValueEnumItems Map value enumeration options
	MapValueEnumItems []AppConfigSchemaEnumItem `json:"mapValueEnumItems"`
}

// AppConfigUpdate Configuration update parameters
type AppConfigUpdate struct {
	// Value Configuration JSON
	Value *string `json:"value"`
}

// AppStatusView Application instance status view for Dashboard display
type AppStatusView struct {
	// Name Application name
	Name string `json:"name"`
	// InstanceId Application instance ID
	InstanceId string `json:"instanceId"`
	// Version Application version
	Version string `json:"version"`
	// Endpoint Application access address
	Endpoint string `json:"endpoint"`
	// ServiceHandlers List of Rpc service processing capabilities provided by the application
	ServiceHandlers []ServiceHandlerRegistration `json:"serviceHandlers"`
	// WebHandlers List of web processing capabilities provided by the application
	WebHandlers []WebHandlerRegistration `json:"webHandlers"`
	// EventListeners List of event listening capabilities provided by the application
	EventListeners []EventListenerRegistration `json:"eventListeners"`
	// TaskRunners List of task execution capabilities provided by the application
	TaskRunners []TaskRunnerRegistration `json:"taskRunners"`
}

// EventDebugDefaultEmitRequest Default Event Debug send request
type EventDebugDefaultEmitRequest struct {
	// TraceId Trace ID
	TraceId string `json:"traceId"`
	// SpanId Span ID
	SpanId string `json:"spanId"`
	// EventJson Default event JSON
	EventJson skel.JSON `json:"eventJson"`
}

// EventDebugEmitRequest Event Debug send request
type EventDebugEmitRequest struct {
	// EventSkelName Event Skel name
	EventSkelName string `json:"eventSkelName"`
	// SchemaHash Event schema hash
	SchemaHash string `json:"schemaHash"`
	// EventJson Event JSON
	EventJson skel.JSON `json:"eventJson"`
	// TraceId Trace ID
	TraceId *string `json:"traceId"`
	// SpanId Span ID
	SpanId *string `json:"spanId"`
}

// EventDebugEventItem Event called by Event Debug
type EventDebugEventItem struct {
	// Name Event name
	Name string `json:"name"`
	// EventSkelName Event Skel name
	EventSkelName string `json:"eventSkelName"`
	// SchemaHash Event schema hash
	SchemaHash string `json:"schemaHash"`
	// Description Event description
	Description string `json:"description"`
	// Deprecated Whether the Event is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Event deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Fields Field list
	Fields []SkeletonField `json:"fields"`
}

// EventListenerRegistration Event listening capability registration information provided by the application
type EventListenerRegistration struct {
	// EventSkelName Event Skel name
	EventSkelName string `json:"eventSkelName"`
	// SchemaHash Event schema hash
	SchemaHash string `json:"schemaHash"`
	// TimeoutMs Execution timeout, in milliseconds
	TimeoutMs int `json:"timeoutMs"`
	// Concurrency Maximum concurrency
	Concurrency int `json:"concurrency"`
	// NoRetry Whether to disallow retrying after failure
	NoRetry bool `json:"noRetry"`
}

// FieldSource Layers that supplied an entity field
type FieldSource struct {
	// Path Field JSON pointer
	Path string `json:"path"`
	// Source Seed source
	Source string `json:"source"`
	// Define Seed definition name
	Define string `json:"define"`
	// Override Seed override name
	Override string `json:"override"`
	// Variables Referenced seed variables
	Variables []string `json:"variables"`
	// Template Seed template
	Template *skel.JSON `json:"template"`
	// Bindings Resolved variable bindings
	Bindings []FieldSourceBinding `json:"bindings"`
}

// FieldSourceBinding A resolved variable reference within a field template
type FieldSourceBinding struct {
	// Path Template JSON pointer
	Path string `json:"path"`
	// Variable Variable name
	Variable string `json:"variable"`
	// Reference Variable reference
	Reference string `json:"reference"`
	// Value Resolved value
	Value skel.JSON `json:"value"`
	// DefaultUsed Whether the default was used
	DefaultUsed bool `json:"defaultUsed"`
}

// PortalCert Portal site certificate
type PortalCert struct {
	// Id Certificate ID
	Id int `json:"id"`
	// Name Certificate name
	Name string `json:"name"`
	// Issuer Certificate issuer
	Issuer string `json:"issuer"`
	// Domains Certificate domain name
	Domains []string `json:"domains"`
	// PublicKeyBase64 Certificate Base64
	PublicKeyBase64 string `json:"publicKeyBase64"`
	// PrivateKeyConfigured Whether the private key has been configured
	PrivateKeyConfigured bool `json:"privateKeyConfigured"`
	// ValidFrom Validity start time
	ValidFrom skel.Timestamp `json:"validFrom"`
	// ValidTo Validity end time
	ValidTo skel.Timestamp `json:"validTo"`
	// FieldSources Field sources; only returned by get, create and update
	FieldSources []FieldSource `json:"fieldSources"`
	// Enabled Whether Hub publishes this certificate to Portal
	Enabled bool `json:"enabled"`
}

// PortalCertCreation Portal site certificate creation parameters
type PortalCertCreation struct {
	// Name Certificate name
	Name string `json:"name"`
	// PublicKeyBase64 Certificate Base64
	PublicKeyBase64 string `json:"publicKeyBase64"`
	// PrivateKeyBase64 Private key Base64
	PrivateKeyBase64 string `json:"privateKeyBase64"`
	// Enabled Whether Hub publishes this certificate to Portal
	Enabled *bool `json:"enabled"`
}

// PortalCertListItem Portal site certificate list item
type PortalCertListItem struct {
	// Id Certificate ID
	Id int `json:"id"`
	// Name Certificate name
	Name string `json:"name"`
	// Issuer Certificate issuer
	Issuer string `json:"issuer"`
	// Domains Certificate domain name
	Domains []string `json:"domains"`
	// PublicKeyBase64 Certificate Base64
	PublicKeyBase64 string `json:"publicKeyBase64"`
	// PrivateKeyConfigured Whether the private key has been configured
	PrivateKeyConfigured bool `json:"privateKeyConfigured"`
	// ValidFrom Validity start time
	ValidFrom skel.Timestamp `json:"validFrom"`
	// ValidTo Validity end time
	ValidTo skel.Timestamp `json:"validTo"`
	// Enabled Whether Hub publishes this certificate to Portal
	Enabled bool `json:"enabled"`
}

// PortalCertUpdate Portal site certificate update parameters
type PortalCertUpdate struct {
	// Name Certificate name
	Name *string `json:"name"`
	// PublicKeyBase64 Certificate Base64
	PublicKeyBase64 *string `json:"publicKeyBase64"`
	// PrivateKeyBase64 Private key Base64
	PrivateKeyBase64 *string `json:"privateKeyBase64"`
	// Enabled Whether Hub publishes this certificate to Portal
	Enabled *bool `json:"enabled"`
}

// PortalCors Portal site CORS configuration
type PortalCors struct {
	// Mode CORS mode: DISABLED/SAME_DOMAIN/STRICT
	Mode PortalCorsMode `json:"mode"`
	// AllowedOrigins List of origins allowed in strict mode
	AllowedOrigins []string `json:"allowedOrigins"`
}

// PortalEntry Portal access entry
type PortalEntry struct {
	// Id Entry ID
	Id int `json:"id"`
	// Name Entry name
	Name string `json:"name"`
	// Scheme Entry protocol
	Scheme string `json:"scheme"`
	// Host Match Host, empty string means no restriction
	Host string `json:"host"`
	// Port Entry port
	Port int `json:"port"`
	// Rules Entry rule list
	Rules []PortalEntryRule `json:"rules"`
	// Enabled Whether Hub publishes the rules of this entry to Portal
	Enabled bool `json:"enabled"`
}

// PortalEntryCreation Portal access entry creation parameters
type PortalEntryCreation struct {
	// Name Entry name
	Name string `json:"name"`
	// Scheme Entry protocol
	Scheme string `json:"scheme"`
	// Host Match Host, empty string means no restriction
	Host string `json:"host"`
	// Port Entry port
	Port int `json:"port"`
	// Enabled Whether Hub publishes the rules of this entry to Portal; defaults to true
	Enabled *bool `json:"enabled"`
}

// PortalEntryRule Portal access entry rules
type PortalEntryRule struct {
	// Rule Entry rules
	Rule PortalRuleListItem `json:"rule"`
	// Site Target site
	Site *PortalSiteListItem `json:"site"`
}

// PortalEntryUpdate Portal access entry update parameters
type PortalEntryUpdate struct {
	// Name Entry name
	Name *string `json:"name"`
	// Scheme Entry protocol
	Scheme *string `json:"scheme"`
	// Host Match Host, empty string means no restriction
	Host *string `json:"host"`
	// Port Entry port
	Port *int `json:"port"`
	// Enabled Whether Hub publishes the rules of this entry to Portal
	Enabled *bool `json:"enabled"`
}

// PortalRule Portal entry rules
type PortalRule struct {
	// Id Rule ID
	Id int `json:"id"`
	// Name Rule name
	Name string `json:"name"`
	// MatchScheme Matching protocol
	MatchScheme string `json:"matchScheme"`
	// MatchHost Match Host, empty string means no restriction
	MatchHost string `json:"matchHost"`
	// MatchPort Match matchPort, 0 means no restriction
	MatchPort int `json:"matchPort"`
	// MatchPathPrefix Match path prefix, empty string means match all paths
	MatchPathPrefix string `json:"matchPathPrefix"`
	// RouteType Target type
	RouteType string `json:"routeType"`
	// RouteSiteName Site name
	RouteSiteName string `json:"routeSiteName"`
	// RouteRedirectionPattern Redirect Pattern
	RouteRedirectionPattern string `json:"routeRedirectionPattern"`
	// RoutePathPrefix Target site path prefix; empty means strip the matching prefix only
	RoutePathPrefix string `json:"routePathPrefix"`
	// ResolvedMatchPathPrefix Effective match path prefix after site mount path resolution
	ResolvedMatchPathPrefix string `json:"resolvedMatchPathPrefix"`
	// ResolvedRoutePathPrefix Effective route path prefix after site mount path resolution
	ResolvedRoutePathPrefix string `json:"resolvedRoutePathPrefix"`
	// FieldSources Field sources; only returned by get, create and update
	FieldSources []FieldSource `json:"fieldSources"`
	// Enabled Whether Hub publishes this rule to Portal
	Enabled bool `json:"enabled"`
}

// PortalRuleConflict Portal entry rules that match the same request
type PortalRuleConflict struct {
	// RuleId Rule ID
	RuleId int `json:"ruleId"`
	// Rule Rule name
	Rule string `json:"rule"`
	// ConflictRuleId ID of the rule that already matches the request
	ConflictRuleId int `json:"conflictRuleId"`
	// ConflictRule Name of the rule that already matches the request
	ConflictRule string `json:"conflictRule"`
	// Entry Name of the Portal entry the rules belong to
	Entry string `json:"entry"`
	// Match Request both rules match
	Match string `json:"match"`
	// PublishedRuleId ID of the rule Hub publishes for the request
	PublishedRuleId int `json:"publishedRuleId"`
	// PublishedRule Name of the rule Hub publishes for the request
	PublishedRule string `json:"publishedRule"`
	// SuppressedRuleId ID of the rule Hub leaves out, because the published rule sorts first
	SuppressedRuleId int `json:"suppressedRuleId"`
	// SuppressedRule Name of the rule Hub leaves out, because the published rule sorts first
	SuppressedRule string `json:"suppressedRule"`
}

// PortalRuleCreation Portal entry rule creation parameters
type PortalRuleCreation struct {
	// Name Rule name
	Name string `json:"name"`
	// EntryName Name of the Portal access entry the rule belongs to
	EntryName string `json:"entryName"`
	// MatchPathPrefix Match path prefix, empty string means match all paths
	MatchPathPrefix string `json:"matchPathPrefix"`
	// RouteType Target type
	RouteType string `json:"routeType"`
	// RouteSiteName Site name
	RouteSiteName string `json:"routeSiteName"`
	// RouteRedirectionPattern Redirect Pattern
	RouteRedirectionPattern string `json:"routeRedirectionPattern"`
	// RoutePathPrefix Target site path prefix; empty means strip the matching prefix only
	RoutePathPrefix *string `json:"routePathPrefix"`
	// Enabled Whether Hub publishes this rule to Portal
	Enabled *bool `json:"enabled"`
}

// PortalRuleListItem Portal entry rule list item
type PortalRuleListItem struct {
	// Id Rule ID
	Id int `json:"id"`
	// Name Rule name
	Name string `json:"name"`
	// MatchScheme Matching protocol
	MatchScheme string `json:"matchScheme"`
	// MatchHost Match Host, empty string means no restriction
	MatchHost string `json:"matchHost"`
	// MatchPort Match matchPort, 0 means no restriction
	MatchPort int `json:"matchPort"`
	// MatchPathPrefix Match path prefix, empty string means match all paths
	MatchPathPrefix string `json:"matchPathPrefix"`
	// RouteType Target type
	RouteType string `json:"routeType"`
	// RouteSiteName Site name
	RouteSiteName string `json:"routeSiteName"`
	// RouteRedirectionPattern Redirect Pattern
	RouteRedirectionPattern string `json:"routeRedirectionPattern"`
	// RoutePathPrefix Target site path prefix; empty means strip the matching prefix only
	RoutePathPrefix string `json:"routePathPrefix"`
	// ResolvedMatchPathPrefix Effective match path prefix after site mount path resolution
	ResolvedMatchPathPrefix string `json:"resolvedMatchPathPrefix"`
	// ResolvedRoutePathPrefix Effective route path prefix after site mount path resolution
	ResolvedRoutePathPrefix string `json:"resolvedRoutePathPrefix"`
	// Enabled Whether Hub publishes this rule to Portal
	Enabled bool `json:"enabled"`
}

// PortalRuleUpdate Portal entry rule update parameters
type PortalRuleUpdate struct {
	// Name Rule name
	Name *string `json:"name"`
	// MatchPathPrefix Match path prefix, empty string means match all paths
	MatchPathPrefix *string `json:"matchPathPrefix"`
	// RouteType Target type
	RouteType *string `json:"routeType"`
	// RouteSiteName Site name
	RouteSiteName *string `json:"routeSiteName"`
	// RouteRedirectionPattern Redirect Pattern
	RouteRedirectionPattern *string `json:"routeRedirectionPattern"`
	// RoutePathPrefix Target site path prefix; empty means strip the matching prefix only
	RoutePathPrefix *string `json:"routePathPrefix"`
	// Enabled Whether Hub publishes this rule to Portal
	Enabled *bool `json:"enabled"`
}

// PortalSite Portal target site
type PortalSite struct {
	// Id Target site id
	Id int `json:"id"`
	// Name Target site name
	Name string `json:"name"`
	// Type Target site type
	Type PortalSiteType `json:"type"`
	// ActorSkelName Actor Skel name
	ActorSkelName string `json:"actorSkelName"`
	// ActorVia Actor access method
	ActorVia string `json:"actorVia"`
	// RpcgwServices Rpc gateway service Skel name list
	RpcgwServices []string `json:"rpcgwServices"`
	// Cors CORS configuration
	Cors *PortalCors `json:"cors"`
	// WebName Web name
	WebName string `json:"webName"`
	// WebMountPath Web mount path; empty means the Web is not limited to a path
	WebMountPath string `json:"webMountPath"`
	// FieldSources Field sources; only returned by get, create and update
	FieldSources []FieldSource `json:"fieldSources"`
	// Enabled Whether Hub publishes this site to Portal
	Enabled bool `json:"enabled"`
}

// PortalSiteActorOption Portal target site Actor options
type PortalSiteActorOption struct {
	// Name Actor name
	Name string `json:"name"`
	// SkelName Actor Skel name
	SkelName string `json:"skelName"`
	// ActorVias Actor access method list
	ActorVias []string `json:"actorVias"`
}

// PortalSiteCreation Portal target site creation parameters
type PortalSiteCreation struct {
	// Name Target site name
	Name string `json:"name"`
	// Type Target site type
	Type PortalSiteType `json:"type"`
	// ActorSkelName Actor Skel name
	ActorSkelName string `json:"actorSkelName"`
	// ActorVia Actor access method
	ActorVia string `json:"actorVia"`
	// Cors CORS configuration
	Cors *PortalCors `json:"cors"`
	// WebName Web name
	WebName string `json:"webName"`
	// Enabled Whether Hub publishes this site to Portal
	Enabled *bool `json:"enabled"`
}

// PortalSiteListItem Portal target site list item
type PortalSiteListItem struct {
	// Id Target site id
	Id int `json:"id"`
	// Name Target site name
	Name string `json:"name"`
	// Type Target site type
	Type PortalSiteType `json:"type"`
	// ActorSkelName Actor Skel name
	ActorSkelName string `json:"actorSkelName"`
	// ActorVia Actor access method
	ActorVia string `json:"actorVia"`
	// RpcgwServices Rpc gateway service Skel name list
	RpcgwServices []string `json:"rpcgwServices"`
	// Cors CORS configuration
	Cors *PortalCors `json:"cors"`
	// WebName Web name
	WebName string `json:"webName"`
	// WebMountPath Web mount path; empty means the Web is not limited to a path
	WebMountPath string `json:"webMountPath"`
	// Enabled Whether Hub publishes this site to Portal
	Enabled bool `json:"enabled"`
}

// PortalSiteOptions Portal target site form options
type PortalSiteOptions struct {
	// Actors Actor options
	Actors []PortalSiteActorOption `json:"actors"`
	// Services Rpc service options
	Services []PortalSiteServiceOption `json:"services"`
	// Webs Web options
	Webs []PortalSiteWebOption `json:"webs"`
}

// PortalSiteServiceOption Portal target site service options
type PortalSiteServiceOption struct {
	// Name Service name
	Name string `json:"name"`
	// SkelName Service Skel name
	SkelName string `json:"skelName"`
	// ActorSkelNames Actor Skel name list
	ActorSkelNames []string `json:"actorSkelNames"`
}

// PortalSiteUpdate Portal target site update parameters
type PortalSiteUpdate struct {
	// Name Target site name
	Name *string `json:"name"`
	// Type Target site type
	Type *PortalSiteType `json:"type"`
	// ActorSkelName Actor Skel name
	ActorSkelName *string `json:"actorSkelName"`
	// ActorVia Actor access method
	ActorVia *string `json:"actorVia"`
	// Cors CORS configuration
	Cors *PortalCors `json:"cors"`
	// WebName Web name
	WebName *string `json:"webName"`
	// Enabled Whether Hub publishes this site to Portal
	Enabled *bool `json:"enabled"`
}

// PortalSiteWebOption Portal target site web options
type PortalSiteWebOption struct {
	// Name Web name
	Name string `json:"name"`
	// SkelName Web Skel name
	SkelName string `json:"skelName"`
	// ActorSkelNames Actor Skel name list
	ActorSkelNames []string `json:"actorSkelNames"`
}

// PortalStatusView Portal instance status view for Dashboard display
type PortalStatusView struct {
	// InstanceId Portal instance ID
	InstanceId string `json:"instanceId"`
	// Version Portal version
	Version string `json:"version"`
}

// ServiceDebugActorItem Service Debug Actor options
type ServiceDebugActorItem struct {
	// Name Actor name
	Name string `json:"name"`
	// SkelName Actor Skel name
	SkelName string `json:"skelName"`
	// InfoSkelName Actor Info Skel name
	InfoSkelName string `json:"infoSkelName"`
	// ActorInfoJson Default Actor Info JSON
	ActorInfoJson skel.JSON `json:"actorInfoJson"`
}

// ServiceDebugAppInstance Application instance called by Service Debug
type ServiceDebugAppInstance struct {
	// AppName Application name
	AppName string `json:"appName"`
	// AppInstanceId Application instance ID
	AppInstanceId string `json:"appInstanceId"`
	// AppVersion Application version
	AppVersion string `json:"appVersion"`
	// Endpoint Application access address
	Endpoint string `json:"endpoint"`
}

// ServiceDebugDefaultInvokeRequest Service Debug default call request
type ServiceDebugDefaultInvokeRequest struct {
	// TraceId Trace ID
	TraceId string `json:"traceId"`
	// SpanId Span ID
	SpanId string `json:"spanId"`
	// Actors Actor options
	Actors []ServiceDebugActorItem `json:"actors"`
	// ActorSkelName Default Actor Skel name
	ActorSkelName *string `json:"actorSkelName"`
	// ActorInfoJson Default Actor Info JSON
	ActorInfoJson skel.JSON `json:"actorInfoJson"`
	// ParamsJson Default request parameters JSON
	ParamsJson skel.JSON `json:"paramsJson"`
}

// ServiceDebugInvokeRequest Service Debug call request
type ServiceDebugInvokeRequest struct {
	// AppName Application name
	AppName *string `json:"appName"`
	// AppInstanceId Application instance ID
	AppInstanceId *string `json:"appInstanceId"`
	// ServiceSkelName Service Skel name
	ServiceSkelName string `json:"serviceSkelName"`
	// SchemaHash Service schema hash
	SchemaHash string `json:"schemaHash"`
	// MethodSkelName Method Skel name
	MethodSkelName string `json:"methodSkelName"`
	// ParamsJson Request parameters JSON
	ParamsJson skel.JSON `json:"paramsJson"`
	// TimeoutSeconds Call timeout, in seconds
	TimeoutSeconds int `json:"timeoutSeconds"`
	// TraceId Trace ID
	TraceId *string `json:"traceId"`
	// SpanId Span ID
	SpanId *string `json:"spanId"`
	// ActorSkelName Actor Skel name
	ActorSkelName *string `json:"actorSkelName"`
	// ActorInfoJson Actor Info JSON
	ActorInfoJson skel.JSON `json:"actorInfoJson"`
}

// ServiceDebugInvokeResponse Service Debug call response
type ServiceDebugInvokeResponse struct {
	// HttpStatus HTTP status code
	HttpStatus int `json:"httpStatus"`
	// RpcStatus Rpc status code
	RpcStatus string `json:"rpcStatus"`
	// HeadersJson Response header JSON
	HeadersJson skel.JSON `json:"headersJson"`
	// BodyJson Response body JSON
	BodyJson skel.JSON `json:"bodyJson"`
}

// ServiceDebugMethodItem Method called by Service Debug
type ServiceDebugMethodItem struct {
	// Name Method name
	Name string `json:"name"`
	// SkelName Method Skel name
	SkelName string `json:"skelName"`
	// Description Method description
	Description string `json:"description"`
	// Deprecated Whether the method is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Method deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// InputDescription Input description
	InputDescription string `json:"inputDescription"`
	// OutputDescription Output description
	OutputDescription string `json:"outputDescription"`
	// Example Input example
	Example string `json:"example"`
	// OutputExample Output example
	OutputExample string `json:"outputExample"`
	// Arguments Parameter list
	Arguments []SkeletonField `json:"arguments"`
	// ResultType Return type
	ResultType string `json:"resultType"`
}

// ServiceDebugServiceItem Service called by Service Debug
type ServiceDebugServiceItem struct {
	// ServiceSkelName Service Skel name
	ServiceSkelName string `json:"serviceSkelName"`
	// SchemaHash Service schema hash
	SchemaHash string `json:"schemaHash"`
	Api        bool   `json:"api"`
	// Deprecated Whether the Service is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Service deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
}

// ServiceHandlerRegistration Rpc service processing capability registration information provided by the application
type ServiceHandlerRegistration struct {
	// ServiceSkelName Service Skel name
	ServiceSkelName string `json:"serviceSkelName"`
	// SchemaHash Service schema hash
	SchemaHash string `json:"schemaHash"`
	// Endpoint Service agent access address
	Endpoint string `json:"endpoint"`
}

// SkeletonActorItem SkeletonActor
type SkeletonActorItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Actor name
	Name string `json:"name"`
	// SkelName Actor Skel name
	SkelName string `json:"skelName"`
	// Description Actor description
	Description string `json:"description"`
	// Deprecated Whether the Actor is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Actor deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// ActorVias Actor access method list
	ActorVias []string `json:"actorVias"`
	// AuthEnabled Whether to enable authentication
	AuthEnabled bool `json:"authEnabled"`
	// IdentifierField Actor identifier field in Info
	IdentifierField string `json:"identifierField"`
	// Credential Authentication credentials
	Credential *SkeletonData `json:"credential"`
	// Info Authentication information
	Info *SkeletonData `json:"info"`
	// AuthService Authentication services
	AuthService *SkeletonServiceItem `json:"authService"`
	// PermEnabled Whether to enable permissions
	PermEnabled bool `json:"permEnabled"`
	// PermService Permission service
	PermService *SkeletonServiceItem `json:"permService"`
	// PermMethod Permission method
	PermMethod *SkeletonMethod `json:"permMethod"`
	// Services Accessible Service List
	Services []SkeletonServiceItem `json:"services"`
	// Webs Accessible web list
	Webs []SkeletonWebItem `json:"webs"`
}

// SkeletonActorRef Skeleton Actor Reference
type SkeletonActorRef struct {
	// Name Actor name
	Name string `json:"name"`
	// SkelName Actor Skel name
	SkelName string `json:"skelName"`
	// Via Access method
	Via string `json:"via"`
}

// SkeletonConfigItem SkeletonConfig
type SkeletonConfigItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Config name
	Name string `json:"name"`
	// SkelName Config Skel name
	SkelName string `json:"skelName"`
	// Description Config description
	Description string `json:"description"`
	// Deprecated Whether the Config is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Config deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Pub Whether the item is public
	Pub bool `json:"pub"`
	// Sensitive Whether the config value is sensitive
	Sensitive bool `json:"sensitive"`
	// Lifecycle Config lifecycle
	Lifecycle string `json:"lifecycle"`
	// Fields Field list
	Fields []SkeletonField `json:"fields"`
}

// SkeletonData SkeletonData
type SkeletonData struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Data name
	Name string `json:"name"`
	// SkelName Data Skel name
	SkelName string `json:"skelName"`
	// Description Data description
	Description string `json:"description"`
	// Deprecated Whether the Data or Enum is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Data or Enum deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Enum Whether it is Enum
	Enum bool `json:"enum"`
	// Sensitive Whether the data is sensitive
	Sensitive bool `json:"sensitive"`
	// TypeParameters Type parameter list
	TypeParameters []string `json:"typeParameters"`
	// Fields Field list
	Fields []SkeletonField `json:"fields"`
	// EnumItems List of enumeration items
	EnumItems []SkeletonEnumItem `json:"enumItems"`
}

// SkeletonDomain Domain skeleton version
type SkeletonDomain struct {
	// Domain Domain name
	Domain string `json:"domain"`
	// SchemaHash DomainSchema hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary DomainSchema hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether multiple active versions exist
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether this is the primary version
	IsMain bool `json:"isMain"`
	// Total Total number of skeleton items
	Total int `json:"total"`
	// Actors Actor list
	Actors []SkeletonActorItem `json:"actors"`
	// Services Service list
	Services []SkeletonServiceItem `json:"services"`
	// Resources Resource list
	Resources []SkeletonResourceItem `json:"resources"`
	// Data Data list
	Data []SkeletonData `json:"data"`
	// Configs Config list
	Configs []SkeletonConfigItem `json:"configs"`
	// Webs Web list
	Webs []SkeletonWebItem `json:"webs"`
	// Tasks Task list
	Tasks []SkeletonTask `json:"tasks"`
	// Events Event list
	Events []SkeletonEventItem `json:"events"`
}

// SkeletonEnumItem Skeleton enumeration items
type SkeletonEnumItem struct {
	// Name Enumeration item name
	Name string `json:"name"`
	// Description Enumeration item description
	Description string `json:"description"`
	// Deprecated Whether the enumeration item is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Enumeration item deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
}

// SkeletonEventItem Skeleton event
type SkeletonEventItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Event name
	Name string `json:"name"`
	// SkelName Event Skel name
	SkelName string `json:"skelName"`
	// Description Event description
	Description string `json:"description"`
	// Deprecated Whether the Event is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Event deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Pub Whether the item is public
	Pub bool `json:"pub"`
	// Sensitive Whether the event payload is sensitive
	Sensitive bool `json:"sensitive"`
	// Fields Field list
	Fields []SkeletonField `json:"fields"`
}

// SkeletonField Skeleton field
type SkeletonField struct {
	// Name Field name
	Name string `json:"name"`
	// Type Field type
	Type string `json:"type"`
	// Description Field description
	Description string `json:"description"`
	// Deprecated Whether the field is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Field deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Example Field example
	Example string `json:"example"`
	// Sensitive Whether the field is sensitive
	Sensitive bool `json:"sensitive"`
}

// SkeletonMethod Skeleton method
type SkeletonMethod struct {
	// Name Method name
	Name string `json:"name"`
	// SkelName Method Skel name
	SkelName string `json:"skelName"`
	// Description Method description
	Description string `json:"description"`
	// Deprecated Whether the method is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Method deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// InputDescription Input description
	InputDescription string `json:"inputDescription"`
	// OutputDescription Output description
	OutputDescription string `json:"outputDescription"`
	// Example Input example
	Example string `json:"example"`
	// AuthMode Authentication mode
	AuthMode string `json:"authMode"`
	// Require Permission requirements
	Require *SkeletonPermExpr `json:"require"`
	// OutputExample Output example
	OutputExample string `json:"outputExample"`
	// Arguments Parameter list
	Arguments []SkeletonField `json:"arguments"`
	// ArgumentsSensitive Whether all input arguments are sensitive
	ArgumentsSensitive bool `json:"argumentsSensitive"`
	// ResultType Return type
	ResultType string `json:"resultType"`
	// ResultSensitive Whether the result is sensitive
	ResultSensitive bool `json:"resultSensitive"`
}

// SkeletonPermCheck Skeleton permission verification call
type SkeletonPermCheck struct {
	// ResourceSkelName Resource Skel name
	ResourceSkelName string `json:"resourceSkelName"`
	// ActionName Action name
	ActionName string `json:"actionName"`
	// CheckName Check name
	CheckName string `json:"checkName"`
	// ServiceSkelName Check Service Skel name
	ServiceSkelName string `json:"serviceSkelName"`
	// MethodSkelName Check Method Skel name
	MethodSkelName string `json:"methodSkelName"`
	// Arguments Parameter list
	Arguments []SkeletonPermCheckArgument `json:"arguments"`
}

// SkeletonPermCheckArgument Skeleton permission verification parameters
type SkeletonPermCheckArgument struct {
	// Name Parameter name
	Name string `json:"name"`
	// JsonPath Parameter JSON path
	JsonPath string `json:"jsonPath"`
	// Type Parameter type
	Type string `json:"type"`
}

// SkeletonPermExpr Skeleton permission expression
type SkeletonPermExpr struct {
	// Mode Permission expression pattern
	Mode string `json:"mode"`
	// Code Permission code
	Code string `json:"code"`
	// Check Permission verification call
	Check *SkeletonPermCheck `json:"check"`
	// Children Subexpression
	Children []SkeletonPermExpr `json:"children"`
}

// SkeletonResourceAction SkeletonResource Action
type SkeletonResourceAction struct {
	// Name Action name
	Name string `json:"name"`
	// PermissionCode Permission code
	PermissionCode string `json:"permissionCode"`
	// Description Action description
	Description string `json:"description"`
	// Deprecated Whether the Action is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Action deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Checks Check list
	Checks []SkeletonResourceCheck `json:"checks"`
}

// SkeletonResourceCheck SkeletonResource Check
type SkeletonResourceCheck struct {
	// Name Check name
	Name string `json:"name"`
	// Deprecated Whether the Check is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Check deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// MethodName Check method name
	MethodName string `json:"methodName"`
	// MethodSkelName Check method Skel name
	MethodSkelName string `json:"methodSkelName"`
	// Arguments Parameter list
	Arguments []SkeletonField `json:"arguments"`
	// ArgumentsSensitive Whether all input arguments are sensitive
	ArgumentsSensitive bool `json:"argumentsSensitive"`
}

// SkeletonResourceItem Skeleton Resource item
type SkeletonResourceItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Resource name
	Name string `json:"name"`
	// SkelName Resource Skel name
	SkelName string `json:"skelName"`
	// Description Resource description
	Description string `json:"description"`
	// Deprecated Whether the Resource is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Resource deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Checks Resource level Check list
	Checks []SkeletonResourceCheck `json:"checks"`
	// Actions Action list
	Actions []SkeletonResourceAction `json:"actions"`
	// CheckService Check service
	CheckService *SkeletonServiceItem `json:"checkService"`
}

// SkeletonServiceItem Skeleton service items
type SkeletonServiceItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Service name
	Name string `json:"name"`
	// SkelName Service Skel name
	SkelName string `json:"skelName"`
	// Description Service Description
	Description string `json:"description"`
	// Deprecated Whether the Service is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Service deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Pub Whether the item is public
	Pub bool `json:"pub"`
	Api bool `json:"api"`
	// AuthMode Authentication mode
	AuthMode string `json:"authMode"`
	// Require Permission requirements
	Require *SkeletonPermExpr `json:"require"`
	// Actors Accessible Actor List
	Actors []SkeletonActorRef `json:"actors"`
	// Methods Method list
	Methods []SkeletonMethod `json:"methods"`
}

// SkeletonTask Skeleton task
type SkeletonTask struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Task name
	Name string `json:"name"`
	// SkelName Task Skel name
	SkelName string `json:"skelName"`
	// Description Task description
	Description string `json:"description"`
	// Deprecated Whether the Task is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Task deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Triggers Trigger list
	Triggers []SkeletonTrigger `json:"triggers"`
}

// SkeletonTrigger Skeleton task trigger
type SkeletonTrigger struct {
	// Name Trigger name
	Name string `json:"name"`
	// SkelName Trigger Skel name
	SkelName string `json:"skelName"`
	// Description Trigger description
	Description string `json:"description"`
	// Deprecated Whether the Trigger is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Trigger deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// InputDescription Input description
	InputDescription string `json:"inputDescription"`
	// Example Input example
	Example string `json:"example"`
	// Arguments Parameter list
	Arguments []SkeletonField `json:"arguments"`
	// ArgumentsSensitive Whether all input arguments are sensitive
	ArgumentsSensitive bool `json:"argumentsSensitive"`
}

// SkeletonWebItem Skeleton web page
type SkeletonWebItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Web page name
	Name string `json:"name"`
	// SkelName Web Skel name
	SkelName string `json:"skelName"`
	// Description Web page description
	Description string `json:"description"`
	// Deprecated Whether the Web is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Web deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Actors Accessible Actor List
	Actors []SkeletonActorRef `json:"actors"`
}

// TaskDebugDefaultLaunchRequest Task Debug initiates a request by default
type TaskDebugDefaultLaunchRequest struct {
	// TraceId Trace ID
	TraceId string `json:"traceId"`
	// SpanId Span ID
	SpanId string `json:"spanId"`
	// ArgumentsJson Default task parameters JSON
	ArgumentsJson skel.JSON `json:"argumentsJson"`
}

// TaskDebugLaunchRequest Task Debug initiates a request
type TaskDebugLaunchRequest struct {
	// TaskSkelName Task Skel name
	TaskSkelName string `json:"taskSkelName"`
	// SchemaHash Task schema hash
	SchemaHash string `json:"schemaHash"`
	// TriggerSkelName Trigger Skel name
	TriggerSkelName string `json:"triggerSkelName"`
	// ArgumentsJson Task parameters JSON
	ArgumentsJson skel.JSON `json:"argumentsJson"`
	// TraceId Trace ID
	TraceId *string `json:"traceId"`
	// SpanId Span ID
	SpanId *string `json:"spanId"`
}

// TaskDebugTaskItem Task called by Task Debug
type TaskDebugTaskItem struct {
	// Name Task name
	Name string `json:"name"`
	// TaskSkelName Task Skel name
	TaskSkelName string `json:"taskSkelName"`
	// SchemaHash Task schema hash
	SchemaHash string `json:"schemaHash"`
	// Description Task description
	Description string `json:"description"`
	// Deprecated Whether the Task is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Task deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
}

// TaskDebugTriggerItem Trigger called by Task Debug
type TaskDebugTriggerItem struct {
	// Name Trigger name
	Name string `json:"name"`
	// SkelName Trigger Skel name
	SkelName string `json:"skelName"`
	// Description Trigger description
	Description string `json:"description"`
	// Deprecated Whether the Trigger is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Trigger deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// InputDescription Input description
	InputDescription string `json:"inputDescription"`
	// Example Input example
	Example string `json:"example"`
	// Arguments Parameter list
	Arguments []SkeletonField `json:"arguments"`
}

// TaskRunnerCronScheduler Task execution Cron schedule
type TaskRunnerCronScheduler struct {
	// TriggerSkelName Trigger Skel name
	TriggerSkelName string `json:"triggerSkelName"`
	// CronExpr Cron expression
	CronExpr string `json:"cronExpr"`
}

// TaskRunnerRegistration Task execution capability registration information provided by the application
type TaskRunnerRegistration struct {
	// TaskSkelName Task Skel name
	TaskSkelName string `json:"taskSkelName"`
	// SchemaHash Task schema hash
	SchemaHash string `json:"schemaHash"`
	// TimeoutMs Execution timeout, in milliseconds
	TimeoutMs int `json:"timeoutMs"`
	// Concurrency Maximum concurrency
	Concurrency int `json:"concurrency"`
	// NoRetry Whether to disallow retrying after failure
	NoRetry bool `json:"noRetry"`
	// CronSchedulers Cron schedule list
	CronSchedulers []TaskRunnerCronScheduler `json:"cronSchedulers"`
}

// WebHandlerRegistration Web processing capability registration information provided by the application
type WebHandlerRegistration struct {
	// WebSkelName Web Skel name
	WebSkelName string `json:"webSkelName"`
	// SchemaHash Web schema hash
	SchemaHash string `json:"schemaHash"`
	// Endpoint Web proxy access address
	Endpoint string `json:"endpoint"`
}
