// Code generated by skelc. DO NOT EDIT.

package admin

import "go.yorun.ai/vine/internal/core/skel"

// AppConfigCreation Configuration creation parameters
type AppConfigCreation struct {
	// SkelName Configuration Skel name
	SkelName string `json:"skelName"`
	// Value Configuration JSON
	Value string `json:"value"`
}

// Clone returns a value-isolated copy of the generated data.
func (v AppConfigCreation) Clone() AppConfigCreation {
	cloned := v
	return cloned
}

// AppConfigItem Configuration items
type AppConfigItem struct {
	// Id Configuration ID
	Id int `json:"id"`
	// Key Configuration key
	Key string `json:"key"`
	// Status Configuration status
	Status string `json:"status"`
	// Lifecycle Configuration lifecycle
	Lifecycle string `json:"lifecycle"`
	// Value Configuration JSON
	Value string `json:"value"`
	// Schema Configuration schema
	Schema *AppConfigSchema `json:"schema"`
}

// Clone returns a value-isolated copy of the generated data.
func (v AppConfigItem) Clone() AppConfigItem {
	cloned := v
	if v.Schema != nil {
		clonedValue0 := *v.Schema
		clonedValue0 = (*v.Schema).Clone()
		cloned.Schema = &clonedValue0
	}
	return cloned
}

// AppConfigSchema Configuration schema items
type AppConfigSchema struct {
	// SkelName Configuration Skel name
	SkelName string `json:"skelName"`
	// Name Configuration name
	Name string `json:"name"`
	// Description Configuration description
	Description string `json:"description"`
	// Deprecated Whether the configuration is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Configuration deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Lifecycle Configuration lifecycle
	Lifecycle string `json:"lifecycle"`
	// Fields Configuration field list
	Fields []AppConfigSchemaField `json:"fields"`
}

// Clone returns a value-isolated copy of the generated data.
func (v AppConfigSchema) Clone() AppConfigSchema {
	cloned := v
	if v.Fields == nil {
		cloned.Fields = nil
	} else {
		cloned.Fields = make([]AppConfigSchemaField, len(v.Fields))
		for index0 := range v.Fields {
			cloned.Fields[index0] = v.Fields[index0].Clone()
		}
	}
	return cloned
}

// AppConfigSchemaEnumItem Configuration schema enumeration options
type AppConfigSchemaEnumItem struct {
	// Name Enum option name
	Name string `json:"name"`
	// Description Enumeration options description
	Description string `json:"description"`
	// Deprecated Whether the enumeration option is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Enumeration option deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
}

// Clone returns a value-isolated copy of the generated data.
func (v AppConfigSchemaEnumItem) Clone() AppConfigSchemaEnumItem {
	cloned := v
	return cloned
}

// AppConfigSchemaField Configuration schema fields
type AppConfigSchemaField struct {
	// Name Field name
	Name string `json:"name"`
	// Type Field type
	Type string `json:"type"`
	// Description Field description
	Description string `json:"description"`
	// Deprecated Whether the field is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Field deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// EnumItems Enumeration options list
	EnumItems []AppConfigSchemaEnumItem `json:"enumItems"`
}

// Clone returns a value-isolated copy of the generated data.
func (v AppConfigSchemaField) Clone() AppConfigSchemaField {
	cloned := v
	if v.EnumItems == nil {
		cloned.EnumItems = nil
	} else {
		cloned.EnumItems = make([]AppConfigSchemaEnumItem, len(v.EnumItems))
		for index0 := range v.EnumItems {
			cloned.EnumItems[index0] = v.EnumItems[index0].Clone()
		}
	}
	return cloned
}

// AppConfigUpdate Configuration update parameters
type AppConfigUpdate struct {
	// Value Configuration JSON
	Value *string `json:"value"`
}

// Clone returns a value-isolated copy of the generated data.
func (v AppConfigUpdate) Clone() AppConfigUpdate {
	cloned := v
	if v.Value != nil {
		clonedValue0 := *v.Value
		cloned.Value = &clonedValue0
	}
	return cloned
}

// AppStatusView Application instance status view for Dashboard display
type AppStatusView struct {
	// Name Application name
	Name string `json:"name"`
	// InstanceId Application instance ID
	InstanceId string `json:"instanceId"`
	// Version Application version
	Version string `json:"version"`
	// Endpoint Application access address
	Endpoint string `json:"endpoint"`
	// ServiceHandlers List of Rpc service processing capabilities provided by the application
	ServiceHandlers []ServiceHandlerRegistration `json:"serviceHandlers"`
	// WebHandlers List of web processing capabilities provided by the application
	WebHandlers []WebHandlerRegistration `json:"webHandlers"`
	// EventListeners List of event listening capabilities provided by the application
	EventListeners []EventListenerRegistration `json:"eventListeners"`
	// TaskRunners List of task execution capabilities provided by the application
	TaskRunners []TaskRunnerRegistration `json:"taskRunners"`
}

// Clone returns a value-isolated copy of the generated data.
func (v AppStatusView) Clone() AppStatusView {
	cloned := v
	if v.ServiceHandlers == nil {
		cloned.ServiceHandlers = nil
	} else {
		cloned.ServiceHandlers = make([]ServiceHandlerRegistration, len(v.ServiceHandlers))
		for index0 := range v.ServiceHandlers {
			cloned.ServiceHandlers[index0] = v.ServiceHandlers[index0].Clone()
		}
	}
	if v.WebHandlers == nil {
		cloned.WebHandlers = nil
	} else {
		cloned.WebHandlers = make([]WebHandlerRegistration, len(v.WebHandlers))
		for index1 := range v.WebHandlers {
			cloned.WebHandlers[index1] = v.WebHandlers[index1].Clone()
		}
	}
	if v.EventListeners == nil {
		cloned.EventListeners = nil
	} else {
		cloned.EventListeners = make([]EventListenerRegistration, len(v.EventListeners))
		for index2 := range v.EventListeners {
			cloned.EventListeners[index2] = v.EventListeners[index2].Clone()
		}
	}
	if v.TaskRunners == nil {
		cloned.TaskRunners = nil
	} else {
		cloned.TaskRunners = make([]TaskRunnerRegistration, len(v.TaskRunners))
		for index3 := range v.TaskRunners {
			cloned.TaskRunners[index3] = v.TaskRunners[index3].Clone()
		}
	}
	return cloned
}

// EventDebugDefaultEmitRequest Default Event Debug send request
type EventDebugDefaultEmitRequest struct {
	// TraceId Trace ID
	TraceId string `json:"traceId"`
	// SpanId Span ID
	SpanId string `json:"spanId"`
	// EventJson Default event JSON
	EventJson skel.JSON `json:"eventJson"`
}

// Clone returns a value-isolated copy of the generated data.
func (v EventDebugDefaultEmitRequest) Clone() EventDebugDefaultEmitRequest {
	cloned := v
	return cloned
}

// EventDebugEmitRequest Event Debug send request
type EventDebugEmitRequest struct {
	// EventSkelName Event Skel name
	EventSkelName string `json:"eventSkelName"`
	// SchemaHash Event schema hash
	SchemaHash string `json:"schemaHash"`
	// EventJson Event JSON
	EventJson skel.JSON `json:"eventJson"`
	// TraceId Trace ID
	TraceId *string `json:"traceId"`
	// SpanId Span ID
	SpanId *string `json:"spanId"`
}

// Clone returns a value-isolated copy of the generated data.
func (v EventDebugEmitRequest) Clone() EventDebugEmitRequest {
	cloned := v
	if v.TraceId != nil {
		clonedValue0 := *v.TraceId
		cloned.TraceId = &clonedValue0
	}
	if v.SpanId != nil {
		clonedValue1 := *v.SpanId
		cloned.SpanId = &clonedValue1
	}
	return cloned
}

// EventDebugEventItem Event called by Event Debug
type EventDebugEventItem struct {
	// Name Event name
	Name string `json:"name"`
	// EventSkelName Event Skel name
	EventSkelName string `json:"eventSkelName"`
	// SchemaHash Event schema hash
	SchemaHash string `json:"schemaHash"`
	// Description Event description
	Description string `json:"description"`
	// Deprecated Whether the Event is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Event deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Fields Field list
	Fields []SkeletonField `json:"fields"`
}

// Clone returns a value-isolated copy of the generated data.
func (v EventDebugEventItem) Clone() EventDebugEventItem {
	cloned := v
	if v.Fields == nil {
		cloned.Fields = nil
	} else {
		cloned.Fields = make([]SkeletonField, len(v.Fields))
		for index0 := range v.Fields {
			cloned.Fields[index0] = v.Fields[index0].Clone()
		}
	}
	return cloned
}

// EventListenerRegistration Event listening capability registration information provided by the application
type EventListenerRegistration struct {
	// EventSkelName Event Skel name
	EventSkelName string `json:"eventSkelName"`
	// SchemaHash Event schema hash
	SchemaHash string `json:"schemaHash"`
	// TimeoutMs Execution timeout, in milliseconds
	TimeoutMs int `json:"timeoutMs"`
	// Concurrency Maximum concurrency
	Concurrency int `json:"concurrency"`
	// NoRetry Whether to disallow retrying after failure
	NoRetry bool `json:"noRetry"`
}

// Clone returns a value-isolated copy of the generated data.
func (v EventListenerRegistration) Clone() EventListenerRegistration {
	cloned := v
	return cloned
}

// PortalCert Portal site certificate
type PortalCert struct {
	// Id Certificate ID
	Id int `json:"id"`
	// Name Certificate name
	Name string `json:"name"`
	// Issuer Certificate issuer
	Issuer string `json:"issuer"`
	// Domains Certificate domain name
	Domains []string `json:"domains"`
	// PublicKeyBase64 Certificate Base64
	PublicKeyBase64 string `json:"publicKeyBase64"`
	// PrivateKeyConfigured Whether the private key has been configured
	PrivateKeyConfigured bool `json:"privateKeyConfigured"`
	// ValidFrom Validity start time
	ValidFrom skel.Timestamp `json:"validFrom"`
	// ValidTo Validity end time
	ValidTo skel.Timestamp `json:"validTo"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalCert) Clone() PortalCert {
	cloned := v
	if v.Domains == nil {
		cloned.Domains = nil
	} else {
		cloned.Domains = make([]string, len(v.Domains))
		copy(cloned.Domains, v.Domains)
	}
	return cloned
}

// PortalCertCreation Portal site certificate creation parameters
type PortalCertCreation struct {
	// Name Certificate name
	Name string `json:"name"`
	// PublicKeyBase64 Certificate Base64
	PublicKeyBase64 string `json:"publicKeyBase64"`
	// PrivateKeyBase64 Private key Base64
	PrivateKeyBase64 string `json:"privateKeyBase64"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalCertCreation) Clone() PortalCertCreation {
	cloned := v
	return cloned
}

// PortalCertUpdate Portal site certificate update parameters
type PortalCertUpdate struct {
	// Name Certificate name
	Name *string `json:"name"`
	// PublicKeyBase64 Certificate Base64
	PublicKeyBase64 *string `json:"publicKeyBase64"`
	// PrivateKeyBase64 Private key Base64
	PrivateKeyBase64 *string `json:"privateKeyBase64"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalCertUpdate) Clone() PortalCertUpdate {
	cloned := v
	if v.Name != nil {
		clonedValue0 := *v.Name
		cloned.Name = &clonedValue0
	}
	if v.PublicKeyBase64 != nil {
		clonedValue1 := *v.PublicKeyBase64
		cloned.PublicKeyBase64 = &clonedValue1
	}
	if v.PrivateKeyBase64 != nil {
		clonedValue2 := *v.PrivateKeyBase64
		cloned.PrivateKeyBase64 = &clonedValue2
	}
	return cloned
}

// PortalCors Portal site CORS configuration
type PortalCors struct {
	// Mode CORS mode: DISABLED/SAME_DOMAIN/STRICT
	Mode PortalCorsMode `json:"mode"`
	// AllowedOrigins List of origins allowed in strict mode
	AllowedOrigins []string `json:"allowedOrigins"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalCors) Clone() PortalCors {
	cloned := v
	if v.AllowedOrigins == nil {
		cloned.AllowedOrigins = nil
	} else {
		cloned.AllowedOrigins = make([]string, len(v.AllowedOrigins))
		copy(cloned.AllowedOrigins, v.AllowedOrigins)
	}
	return cloned
}

// PortalDashboardAccess Hub Dashboard access entry
type PortalDashboardAccess struct {
	// Scheme Entry protocol
	Scheme string `json:"scheme"`
	// Host Match Host, empty string means no restriction
	Host string `json:"host"`
	// Port Entry port
	Port int `json:"port"`
	// PathPrefix Match path prefix
	PathPrefix string `json:"pathPrefix"`
	// CanUpdate Whether to allow modification of Dashboard access entry
	CanUpdate bool `json:"canUpdate"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalDashboardAccess) Clone() PortalDashboardAccess {
	cloned := v
	return cloned
}

// PortalEntry Portal access entry
type PortalEntry struct {
	// Name Entry name
	Name string `json:"name"`
	// Scheme Entry protocol
	Scheme string `json:"scheme"`
	// Host Match Host, empty string means no restriction
	Host string `json:"host"`
	// Port Entry port
	Port int `json:"port"`
	// Rules Entry rule list
	Rules []PortalEntryRule `json:"rules"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalEntry) Clone() PortalEntry {
	cloned := v
	if v.Rules == nil {
		cloned.Rules = nil
	} else {
		cloned.Rules = make([]PortalEntryRule, len(v.Rules))
		for index0 := range v.Rules {
			cloned.Rules[index0] = v.Rules[index0].Clone()
		}
	}
	return cloned
}

// PortalEntryAccessUpdate Portal access entry configuration update parameters
type PortalEntryAccessUpdate struct {
	// Scheme Entry protocol
	Scheme string `json:"scheme"`
	// Host Match Host, empty string means no restriction
	Host string `json:"host"`
	// Port Entry port
	Port int `json:"port"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalEntryAccessUpdate) Clone() PortalEntryAccessUpdate {
	cloned := v
	return cloned
}

// PortalEntryRule Portal access entry rules
type PortalEntryRule struct {
	// Rule Entry rules
	Rule PortalRule `json:"rule"`
	// Site Target site
	Site *PortalSite `json:"site"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalEntryRule) Clone() PortalEntryRule {
	cloned := v
	cloned.Rule = v.Rule.Clone()
	if v.Site != nil {
		clonedValue0 := *v.Site
		clonedValue0 = (*v.Site).Clone()
		cloned.Site = &clonedValue0
	}
	return cloned
}

// PortalRule Portal entry rules
type PortalRule struct {
	// Id Rule ID
	Id int `json:"id"`
	// Name Rule name
	Name string `json:"name"`
	// MatchScheme Matching protocol
	MatchScheme string `json:"matchScheme"`
	// MatchHost Match Host, empty string means no restriction
	MatchHost string `json:"matchHost"`
	// MatchPort Match matchPort, 0 means no restriction
	MatchPort int `json:"matchPort"`
	// MatchPathPrefix Match path prefix, empty string means match all paths
	MatchPathPrefix string `json:"matchPathPrefix"`
	// RouteType Target type
	RouteType string `json:"routeType"`
	// RouteSiteName Site name
	RouteSiteName string `json:"routeSiteName"`
	// RouteRedirectionPattern Redirect Pattern
	RouteRedirectionPattern string `json:"routeRedirectionPattern"`
	// RoutePathPrefix Target site path prefix; empty means strip the matching prefix only
	RoutePathPrefix string `json:"routePathPrefix"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalRule) Clone() PortalRule {
	cloned := v
	return cloned
}

// PortalRuleCreation Portal entry rule creation parameters
type PortalRuleCreation struct {
	// Name Rule name
	Name string `json:"name"`
	// MatchScheme Matching protocol
	MatchScheme string `json:"matchScheme"`
	// MatchHost Match Host, empty string means no restriction
	MatchHost string `json:"matchHost"`
	// MatchPort Match matchPort, 0 means no restriction
	MatchPort int `json:"matchPort"`
	// MatchPathPrefix Match path prefix, empty string means match all paths
	MatchPathPrefix string `json:"matchPathPrefix"`
	// RouteType Target type
	RouteType string `json:"routeType"`
	// RouteSiteName Site name
	RouteSiteName string `json:"routeSiteName"`
	// RouteRedirectionPattern Redirect Pattern
	RouteRedirectionPattern string `json:"routeRedirectionPattern"`
	// RoutePathPrefix Target site path prefix; empty means strip the matching prefix only
	RoutePathPrefix *string `json:"routePathPrefix"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalRuleCreation) Clone() PortalRuleCreation {
	cloned := v
	if v.RoutePathPrefix != nil {
		clonedValue0 := *v.RoutePathPrefix
		cloned.RoutePathPrefix = &clonedValue0
	}
	return cloned
}

// PortalRuleUpdate Portal entry rule update parameters
type PortalRuleUpdate struct {
	// Name Rule name
	Name *string `json:"name"`
	// MatchScheme Matching protocol
	MatchScheme *string `json:"matchScheme"`
	// MatchHost Match Host, empty string means no restriction
	MatchHost *string `json:"matchHost"`
	// MatchPort Match matchPort, 0 means no restriction
	MatchPort *int `json:"matchPort"`
	// MatchPathPrefix Match path prefix, empty string means match all paths
	MatchPathPrefix *string `json:"matchPathPrefix"`
	// RouteType Target type
	RouteType *string `json:"routeType"`
	// RouteSiteName Site name
	RouteSiteName *string `json:"routeSiteName"`
	// RouteRedirectionPattern Redirect Pattern
	RouteRedirectionPattern *string `json:"routeRedirectionPattern"`
	// RoutePathPrefix Target site path prefix; empty means strip the matching prefix only
	RoutePathPrefix *string `json:"routePathPrefix"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalRuleUpdate) Clone() PortalRuleUpdate {
	cloned := v
	if v.Name != nil {
		clonedValue0 := *v.Name
		cloned.Name = &clonedValue0
	}
	if v.MatchScheme != nil {
		clonedValue1 := *v.MatchScheme
		cloned.MatchScheme = &clonedValue1
	}
	if v.MatchHost != nil {
		clonedValue2 := *v.MatchHost
		cloned.MatchHost = &clonedValue2
	}
	if v.MatchPort != nil {
		clonedValue3 := *v.MatchPort
		cloned.MatchPort = &clonedValue3
	}
	if v.MatchPathPrefix != nil {
		clonedValue4 := *v.MatchPathPrefix
		cloned.MatchPathPrefix = &clonedValue4
	}
	if v.RouteType != nil {
		clonedValue5 := *v.RouteType
		cloned.RouteType = &clonedValue5
	}
	if v.RouteSiteName != nil {
		clonedValue6 := *v.RouteSiteName
		cloned.RouteSiteName = &clonedValue6
	}
	if v.RouteRedirectionPattern != nil {
		clonedValue7 := *v.RouteRedirectionPattern
		cloned.RouteRedirectionPattern = &clonedValue7
	}
	if v.RoutePathPrefix != nil {
		clonedValue8 := *v.RoutePathPrefix
		cloned.RoutePathPrefix = &clonedValue8
	}
	return cloned
}

// PortalSite Portal target site
type PortalSite struct {
	// Id Target site id
	Id int `json:"id"`
	// Name Target site name
	Name string `json:"name"`
	// Type Target site type
	Type PortalSiteType `json:"type"`
	// ActorSkelName Actor Skel name
	ActorSkelName string `json:"actorSkelName"`
	// ActorVia Actor access method
	ActorVia string `json:"actorVia"`
	// RpcgwServices Rpc gateway service Skel name list
	RpcgwServices []string `json:"rpcgwServices"`
	// Cors CORS configuration
	Cors *PortalCors `json:"cors"`
	// WebName Web name
	WebName string `json:"webName"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalSite) Clone() PortalSite {
	cloned := v
	if v.RpcgwServices == nil {
		cloned.RpcgwServices = nil
	} else {
		cloned.RpcgwServices = make([]string, len(v.RpcgwServices))
		copy(cloned.RpcgwServices, v.RpcgwServices)
	}
	if v.Cors != nil {
		clonedValue1 := *v.Cors
		clonedValue1 = (*v.Cors).Clone()
		cloned.Cors = &clonedValue1
	}
	return cloned
}

// PortalSiteActorOption Portal target site Actor options
type PortalSiteActorOption struct {
	// Name Actor name
	Name string `json:"name"`
	// SkelName Actor Skel name
	SkelName string `json:"skelName"`
	// ActorVias Actor access method list
	ActorVias []string `json:"actorVias"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalSiteActorOption) Clone() PortalSiteActorOption {
	cloned := v
	if v.ActorVias == nil {
		cloned.ActorVias = nil
	} else {
		cloned.ActorVias = make([]string, len(v.ActorVias))
		copy(cloned.ActorVias, v.ActorVias)
	}
	return cloned
}

// PortalSiteCreation Portal target site creation parameters
type PortalSiteCreation struct {
	// Name Target site name
	Name string `json:"name"`
	// Type Target site type
	Type PortalSiteType `json:"type"`
	// ActorSkelName Actor Skel name
	ActorSkelName string `json:"actorSkelName"`
	// ActorVia Actor access method
	ActorVia string `json:"actorVia"`
	// Cors CORS configuration
	Cors *PortalCors `json:"cors"`
	// WebName Web name
	WebName string `json:"webName"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalSiteCreation) Clone() PortalSiteCreation {
	cloned := v
	if v.Cors != nil {
		clonedValue0 := *v.Cors
		clonedValue0 = (*v.Cors).Clone()
		cloned.Cors = &clonedValue0
	}
	return cloned
}

// PortalSiteOptions Portal target site form options
type PortalSiteOptions struct {
	// Actors Actor options
	Actors []PortalSiteActorOption `json:"actors"`
	// Services Rpc service options
	Services []PortalSiteServiceOption `json:"services"`
	// Webs Web options
	Webs []PortalSiteWebOption `json:"webs"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalSiteOptions) Clone() PortalSiteOptions {
	cloned := v
	if v.Actors == nil {
		cloned.Actors = nil
	} else {
		cloned.Actors = make([]PortalSiteActorOption, len(v.Actors))
		for index0 := range v.Actors {
			cloned.Actors[index0] = v.Actors[index0].Clone()
		}
	}
	if v.Services == nil {
		cloned.Services = nil
	} else {
		cloned.Services = make([]PortalSiteServiceOption, len(v.Services))
		for index1 := range v.Services {
			cloned.Services[index1] = v.Services[index1].Clone()
		}
	}
	if v.Webs == nil {
		cloned.Webs = nil
	} else {
		cloned.Webs = make([]PortalSiteWebOption, len(v.Webs))
		for index2 := range v.Webs {
			cloned.Webs[index2] = v.Webs[index2].Clone()
		}
	}
	return cloned
}

// PortalSiteServiceOption Portal target site service options
type PortalSiteServiceOption struct {
	// Name Service name
	Name string `json:"name"`
	// SkelName Service Skel name
	SkelName string `json:"skelName"`
	// ActorSkelNames Actor Skel name list
	ActorSkelNames []string `json:"actorSkelNames"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalSiteServiceOption) Clone() PortalSiteServiceOption {
	cloned := v
	if v.ActorSkelNames == nil {
		cloned.ActorSkelNames = nil
	} else {
		cloned.ActorSkelNames = make([]string, len(v.ActorSkelNames))
		copy(cloned.ActorSkelNames, v.ActorSkelNames)
	}
	return cloned
}

// PortalSiteUpdate Portal target site update parameters
type PortalSiteUpdate struct {
	// Name Target site name
	Name *string `json:"name"`
	// Type Target site type
	Type *PortalSiteType `json:"type"`
	// ActorSkelName Actor Skel name
	ActorSkelName *string `json:"actorSkelName"`
	// ActorVia Actor access method
	ActorVia *string `json:"actorVia"`
	// Cors CORS configuration
	Cors *PortalCors `json:"cors"`
	// WebName Web name
	WebName *string `json:"webName"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalSiteUpdate) Clone() PortalSiteUpdate {
	cloned := v
	if v.Name != nil {
		clonedValue0 := *v.Name
		cloned.Name = &clonedValue0
	}
	if v.Type != nil {
		clonedValue1 := *v.Type
		cloned.Type = &clonedValue1
	}
	if v.ActorSkelName != nil {
		clonedValue2 := *v.ActorSkelName
		cloned.ActorSkelName = &clonedValue2
	}
	if v.ActorVia != nil {
		clonedValue3 := *v.ActorVia
		cloned.ActorVia = &clonedValue3
	}
	if v.Cors != nil {
		clonedValue4 := *v.Cors
		clonedValue4 = (*v.Cors).Clone()
		cloned.Cors = &clonedValue4
	}
	if v.WebName != nil {
		clonedValue5 := *v.WebName
		cloned.WebName = &clonedValue5
	}
	return cloned
}

// PortalSiteWebOption Portal target site web options
type PortalSiteWebOption struct {
	// Name Web name
	Name string `json:"name"`
	// SkelName Web Skel name
	SkelName string `json:"skelName"`
	// ActorSkelNames Actor Skel name list
	ActorSkelNames []string `json:"actorSkelNames"`
}

// Clone returns a value-isolated copy of the generated data.
func (v PortalSiteWebOption) Clone() PortalSiteWebOption {
	cloned := v
	if v.ActorSkelNames == nil {
		cloned.ActorSkelNames = nil
	} else {
		cloned.ActorSkelNames = make([]string, len(v.ActorSkelNames))
		copy(cloned.ActorSkelNames, v.ActorSkelNames)
	}
	return cloned
}

// SeedEntityDiff Seed entity differences
type SeedEntityDiff struct {
	// Kind Entity type
	Kind string `json:"kind"`
	// Name Entity name
	Name string `json:"name"`
	// Exists Whether the entity currently exists
	Exists bool `json:"exists"`
	// Fields Field differences
	Fields []SeedFieldDiff `json:"fields"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SeedEntityDiff) Clone() SeedEntityDiff {
	cloned := v
	if v.Fields == nil {
		cloned.Fields = nil
	} else {
		cloned.Fields = make([]SeedFieldDiff, len(v.Fields))
		for index0 := range v.Fields {
			cloned.Fields[index0] = v.Fields[index0].Clone()
		}
	}
	return cloned
}

// SeedFieldDiff Seed field differences
type SeedFieldDiff struct {
	// Name Field name
	Name string `json:"name"`
	// CurrentValue Current value
	CurrentValue string `json:"currentValue"`
	// SeedValue Seed value
	SeedValue string `json:"seedValue"`
	// Changed Whether the values differ
	Changed bool `json:"changed"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SeedFieldDiff) Clone() SeedFieldDiff {
	cloned := v
	return cloned
}

// SeedItemSelection Seed entity selection
type SeedItemSelection struct {
	// Kind Entity type
	Kind string `json:"kind"`
	// Name Entity name
	Name string `json:"name"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SeedItemSelection) Clone() SeedItemSelection {
	cloned := v
	return cloned
}

// SeedPreview Seed preview
type SeedPreview struct {
	// Items Entity differences
	Items []SeedEntityDiff `json:"items"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SeedPreview) Clone() SeedPreview {
	cloned := v
	if v.Items == nil {
		cloned.Items = nil
	} else {
		cloned.Items = make([]SeedEntityDiff, len(v.Items))
		for index0 := range v.Items {
			cloned.Items[index0] = v.Items[index0].Clone()
		}
	}
	return cloned
}

// ServiceDebugActorItem Service Debug Actor options
type ServiceDebugActorItem struct {
	// Name Actor name
	Name string `json:"name"`
	// SkelName Actor Skel name
	SkelName string `json:"skelName"`
	// InfoSkelName Actor Info Skel name
	InfoSkelName string `json:"infoSkelName"`
	// ActorInfoJson Default Actor Info JSON
	ActorInfoJson skel.JSON `json:"actorInfoJson"`
}

// Clone returns a value-isolated copy of the generated data.
func (v ServiceDebugActorItem) Clone() ServiceDebugActorItem {
	cloned := v
	return cloned
}

// ServiceDebugAppInstance Application instance called by Service Debug
type ServiceDebugAppInstance struct {
	// AppName Application name
	AppName string `json:"appName"`
	// AppInstanceId Application instance ID
	AppInstanceId string `json:"appInstanceId"`
	// AppVersion Application version
	AppVersion string `json:"appVersion"`
	// Endpoint Application access address
	Endpoint string `json:"endpoint"`
}

// Clone returns a value-isolated copy of the generated data.
func (v ServiceDebugAppInstance) Clone() ServiceDebugAppInstance {
	cloned := v
	return cloned
}

// ServiceDebugDefaultInvokeRequest Service Debug default call request
type ServiceDebugDefaultInvokeRequest struct {
	// TraceId Trace ID
	TraceId string `json:"traceId"`
	// SpanId Span ID
	SpanId string `json:"spanId"`
	// Actors Actor options
	Actors []ServiceDebugActorItem `json:"actors"`
	// ActorSkelName Default Actor Skel name
	ActorSkelName *string `json:"actorSkelName"`
	// ActorInfoJson Default Actor Info JSON
	ActorInfoJson skel.JSON `json:"actorInfoJson"`
	// ParamsJson Default request parameters JSON
	ParamsJson skel.JSON `json:"paramsJson"`
}

// Clone returns a value-isolated copy of the generated data.
func (v ServiceDebugDefaultInvokeRequest) Clone() ServiceDebugDefaultInvokeRequest {
	cloned := v
	if v.Actors == nil {
		cloned.Actors = nil
	} else {
		cloned.Actors = make([]ServiceDebugActorItem, len(v.Actors))
		for index0 := range v.Actors {
			cloned.Actors[index0] = v.Actors[index0].Clone()
		}
	}
	if v.ActorSkelName != nil {
		clonedValue1 := *v.ActorSkelName
		cloned.ActorSkelName = &clonedValue1
	}
	return cloned
}

// ServiceDebugInvokeRequest Service Debug call request
type ServiceDebugInvokeRequest struct {
	// AppName Application name
	AppName *string `json:"appName"`
	// AppInstanceId Application instance ID
	AppInstanceId *string `json:"appInstanceId"`
	// ServiceSkelName Service Skel name
	ServiceSkelName string `json:"serviceSkelName"`
	// SchemaHash Service schema hash
	SchemaHash string `json:"schemaHash"`
	// MethodSkelName Method Skel name
	MethodSkelName string `json:"methodSkelName"`
	// ParamsJson Request parameters JSON
	ParamsJson skel.JSON `json:"paramsJson"`
	// TimeoutSeconds Call timeout, in seconds
	TimeoutSeconds int `json:"timeoutSeconds"`
	// TraceId Trace ID
	TraceId *string `json:"traceId"`
	// SpanId Span ID
	SpanId *string `json:"spanId"`
	// ActorSkelName Actor Skel name
	ActorSkelName *string `json:"actorSkelName"`
	// ActorInfoJson Actor Info JSON
	ActorInfoJson skel.JSON `json:"actorInfoJson"`
}

// Clone returns a value-isolated copy of the generated data.
func (v ServiceDebugInvokeRequest) Clone() ServiceDebugInvokeRequest {
	cloned := v
	if v.AppName != nil {
		clonedValue0 := *v.AppName
		cloned.AppName = &clonedValue0
	}
	if v.AppInstanceId != nil {
		clonedValue1 := *v.AppInstanceId
		cloned.AppInstanceId = &clonedValue1
	}
	if v.TraceId != nil {
		clonedValue2 := *v.TraceId
		cloned.TraceId = &clonedValue2
	}
	if v.SpanId != nil {
		clonedValue3 := *v.SpanId
		cloned.SpanId = &clonedValue3
	}
	if v.ActorSkelName != nil {
		clonedValue4 := *v.ActorSkelName
		cloned.ActorSkelName = &clonedValue4
	}
	return cloned
}

// ServiceDebugInvokeResponse Service Debug call response
type ServiceDebugInvokeResponse struct {
	// HttpStatus HTTP status code
	HttpStatus int `json:"httpStatus"`
	// RpcStatus Rpc status code
	RpcStatus string `json:"rpcStatus"`
	// HeadersJson Response header JSON
	HeadersJson skel.JSON `json:"headersJson"`
	// BodyJson Response body JSON
	BodyJson skel.JSON `json:"bodyJson"`
}

// Clone returns a value-isolated copy of the generated data.
func (v ServiceDebugInvokeResponse) Clone() ServiceDebugInvokeResponse {
	cloned := v
	return cloned
}

// ServiceDebugMethodItem Method called by Service Debug
type ServiceDebugMethodItem struct {
	// Name Method name
	Name string `json:"name"`
	// SkelName Method Skel name
	SkelName string `json:"skelName"`
	// Description Method description
	Description string `json:"description"`
	// Deprecated Whether the method is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Method deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// InputDescription Input description
	InputDescription string `json:"inputDescription"`
	// OutputDescription Output description
	OutputDescription string `json:"outputDescription"`
	// Example Input example
	Example string `json:"example"`
	// OutputExample Output example
	OutputExample string `json:"outputExample"`
	// Arguments Parameter list
	Arguments []SkeletonField `json:"arguments"`
	// ResultType Return type
	ResultType string `json:"resultType"`
}

// Clone returns a value-isolated copy of the generated data.
func (v ServiceDebugMethodItem) Clone() ServiceDebugMethodItem {
	cloned := v
	if v.Arguments == nil {
		cloned.Arguments = nil
	} else {
		cloned.Arguments = make([]SkeletonField, len(v.Arguments))
		for index0 := range v.Arguments {
			cloned.Arguments[index0] = v.Arguments[index0].Clone()
		}
	}
	return cloned
}

// ServiceDebugServiceItem Service called by Service Debug
type ServiceDebugServiceItem struct {
	// ServiceSkelName Service Skel name
	ServiceSkelName string `json:"serviceSkelName"`
	// SchemaHash Service schema hash
	SchemaHash string `json:"schemaHash"`
	Api        bool   `json:"api"`
	// Deprecated Whether the Service is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Service deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
}

// Clone returns a value-isolated copy of the generated data.
func (v ServiceDebugServiceItem) Clone() ServiceDebugServiceItem {
	cloned := v
	return cloned
}

// ServiceHandlerRegistration Rpc service processing capability registration information provided by the application
type ServiceHandlerRegistration struct {
	// ServiceSkelName Service Skel name
	ServiceSkelName string `json:"serviceSkelName"`
	// SchemaHash Service schema hash
	SchemaHash string `json:"schemaHash"`
	// Endpoint Service agent access address
	Endpoint string `json:"endpoint"`
}

// Clone returns a value-isolated copy of the generated data.
func (v ServiceHandlerRegistration) Clone() ServiceHandlerRegistration {
	cloned := v
	return cloned
}

// SkeletonActorItem SkeletonActor
type SkeletonActorItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Actor name
	Name string `json:"name"`
	// SkelName Actor Skel name
	SkelName string `json:"skelName"`
	// Description Actor description
	Description string `json:"description"`
	// Deprecated Whether the Actor is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Actor deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// ActorVias Actor access method list
	ActorVias []string `json:"actorVias"`
	// AuthEnabled Whether to enable authentication
	AuthEnabled bool `json:"authEnabled"`
	// IdentifierField Actor identifier field in Info
	IdentifierField string `json:"identifierField"`
	// Credential Authentication credentials
	Credential *SkeletonData `json:"credential"`
	// Info Authentication information
	Info *SkeletonData `json:"info"`
	// AuthService Authentication services
	AuthService *SkeletonServiceItem `json:"authService"`
	// PermEnabled Whether to enable permissions
	PermEnabled bool `json:"permEnabled"`
	// PermService Permission service
	PermService *SkeletonServiceItem `json:"permService"`
	// PermMethod Permission method
	PermMethod *SkeletonMethod `json:"permMethod"`
	// Services Accessible Service List
	Services []SkeletonServiceItem `json:"services"`
	// Webs Accessible web list
	Webs []SkeletonWebItem `json:"webs"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonActorItem) Clone() SkeletonActorItem {
	cloned := v
	if v.ActorVias == nil {
		cloned.ActorVias = nil
	} else {
		cloned.ActorVias = make([]string, len(v.ActorVias))
		copy(cloned.ActorVias, v.ActorVias)
	}
	if v.Credential != nil {
		clonedValue1 := *v.Credential
		clonedValue1 = (*v.Credential).Clone()
		cloned.Credential = &clonedValue1
	}
	if v.Info != nil {
		clonedValue2 := *v.Info
		clonedValue2 = (*v.Info).Clone()
		cloned.Info = &clonedValue2
	}
	if v.AuthService != nil {
		clonedValue3 := *v.AuthService
		clonedValue3 = (*v.AuthService).Clone()
		cloned.AuthService = &clonedValue3
	}
	if v.PermService != nil {
		clonedValue4 := *v.PermService
		clonedValue4 = (*v.PermService).Clone()
		cloned.PermService = &clonedValue4
	}
	if v.PermMethod != nil {
		clonedValue5 := *v.PermMethod
		clonedValue5 = (*v.PermMethod).Clone()
		cloned.PermMethod = &clonedValue5
	}
	if v.Services == nil {
		cloned.Services = nil
	} else {
		cloned.Services = make([]SkeletonServiceItem, len(v.Services))
		for index6 := range v.Services {
			cloned.Services[index6] = v.Services[index6].Clone()
		}
	}
	if v.Webs == nil {
		cloned.Webs = nil
	} else {
		cloned.Webs = make([]SkeletonWebItem, len(v.Webs))
		for index7 := range v.Webs {
			cloned.Webs[index7] = v.Webs[index7].Clone()
		}
	}
	return cloned
}

// SkeletonActorRef Skeleton Actor Reference
type SkeletonActorRef struct {
	// Name Actor name
	Name string `json:"name"`
	// SkelName Actor Skel name
	SkelName string `json:"skelName"`
	// Via Access method
	Via string `json:"via"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonActorRef) Clone() SkeletonActorRef {
	cloned := v
	return cloned
}

// SkeletonConfigItem SkeletonConfig
type SkeletonConfigItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Config name
	Name string `json:"name"`
	// SkelName Config Skel name
	SkelName string `json:"skelName"`
	// Description Config description
	Description string `json:"description"`
	// Deprecated Whether the Config is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Config deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Pub Whether the item is public
	Pub bool `json:"pub"`
	// Sensitive Whether the config value is sensitive
	Sensitive bool `json:"sensitive"`
	// Lifecycle Config lifecycle
	Lifecycle string `json:"lifecycle"`
	// Fields Field list
	Fields []SkeletonField `json:"fields"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonConfigItem) Clone() SkeletonConfigItem {
	cloned := v
	if v.Fields == nil {
		cloned.Fields = nil
	} else {
		cloned.Fields = make([]SkeletonField, len(v.Fields))
		for index0 := range v.Fields {
			cloned.Fields[index0] = v.Fields[index0].Clone()
		}
	}
	return cloned
}

// SkeletonData SkeletonData
type SkeletonData struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Data name
	Name string `json:"name"`
	// SkelName Data Skel name
	SkelName string `json:"skelName"`
	// Description Data description
	Description string `json:"description"`
	// Deprecated Whether the Data or Enum is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Data or Enum deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Enum Whether it is Enum
	Enum bool `json:"enum"`
	// Sensitive Whether the data is sensitive
	Sensitive bool `json:"sensitive"`
	// TypeParameters Type parameter list
	TypeParameters []string `json:"typeParameters"`
	// Fields Field list
	Fields []SkeletonField `json:"fields"`
	// EnumItems List of enumeration items
	EnumItems []SkeletonEnumItem `json:"enumItems"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonData) Clone() SkeletonData {
	cloned := v
	if v.TypeParameters == nil {
		cloned.TypeParameters = nil
	} else {
		cloned.TypeParameters = make([]string, len(v.TypeParameters))
		copy(cloned.TypeParameters, v.TypeParameters)
	}
	if v.Fields == nil {
		cloned.Fields = nil
	} else {
		cloned.Fields = make([]SkeletonField, len(v.Fields))
		for index1 := range v.Fields {
			cloned.Fields[index1] = v.Fields[index1].Clone()
		}
	}
	if v.EnumItems == nil {
		cloned.EnumItems = nil
	} else {
		cloned.EnumItems = make([]SkeletonEnumItem, len(v.EnumItems))
		for index2 := range v.EnumItems {
			cloned.EnumItems[index2] = v.EnumItems[index2].Clone()
		}
	}
	return cloned
}

// SkeletonDomain Domain skeleton version
type SkeletonDomain struct {
	// Domain Domain name
	Domain string `json:"domain"`
	// SchemaHash DomainSchema hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary DomainSchema hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether multiple active versions exist
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether this is the primary version
	IsMain bool `json:"isMain"`
	// Total Total number of skeleton items
	Total int `json:"total"`
	// Actors Actor list
	Actors []SkeletonActorItem `json:"actors"`
	// Services Service list
	Services []SkeletonServiceItem `json:"services"`
	// Resources Resource list
	Resources []SkeletonResourceItem `json:"resources"`
	// Data Data list
	Data []SkeletonData `json:"data"`
	// Configs Config list
	Configs []SkeletonConfigItem `json:"configs"`
	// Webs Web list
	Webs []SkeletonWebItem `json:"webs"`
	// Tasks Task list
	Tasks []SkeletonTask `json:"tasks"`
	// Events Event list
	Events []SkeletonEventItem `json:"events"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonDomain) Clone() SkeletonDomain {
	cloned := v
	if v.Actors == nil {
		cloned.Actors = nil
	} else {
		cloned.Actors = make([]SkeletonActorItem, len(v.Actors))
		for index0 := range v.Actors {
			cloned.Actors[index0] = v.Actors[index0].Clone()
		}
	}
	if v.Services == nil {
		cloned.Services = nil
	} else {
		cloned.Services = make([]SkeletonServiceItem, len(v.Services))
		for index1 := range v.Services {
			cloned.Services[index1] = v.Services[index1].Clone()
		}
	}
	if v.Resources == nil {
		cloned.Resources = nil
	} else {
		cloned.Resources = make([]SkeletonResourceItem, len(v.Resources))
		for index2 := range v.Resources {
			cloned.Resources[index2] = v.Resources[index2].Clone()
		}
	}
	if v.Data == nil {
		cloned.Data = nil
	} else {
		cloned.Data = make([]SkeletonData, len(v.Data))
		for index3 := range v.Data {
			cloned.Data[index3] = v.Data[index3].Clone()
		}
	}
	if v.Configs == nil {
		cloned.Configs = nil
	} else {
		cloned.Configs = make([]SkeletonConfigItem, len(v.Configs))
		for index4 := range v.Configs {
			cloned.Configs[index4] = v.Configs[index4].Clone()
		}
	}
	if v.Webs == nil {
		cloned.Webs = nil
	} else {
		cloned.Webs = make([]SkeletonWebItem, len(v.Webs))
		for index5 := range v.Webs {
			cloned.Webs[index5] = v.Webs[index5].Clone()
		}
	}
	if v.Tasks == nil {
		cloned.Tasks = nil
	} else {
		cloned.Tasks = make([]SkeletonTask, len(v.Tasks))
		for index6 := range v.Tasks {
			cloned.Tasks[index6] = v.Tasks[index6].Clone()
		}
	}
	if v.Events == nil {
		cloned.Events = nil
	} else {
		cloned.Events = make([]SkeletonEventItem, len(v.Events))
		for index7 := range v.Events {
			cloned.Events[index7] = v.Events[index7].Clone()
		}
	}
	return cloned
}

// SkeletonEnumItem Skeleton enumeration items
type SkeletonEnumItem struct {
	// Name Enumeration item name
	Name string `json:"name"`
	// Description Enumeration item description
	Description string `json:"description"`
	// Deprecated Whether the enumeration item is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Enumeration item deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonEnumItem) Clone() SkeletonEnumItem {
	cloned := v
	return cloned
}

// SkeletonEventItem Skeleton event
type SkeletonEventItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Event name
	Name string `json:"name"`
	// SkelName Event Skel name
	SkelName string `json:"skelName"`
	// Description Event description
	Description string `json:"description"`
	// Deprecated Whether the Event is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Event deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Pub Whether the item is public
	Pub bool `json:"pub"`
	// Sensitive Whether the event payload is sensitive
	Sensitive bool `json:"sensitive"`
	// Fields Field list
	Fields []SkeletonField `json:"fields"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonEventItem) Clone() SkeletonEventItem {
	cloned := v
	if v.Fields == nil {
		cloned.Fields = nil
	} else {
		cloned.Fields = make([]SkeletonField, len(v.Fields))
		for index0 := range v.Fields {
			cloned.Fields[index0] = v.Fields[index0].Clone()
		}
	}
	return cloned
}

// SkeletonField Skeleton field
type SkeletonField struct {
	// Name Field name
	Name string `json:"name"`
	// Type Field type
	Type string `json:"type"`
	// Description Field description
	Description string `json:"description"`
	// Deprecated Whether the field is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Field deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Example Field example
	Example string `json:"example"`
	// Sensitive Whether the field is sensitive
	Sensitive bool `json:"sensitive"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonField) Clone() SkeletonField {
	cloned := v
	return cloned
}

// SkeletonMethod Skeleton method
type SkeletonMethod struct {
	// Name Method name
	Name string `json:"name"`
	// SkelName Method Skel name
	SkelName string `json:"skelName"`
	// Description Method description
	Description string `json:"description"`
	// Deprecated Whether the method is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Method deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// InputDescription Input description
	InputDescription string `json:"inputDescription"`
	// OutputDescription Output description
	OutputDescription string `json:"outputDescription"`
	// Example Input example
	Example string `json:"example"`
	// AuthMode Authentication mode
	AuthMode string `json:"authMode"`
	// Require Permission requirements
	Require *SkeletonPermExpr `json:"require"`
	// OutputExample Output example
	OutputExample string `json:"outputExample"`
	// Arguments Parameter list
	Arguments []SkeletonField `json:"arguments"`
	// ArgumentsSensitive Whether all input arguments are sensitive
	ArgumentsSensitive bool `json:"argumentsSensitive"`
	// ResultType Return type
	ResultType string `json:"resultType"`
	// ResultSensitive Whether the result is sensitive
	ResultSensitive bool `json:"resultSensitive"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonMethod) Clone() SkeletonMethod {
	cloned := v
	if v.Require != nil {
		clonedValue0 := *v.Require
		clonedValue0 = (*v.Require).Clone()
		cloned.Require = &clonedValue0
	}
	if v.Arguments == nil {
		cloned.Arguments = nil
	} else {
		cloned.Arguments = make([]SkeletonField, len(v.Arguments))
		for index1 := range v.Arguments {
			cloned.Arguments[index1] = v.Arguments[index1].Clone()
		}
	}
	return cloned
}

// SkeletonPermCheck Skeleton permission verification call
type SkeletonPermCheck struct {
	// ResourceSkelName Resource Skel name
	ResourceSkelName string `json:"resourceSkelName"`
	// ActionName Action name
	ActionName string `json:"actionName"`
	// CheckName Check name
	CheckName string `json:"checkName"`
	// ServiceSkelName Check Service Skel name
	ServiceSkelName string `json:"serviceSkelName"`
	// MethodSkelName Check Method Skel name
	MethodSkelName string `json:"methodSkelName"`
	// Arguments Parameter list
	Arguments []SkeletonPermCheckArgument `json:"arguments"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonPermCheck) Clone() SkeletonPermCheck {
	cloned := v
	if v.Arguments == nil {
		cloned.Arguments = nil
	} else {
		cloned.Arguments = make([]SkeletonPermCheckArgument, len(v.Arguments))
		for index0 := range v.Arguments {
			cloned.Arguments[index0] = v.Arguments[index0].Clone()
		}
	}
	return cloned
}

// SkeletonPermCheckArgument Skeleton permission verification parameters
type SkeletonPermCheckArgument struct {
	// Name Parameter name
	Name string `json:"name"`
	// JsonPath Parameter JSON path
	JsonPath string `json:"jsonPath"`
	// Type Parameter type
	Type string `json:"type"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonPermCheckArgument) Clone() SkeletonPermCheckArgument {
	cloned := v
	return cloned
}

// SkeletonPermExpr Skeleton permission expression
type SkeletonPermExpr struct {
	// Mode Permission expression pattern
	Mode string `json:"mode"`
	// Code Permission code
	Code string `json:"code"`
	// Check Permission verification call
	Check *SkeletonPermCheck `json:"check"`
	// Children Subexpression
	Children []SkeletonPermExpr `json:"children"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonPermExpr) Clone() SkeletonPermExpr {
	cloned := v
	if v.Check != nil {
		clonedValue0 := *v.Check
		clonedValue0 = (*v.Check).Clone()
		cloned.Check = &clonedValue0
	}
	if v.Children == nil {
		cloned.Children = nil
	} else {
		cloned.Children = make([]SkeletonPermExpr, len(v.Children))
		for index1 := range v.Children {
			cloned.Children[index1] = v.Children[index1].Clone()
		}
	}
	return cloned
}

// SkeletonResourceAction SkeletonResource Action
type SkeletonResourceAction struct {
	// Name Action name
	Name string `json:"name"`
	// PermissionCode Permission code
	PermissionCode string `json:"permissionCode"`
	// Description Action description
	Description string `json:"description"`
	// Deprecated Whether the Action is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Action deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Checks Check list
	Checks []SkeletonResourceCheck `json:"checks"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonResourceAction) Clone() SkeletonResourceAction {
	cloned := v
	if v.Checks == nil {
		cloned.Checks = nil
	} else {
		cloned.Checks = make([]SkeletonResourceCheck, len(v.Checks))
		for index0 := range v.Checks {
			cloned.Checks[index0] = v.Checks[index0].Clone()
		}
	}
	return cloned
}

// SkeletonResourceCheck SkeletonResource Check
type SkeletonResourceCheck struct {
	// Name Check name
	Name string `json:"name"`
	// Deprecated Whether the Check is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Check deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// MethodName Check method name
	MethodName string `json:"methodName"`
	// MethodSkelName Check method Skel name
	MethodSkelName string `json:"methodSkelName"`
	// Arguments Parameter list
	Arguments []SkeletonField `json:"arguments"`
	// ArgumentsSensitive Whether all input arguments are sensitive
	ArgumentsSensitive bool `json:"argumentsSensitive"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonResourceCheck) Clone() SkeletonResourceCheck {
	cloned := v
	if v.Arguments == nil {
		cloned.Arguments = nil
	} else {
		cloned.Arguments = make([]SkeletonField, len(v.Arguments))
		for index0 := range v.Arguments {
			cloned.Arguments[index0] = v.Arguments[index0].Clone()
		}
	}
	return cloned
}

// SkeletonResourceItem Skeleton Resource item
type SkeletonResourceItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Resource name
	Name string `json:"name"`
	// SkelName Resource Skel name
	SkelName string `json:"skelName"`
	// Description Resource description
	Description string `json:"description"`
	// Deprecated Whether the Resource is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Resource deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Checks Resource level Check list
	Checks []SkeletonResourceCheck `json:"checks"`
	// Actions Action list
	Actions []SkeletonResourceAction `json:"actions"`
	// CheckService Check service
	CheckService *SkeletonServiceItem `json:"checkService"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonResourceItem) Clone() SkeletonResourceItem {
	cloned := v
	if v.Checks == nil {
		cloned.Checks = nil
	} else {
		cloned.Checks = make([]SkeletonResourceCheck, len(v.Checks))
		for index0 := range v.Checks {
			cloned.Checks[index0] = v.Checks[index0].Clone()
		}
	}
	if v.Actions == nil {
		cloned.Actions = nil
	} else {
		cloned.Actions = make([]SkeletonResourceAction, len(v.Actions))
		for index1 := range v.Actions {
			cloned.Actions[index1] = v.Actions[index1].Clone()
		}
	}
	if v.CheckService != nil {
		clonedValue2 := *v.CheckService
		clonedValue2 = (*v.CheckService).Clone()
		cloned.CheckService = &clonedValue2
	}
	return cloned
}

// SkeletonServiceItem Skeleton service items
type SkeletonServiceItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Service name
	Name string `json:"name"`
	// SkelName Service Skel name
	SkelName string `json:"skelName"`
	// Description Service Description
	Description string `json:"description"`
	// Deprecated Whether the Service is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Service deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Pub Whether the item is public
	Pub bool `json:"pub"`
	Api bool `json:"api"`
	// AuthMode Authentication mode
	AuthMode string `json:"authMode"`
	// Require Permission requirements
	Require *SkeletonPermExpr `json:"require"`
	// Actors Accessible Actor List
	Actors []SkeletonActorRef `json:"actors"`
	// Methods Method list
	Methods []SkeletonMethod `json:"methods"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonServiceItem) Clone() SkeletonServiceItem {
	cloned := v
	if v.Require != nil {
		clonedValue0 := *v.Require
		clonedValue0 = (*v.Require).Clone()
		cloned.Require = &clonedValue0
	}
	if v.Actors == nil {
		cloned.Actors = nil
	} else {
		cloned.Actors = make([]SkeletonActorRef, len(v.Actors))
		for index1 := range v.Actors {
			cloned.Actors[index1] = v.Actors[index1].Clone()
		}
	}
	if v.Methods == nil {
		cloned.Methods = nil
	} else {
		cloned.Methods = make([]SkeletonMethod, len(v.Methods))
		for index2 := range v.Methods {
			cloned.Methods[index2] = v.Methods[index2].Clone()
		}
	}
	return cloned
}

// SkeletonTask Skeleton task
type SkeletonTask struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Task name
	Name string `json:"name"`
	// SkelName Task Skel name
	SkelName string `json:"skelName"`
	// Description Task description
	Description string `json:"description"`
	// Deprecated Whether the Task is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Task deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Triggers Trigger list
	Triggers []SkeletonTrigger `json:"triggers"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonTask) Clone() SkeletonTask {
	cloned := v
	if v.Triggers == nil {
		cloned.Triggers = nil
	} else {
		cloned.Triggers = make([]SkeletonTrigger, len(v.Triggers))
		for index0 := range v.Triggers {
			cloned.Triggers[index0] = v.Triggers[index0].Clone()
		}
	}
	return cloned
}

// SkeletonTrigger Skeleton task trigger
type SkeletonTrigger struct {
	// Name Trigger name
	Name string `json:"name"`
	// SkelName Trigger Skel name
	SkelName string `json:"skelName"`
	// Description Trigger description
	Description string `json:"description"`
	// Deprecated Whether the Trigger is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Trigger deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// InputDescription Input description
	InputDescription string `json:"inputDescription"`
	// Example Input example
	Example string `json:"example"`
	// Arguments Parameter list
	Arguments []SkeletonField `json:"arguments"`
	// ArgumentsSensitive Whether all input arguments are sensitive
	ArgumentsSensitive bool `json:"argumentsSensitive"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonTrigger) Clone() SkeletonTrigger {
	cloned := v
	if v.Arguments == nil {
		cloned.Arguments = nil
	} else {
		cloned.Arguments = make([]SkeletonField, len(v.Arguments))
		for index0 := range v.Arguments {
			cloned.Arguments[index0] = v.Arguments[index0].Clone()
		}
	}
	return cloned
}

// SkeletonWebItem Skeleton web page
type SkeletonWebItem struct {
	// Domain Domain
	Domain string `json:"domain"`
	// SchemaHash Skeleton item hash
	SchemaHash string `json:"schemaHash"`
	// MainSchemaHash Primary skeleton item hash
	MainSchemaHash string `json:"mainSchemaHash"`
	// IsMultiVersion Whether there are multiple valid versions of the skeleton item
	IsMultiVersion bool `json:"isMultiVersion"`
	// IsMain Whether it is the main version of the skeleton item
	IsMain bool `json:"isMain"`
	// DomainSchemaHash Owning DomainSchema hash
	DomainSchemaHash string `json:"domainSchemaHash"`
	// Name Web page name
	Name string `json:"name"`
	// SkelName Web Skel name
	SkelName string `json:"skelName"`
	// Description Web page description
	Description string `json:"description"`
	// Deprecated Whether the Web is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Web deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// Actors Accessible Actor List
	Actors []SkeletonActorRef `json:"actors"`
}

// Clone returns a value-isolated copy of the generated data.
func (v SkeletonWebItem) Clone() SkeletonWebItem {
	cloned := v
	if v.Actors == nil {
		cloned.Actors = nil
	} else {
		cloned.Actors = make([]SkeletonActorRef, len(v.Actors))
		for index0 := range v.Actors {
			cloned.Actors[index0] = v.Actors[index0].Clone()
		}
	}
	return cloned
}

// TaskDebugDefaultLaunchRequest Task Debug initiates a request by default
type TaskDebugDefaultLaunchRequest struct {
	// TraceId Trace ID
	TraceId string `json:"traceId"`
	// SpanId Span ID
	SpanId string `json:"spanId"`
	// ArgumentsJson Default task parameters JSON
	ArgumentsJson skel.JSON `json:"argumentsJson"`
}

// Clone returns a value-isolated copy of the generated data.
func (v TaskDebugDefaultLaunchRequest) Clone() TaskDebugDefaultLaunchRequest {
	cloned := v
	return cloned
}

// TaskDebugLaunchRequest Task Debug initiates a request
type TaskDebugLaunchRequest struct {
	// TaskSkelName Task Skel name
	TaskSkelName string `json:"taskSkelName"`
	// SchemaHash Task schema hash
	SchemaHash string `json:"schemaHash"`
	// TriggerSkelName Trigger Skel name
	TriggerSkelName string `json:"triggerSkelName"`
	// ArgumentsJson Task parameters JSON
	ArgumentsJson skel.JSON `json:"argumentsJson"`
	// TraceId Trace ID
	TraceId *string `json:"traceId"`
	// SpanId Span ID
	SpanId *string `json:"spanId"`
}

// Clone returns a value-isolated copy of the generated data.
func (v TaskDebugLaunchRequest) Clone() TaskDebugLaunchRequest {
	cloned := v
	if v.TraceId != nil {
		clonedValue0 := *v.TraceId
		cloned.TraceId = &clonedValue0
	}
	if v.SpanId != nil {
		clonedValue1 := *v.SpanId
		cloned.SpanId = &clonedValue1
	}
	return cloned
}

// TaskDebugTaskItem Task called by Task Debug
type TaskDebugTaskItem struct {
	// Name Task name
	Name string `json:"name"`
	// TaskSkelName Task Skel name
	TaskSkelName string `json:"taskSkelName"`
	// SchemaHash Task schema hash
	SchemaHash string `json:"schemaHash"`
	// Description Task description
	Description string `json:"description"`
	// Deprecated Whether the Task is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Task deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
}

// Clone returns a value-isolated copy of the generated data.
func (v TaskDebugTaskItem) Clone() TaskDebugTaskItem {
	cloned := v
	return cloned
}

// TaskDebugTriggerItem Trigger called by Task Debug
type TaskDebugTriggerItem struct {
	// Name Trigger name
	Name string `json:"name"`
	// SkelName Trigger Skel name
	SkelName string `json:"skelName"`
	// Description Trigger description
	Description string `json:"description"`
	// Deprecated Whether the Trigger is deprecated
	Deprecated bool `json:"deprecated"`
	// DeprecatedReason Trigger deprecation reason
	DeprecatedReason string `json:"deprecatedReason"`
	// InputDescription Input description
	InputDescription string `json:"inputDescription"`
	// Example Input example
	Example string `json:"example"`
	// Arguments Parameter list
	Arguments []SkeletonField `json:"arguments"`
}

// Clone returns a value-isolated copy of the generated data.
func (v TaskDebugTriggerItem) Clone() TaskDebugTriggerItem {
	cloned := v
	if v.Arguments == nil {
		cloned.Arguments = nil
	} else {
		cloned.Arguments = make([]SkeletonField, len(v.Arguments))
		for index0 := range v.Arguments {
			cloned.Arguments[index0] = v.Arguments[index0].Clone()
		}
	}
	return cloned
}

// TaskRunnerCronScheduler Task execution Cron schedule
type TaskRunnerCronScheduler struct {
	// TriggerSkelName Trigger Skel name
	TriggerSkelName string `json:"triggerSkelName"`
	// CronExpr Cron expression
	CronExpr string `json:"cronExpr"`
}

// Clone returns a value-isolated copy of the generated data.
func (v TaskRunnerCronScheduler) Clone() TaskRunnerCronScheduler {
	cloned := v
	return cloned
}

// TaskRunnerRegistration Task execution capability registration information provided by the application
type TaskRunnerRegistration struct {
	// TaskSkelName Task Skel name
	TaskSkelName string `json:"taskSkelName"`
	// SchemaHash Task schema hash
	SchemaHash string `json:"schemaHash"`
	// TimeoutMs Execution timeout, in milliseconds
	TimeoutMs int `json:"timeoutMs"`
	// Concurrency Maximum concurrency
	Concurrency int `json:"concurrency"`
	// NoRetry Whether to disallow retrying after failure
	NoRetry bool `json:"noRetry"`
	// CronSchedulers Cron schedule list
	CronSchedulers []TaskRunnerCronScheduler `json:"cronSchedulers"`
}

// Clone returns a value-isolated copy of the generated data.
func (v TaskRunnerRegistration) Clone() TaskRunnerRegistration {
	cloned := v
	if v.CronSchedulers == nil {
		cloned.CronSchedulers = nil
	} else {
		cloned.CronSchedulers = make([]TaskRunnerCronScheduler, len(v.CronSchedulers))
		for index0 := range v.CronSchedulers {
			cloned.CronSchedulers[index0] = v.CronSchedulers[index0].Clone()
		}
	}
	return cloned
}

// WebHandlerRegistration Web processing capability registration information provided by the application
type WebHandlerRegistration struct {
	// WebSkelName Web Skel name
	WebSkelName string `json:"webSkelName"`
	// SchemaHash Web schema hash
	SchemaHash string `json:"schemaHash"`
	// Endpoint Web proxy access address
	Endpoint string `json:"endpoint"`
}

// Clone returns a value-isolated copy of the generated data.
func (v WebHandlerRegistration) Clone() WebHandlerRegistration {
	cloned := v
	return cloned
}
