// Code generated by skelc. DO NOT EDIT.

package admin

import (
	"reflect"

	web "go.yorun.ai/vine/internal/core/web/spec"
)

func init() {
	web.Register(_DashboardWebSpec)
}

var _DashboardWebSpec = &web.WebSpec{
	Name:              "DashboardWeb",
	SkelName:          "vine.hub.admin.DashboardWeb",
	Hash:              "c10f559e",
	ServerType:        reflect.TypeFor[DashboardWebServer](),
	DefaultServerType: reflect.TypeFor[*DefaultDashboardWebServer](),
}

// DashboardWebServer Hub Dashboard Web
type DashboardWebServer interface {
	web.Handler

	mustBeDashboardWebServer()
}

type DefaultDashboardWebServer struct {
}

func (*DefaultDashboardWebServer) Routes(*web.Router) {
	panic("method routes is not implemented")
}

func (*DefaultDashboardWebServer) mustBeDashboardWebServer() {}
