// Code generated by skelc. DO NOT EDIT.

/** Portal site CORS mode. */
export type PortalCorsMode =
  | "UNSPECIFIED"
  /** Disable CORS. */
  | "DISABLED"
  /** Allow origins in the same domain as the entry rule. */
  | "SAME_DOMAIN"
  /** Only allow Origins in the configuration list. */
  | "STRICT"
;
/** Portal target site type. */
export type PortalSiteType =
  | "UNSPECIFIED"
  /** Rpc gateway. */
  | "RPCGW"
  /** Web gateway. */
  | "WEBGW"
;
/** Configuration creation parameters. */
export type AppConfigCreation = {
  /** Configuration Skel name. */
  skelName: string;
  /** Configuration JSON. */
  value:    string;
}
/** Configuration items. */
export type AppConfigItem = {
  /** Configuration ID. */
  id:           number;
  /** Configuration key. */
  key:          string;
  /** Configuration status. */
  status:       string;
  /** Configuration lifecycle. */
  lifecycle:    string;
  /** Configuration JSON. */
  value:        string;
  /** Configuration schema. */
  schema:       AppConfigSchema | null;
  /** Field sources; only returned by get, create and update. */
  fieldSources: Array<FieldSource>;
}
/** Configuration item list item. */
export type AppConfigListItem = {
  /** Configuration ID. */
  id:             number;
  /** Configuration key. */
  key:            string;
  /** Configuration status. */
  status:         string;
  /** Configuration lifecycle. */
  lifecycle:      string;
  /** Configuration schema name; empty when no schema matches. */
  schemaName:     string;
  /** Configuration schema Skel name; empty when no schema matches. */
  schemaSkelName: string;
}
/** Configuration schema items. */
export type AppConfigSchema = {
  /** Configuration Skel name. */
  skelName:         string;
  /** Configuration name. */
  name:             string;
  /** Configuration description. */
  description:      string;
  /** Whether the configuration is deprecated. */
  deprecated:       boolean;
  /** Configuration deprecation reason. */
  deprecatedReason: string;
  /** Configuration lifecycle. */
  lifecycle:        string;
  /** Configuration field list. */
  fields:           Array<AppConfigSchemaField>;
}
/** Configuration schema enumeration options. */
export type AppConfigSchemaEnumItem = {
  /** Enum option name. */
  name:             string;
  /** Enumeration options description. */
  description:      string;
  /** Whether the enumeration option is deprecated. */
  deprecated:       boolean;
  /** Enumeration option deprecation reason. */
  deprecatedReason: string;
}
/** Configuration schema fields. */
export type AppConfigSchemaField = {
  /** Field name. */
  name:              string;
  /** Field type. */
  type:              string;
  /** Field description. */
  description:       string;
  /** Whether the field is deprecated. */
  deprecated:        boolean;
  /** Field deprecation reason. */
  deprecatedReason:  string;
  /** Enumeration options list. */
  enumItems:         Array<AppConfigSchemaEnumItem>;
  /** Map key enumeration options. */
  mapKeyEnumItems:   Array<AppConfigSchemaEnumItem>;
  /** Map value enumeration options. */
  mapValueEnumItems: Array<AppConfigSchemaEnumItem>;
}
/** Configuration update parameters. */
export type AppConfigUpdate = {
  /** Configuration JSON. */
  value: string | null;
}
/** Application instance status view for Dashboard display. */
export type AppStatusView = {
  /** Application name. */
  name:            string;
  /** Application instance ID. */
  instanceId:      string;
  /** Application version. */
  version:         string;
  /** Application access address. */
  endpoint:        string;
  /** List of Rpc service processing capabilities provided by the application. */
  serviceHandlers: Array<ServiceHandlerRegistration>;
  /** List of web processing capabilities provided by the application. */
  webHandlers:     Array<WebHandlerRegistration>;
  /** List of event listening capabilities provided by the application. */
  eventListeners:  Array<EventListenerRegistration>;
  /** List of task execution capabilities provided by the application. */
  taskRunners:     Array<TaskRunnerRegistration>;
}
/** Default Event Debug send request. */
export type EventDebugDefaultEmitRequest = {
  /** Trace ID. */
  traceId:   string;
  /** Span ID. */
  spanId:    string;
  /** Default event JSON. */
  eventJson: string;
}
/** Event Debug send request. */
export type EventDebugEmitRequest = {
  /** Event Skel name. */
  eventSkelName: string;
  /** Event schema hash. */
  schemaHash:    string;
  /** Event JSON. */
  eventJson:     string;
  /** Trace ID. */
  traceId:       string | null;
  /** Span ID. */
  spanId:        string | null;
}
/** Event called by Event Debug. */
export type EventDebugEventItem = {
  /** Event name. */
  name:             string;
  /** Event Skel name. */
  eventSkelName:    string;
  /** Event schema hash. */
  schemaHash:       string;
  /** Event description. */
  description:      string;
  /** Whether the Event is deprecated. */
  deprecated:       boolean;
  /** Event deprecation reason. */
  deprecatedReason: string;
  /** Field list. */
  fields:           Array<SkeletonField>;
}
/** Event listening capability registration information provided by the application. */
export type EventListenerRegistration = {
  /** Event Skel name. */
  eventSkelName: string;
  /** Event schema hash. */
  schemaHash:    string;
  /** Execution timeout, in milliseconds. */
  timeoutMs:     number;
  /** Maximum concurrency. */
  concurrency:   number;
  /** Whether to disallow retrying after failure. */
  noRetry:       boolean;
}
/** Layers that supplied an entity field. */
export type FieldSource = {
  /** Field JSON pointer. */
  path:      string;
  /** Seed source. */
  source:    string;
  /** Seed definition name. */
  define:    string;
  /** Seed override name. */
  override:  string;
  /** Referenced seed variables. */
  variables: Array<string>;
  /** Seed template. */
  template:  string | null;
  /** Resolved variable bindings. */
  bindings:  Array<FieldSourceBinding>;
}
/** A resolved variable reference within a field template. */
export type FieldSourceBinding = {
  /** Template JSON pointer. */
  path:        string;
  /** Variable name. */
  variable:    string;
  /** Variable reference. */
  reference:   string;
  /** Resolved value. */
  value:       string;
  /** Whether the default was used. */
  defaultUsed: boolean;
}
/** JetStream consumer snapshot; unacknowledged messages are not necessarily executing. */
export type MessageQueueConsumer = {
  name:           string;
  filterSubjects: Array<string>;
  /** Undelivered message count as a decimal string. */
  pending:        string;
  ackPending:     number;
  /** Distinct redelivered messages still unacknowledged, not cumulative retries. */
  redelivered:    number;
  /** Outstanding pull requests, not waiting messages. */
  waiting:        number;
}
/** Task or Event stream snapshot. */
export type MessageQueueStatusView = {
  kind:      string;
  stream:    string;
  exists:    boolean;
  /** Stored message count as a decimal string. */
  messages:  string;
  /** Stored bytes as a decimal string. */
  bytes:     string;
  subjects:  Array<MessageQueueSubject>;
  consumers: Array<MessageQueueConsumer>;
}
/** Stored messages for a subject, including subjects without consumers. */
export type MessageQueueSubject = {
  subject:  string;
  /** Message count as a decimal string. */
  messages: string;
}
/** Portal site certificate. */
export type PortalCert = {
  /** Certificate ID. */
  id:                   number;
  /** Certificate name. */
  name:                 string;
  /** Certificate issuer. */
  issuer:               string;
  /** Certificate domain name. */
  domains:              Array<string>;
  /** Certificate Base64. */
  publicKeyBase64:      string;
  /** Whether the private key has been configured. */
  privateKeyConfigured: boolean;
  /** Validity start time. */
  validFrom:            string;
  /** Validity end time. */
  validTo:              string;
  /** Field sources; only returned by get, create and update. */
  fieldSources:         Array<FieldSource>;
  /** Whether Hub publishes this certificate to Portal. */
  enabled:              boolean;
}
/** Portal site certificate creation parameters. */
export type PortalCertCreation = {
  /** Certificate name. */
  name:             string;
  /** Certificate Base64. */
  publicKeyBase64:  string;
  /** Private key Base64. */
  privateKeyBase64: string;
  /** Whether Hub publishes this certificate to Portal. */
  enabled:          boolean | null;
}
/** Portal site certificate list item. */
export type PortalCertListItem = {
  /** Certificate ID. */
  id:                   number;
  /** Certificate name. */
  name:                 string;
  /** Certificate issuer. */
  issuer:               string;
  /** Certificate domain name. */
  domains:              Array<string>;
  /** Certificate Base64. */
  publicKeyBase64:      string;
  /** Whether the private key has been configured. */
  privateKeyConfigured: boolean;
  /** Validity start time. */
  validFrom:            string;
  /** Validity end time. */
  validTo:              string;
  /** Whether Hub publishes this certificate to Portal. */
  enabled:              boolean;
}
/** Portal site certificate update parameters. */
export type PortalCertUpdate = {
  /** Certificate name. */
  name:             string | null;
  /** Certificate Base64. */
  publicKeyBase64:  string | null;
  /** Private key Base64. */
  privateKeyBase64: string | null;
  /** Whether Hub publishes this certificate to Portal. */
  enabled:          boolean | null;
}
/** Portal site CORS configuration. */
export type PortalCors = {
  /** CORS mode: DISABLED/SAME_DOMAIN/STRICT. */
  mode:           PortalCorsMode;
  /** List of origins allowed in strict mode. */
  allowedOrigins: Array<string>;
}
/** Portal access entry. */
export type PortalEntry = {
  /** Entry ID. */
  id:      number;
  /** Entry name. */
  name:    string;
  /** Entry protocol. */
  scheme:  string;
  /** Match Host, empty string means no restriction. */
  host:    string;
  /** Entry port. */
  port:    number;
  /** Entry rule list. */
  rules:   Array<PortalEntryRule>;
  /** Whether Hub publishes the rules of this entry to Portal. */
  enabled: boolean;
}
/** Portal access entry creation parameters. */
export type PortalEntryCreation = {
  /** Entry name. */
  name:    string;
  /** Entry protocol. */
  scheme:  string;
  /** Match Host, empty string means no restriction. */
  host:    string;
  /** Entry port. */
  port:    number;
  /** Whether Hub publishes the rules of this entry to Portal; defaults to true. */
  enabled: boolean | null;
}
/** Portal access entry rules. */
export type PortalEntryRule = {
  /** Entry rules. */
  rule: PortalRuleListItem;
  /** Target site. */
  site: PortalSiteListItem | null;
}
/** Portal access entry update parameters. */
export type PortalEntryUpdate = {
  /** Entry name. */
  name:    string | null;
  /** Entry protocol. */
  scheme:  string | null;
  /** Match Host, empty string means no restriction. */
  host:    string | null;
  /** Entry port. */
  port:    number | null;
  /** Whether Hub publishes the rules of this entry to Portal. */
  enabled: boolean | null;
}
/** Portal entry rules. */
export type PortalRule = {
  /** Rule ID. */
  id:                      number;
  /** Rule name. */
  name:                    string;
  /** Matching protocol. */
  matchScheme:             string;
  /** Match Host, empty string means no restriction. */
  matchHost:               string;
  /** Match matchPort, 0 means no restriction. */
  matchPort:               number;
  /** Match path prefix, empty string means match all paths. */
  matchPathPrefix:         string;
  /** Target type. */
  routeType:               string;
  /** Site name. */
  routeSiteName:           string;
  /** Redirect Pattern. */
  routeRedirectionPattern: string;
  /** Target site path prefix; empty means strip the matching prefix only. */
  routePathPrefix:         string;
  /** Effective match path prefix after site mount path resolution. */
  resolvedMatchPathPrefix: string;
  /** Effective route path prefix after site mount path resolution. */
  resolvedRoutePathPrefix: string;
  /** Field sources; only returned by get, create and update. */
  fieldSources:            Array<FieldSource>;
  /** Whether Hub publishes this rule to Portal. */
  enabled:                 boolean;
}
/** Portal entry rules that match the same request. */
export type PortalRuleConflict = {
  /** Rule ID. */
  ruleId:           number;
  /** Rule name. */
  rule:             string;
  /** ID of the rule that already matches the request. */
  conflictRuleId:   number;
  /** Name of the rule that already matches the request. */
  conflictRule:     string;
  /** Name of the Portal entry the rules belong to. */
  entry:            string;
  /** Request both rules match. */
  match:            string;
  /** ID of the rule Hub publishes for the request. */
  publishedRuleId:  number;
  /** Name of the rule Hub publishes for the request. */
  publishedRule:    string;
  /** ID of the rule Hub leaves out, because the published rule sorts first. */
  suppressedRuleId: number;
  /** Name of the rule Hub leaves out, because the published rule sorts first. */
  suppressedRule:   string;
}
/** Portal entry rule creation parameters. */
export type PortalRuleCreation = {
  /** Rule name. */
  name:                    string;
  /** Name of the Portal access entry the rule belongs to. */
  entryName:               string;
  /** Match path prefix, empty string means match all paths. */
  matchPathPrefix:         string;
  /** Target type. */
  routeType:               string;
  /** Site name. */
  routeSiteName:           string;
  /** Redirect Pattern. */
  routeRedirectionPattern: string;
  /** Target site path prefix; empty means strip the matching prefix only. */
  routePathPrefix:         string | null;
  /** Whether Hub publishes this rule to Portal. */
  enabled:                 boolean | null;
}
/** Portal entry rule list item. */
export type PortalRuleListItem = {
  /** Rule ID. */
  id:                      number;
  /** Rule name. */
  name:                    string;
  /** Matching protocol. */
  matchScheme:             string;
  /** Match Host, empty string means no restriction. */
  matchHost:               string;
  /** Match matchPort, 0 means no restriction. */
  matchPort:               number;
  /** Match path prefix, empty string means match all paths. */
  matchPathPrefix:         string;
  /** Target type. */
  routeType:               string;
  /** Site name. */
  routeSiteName:           string;
  /** Redirect Pattern. */
  routeRedirectionPattern: string;
  /** Target site path prefix; empty means strip the matching prefix only. */
  routePathPrefix:         string;
  /** Effective match path prefix after site mount path resolution. */
  resolvedMatchPathPrefix: string;
  /** Effective route path prefix after site mount path resolution. */
  resolvedRoutePathPrefix: string;
  /** Whether Hub publishes this rule to Portal. */
  enabled:                 boolean;
}
/** Portal entry rule update parameters. */
export type PortalRuleUpdate = {
  /** Rule name. */
  name:                    string | null;
  /** Match path prefix, empty string means match all paths. */
  matchPathPrefix:         string | null;
  /** Target type. */
  routeType:               string | null;
  /** Site name. */
  routeSiteName:           string | null;
  /** Redirect Pattern. */
  routeRedirectionPattern: string | null;
  /** Target site path prefix; empty means strip the matching prefix only. */
  routePathPrefix:         string | null;
  /** Whether Hub publishes this rule to Portal. */
  enabled:                 boolean | null;
}
/** Portal target site. */
export type PortalSite = {
  /** Target site id. */
  id:            number;
  /** Target site name. */
  name:          string;
  /** Target site type. */
  type:          PortalSiteType;
  /** Actor Skel name. */
  actorSkelName: string;
  /** Actor access method. */
  actorVia:      string;
  /** Rpc gateway service Skel name list. */
  rpcgwServices: Array<string>;
  /** CORS configuration. */
  cors:          PortalCors | null;
  /** Web name. */
  webName:       string;
  /** Web mount path; empty means the Web is not limited to a path. */
  webMountPath:  string;
  /** Field sources; only returned by get, create and update. */
  fieldSources:  Array<FieldSource>;
  /** Whether Hub publishes this site to Portal. */
  enabled:       boolean;
}
/** Portal target site Actor options. */
export type PortalSiteActorOption = {
  /** Actor name. */
  name:      string;
  /** Actor Skel name. */
  skelName:  string;
  /** Actor access method list. */
  actorVias: Array<string>;
}
/** Portal target site creation parameters. */
export type PortalSiteCreation = {
  /** Target site name. */
  name:          string;
  /** Target site type. */
  type:          PortalSiteType;
  /** Actor Skel name. */
  actorSkelName: string;
  /** Actor access method. */
  actorVia:      string;
  /** CORS configuration. */
  cors:          PortalCors | null;
  /** Web name. */
  webName:       string;
  /** Whether Hub publishes this site to Portal. */
  enabled:       boolean | null;
}
/** Portal target site list item. */
export type PortalSiteListItem = {
  /** Target site id. */
  id:            number;
  /** Target site name. */
  name:          string;
  /** Target site type. */
  type:          PortalSiteType;
  /** Actor Skel name. */
  actorSkelName: string;
  /** Actor access method. */
  actorVia:      string;
  /** Rpc gateway service Skel name list. */
  rpcgwServices: Array<string>;
  /** CORS configuration. */
  cors:          PortalCors | null;
  /** Web name. */
  webName:       string;
  /** Web mount path; empty means the Web is not limited to a path. */
  webMountPath:  string;
  /** Whether Hub publishes this site to Portal. */
  enabled:       boolean;
}
/** Portal target site form options. */
export type PortalSiteOptions = {
  /** Actor options. */
  actors:   Array<PortalSiteActorOption>;
  /** Rpc service options. */
  services: Array<PortalSiteServiceOption>;
  /** Web options. */
  webs:     Array<PortalSiteWebOption>;
}
/** Portal target site service options. */
export type PortalSiteServiceOption = {
  /** Service name. */
  name:           string;
  /** Service Skel name. */
  skelName:       string;
  /** Actor Skel name list. */
  actorSkelNames: Array<string>;
}
/** Portal target site update parameters. */
export type PortalSiteUpdate = {
  /** Target site name. */
  name:          string | null;
  /** Target site type. */
  type:          PortalSiteType | null;
  /** Actor Skel name. */
  actorSkelName: string | null;
  /** Actor access method. */
  actorVia:      string | null;
  /** CORS configuration. */
  cors:          PortalCors | null;
  /** Web name. */
  webName:       string | null;
  /** Whether Hub publishes this site to Portal. */
  enabled:       boolean | null;
}
/** Portal target site web options. */
export type PortalSiteWebOption = {
  /** Web name. */
  name:           string;
  /** Web Skel name. */
  skelName:       string;
  /** Actor Skel name list. */
  actorSkelNames: Array<string>;
}
/** Portal instance status view for Dashboard display. */
export type PortalStatusView = {
  /** Portal instance ID. */
  instanceId: string;
  /** Portal version. */
  version:    string;
}
/** Service Debug Actor options. */
export type ServiceDebugActorItem = {
  /** Actor name. */
  name:          string;
  /** Actor Skel name. */
  skelName:      string;
  /** Actor Info Skel name. */
  infoSkelName:  string;
  /** Default Actor Info JSON. */
  actorInfoJson: string;
}
/** Application instance called by Service Debug. */
export type ServiceDebugAppInstance = {
  /** Application name. */
  appName:       string;
  /** Application instance ID. */
  appInstanceId: string;
  /** Application version. */
  appVersion:    string;
  /** Application access address. */
  endpoint:      string;
}
/** Service Debug default call request. */
export type ServiceDebugDefaultInvokeRequest = {
  /** Trace ID. */
  traceId:       string;
  /** Span ID. */
  spanId:        string;
  /** Actor options. */
  actors:        Array<ServiceDebugActorItem>;
  /** Default Actor Skel name. */
  actorSkelName: string | null;
  /** Default Actor Info JSON. */
  actorInfoJson: string;
  /** Default request parameters JSON. */
  paramsJson:    string;
}
/** Service Debug call request. */
export type ServiceDebugInvokeRequest = {
  /** Application name. */
  appName:         string | null;
  /** Application instance ID. */
  appInstanceId:   string | null;
  /** Service Skel name. */
  serviceSkelName: string;
  /** Service schema hash. */
  schemaHash:      string;
  /** Method Skel name. */
  methodSkelName:  string;
  /** Request parameters JSON. */
  paramsJson:      string;
  /** Call timeout, in seconds. */
  timeoutSeconds:  number;
  /** Trace ID. */
  traceId:         string | null;
  /** Span ID. */
  spanId:          string | null;
  /** Actor Skel name. */
  actorSkelName:   string | null;
  /** Actor Info JSON. */
  actorInfoJson:   string;
}
/** Service Debug call response. */
export type ServiceDebugInvokeResponse = {
  /** HTTP status code. */
  httpStatus:  number;
  /** Rpc status code. */
  rpcStatus:   string;
  /** Response header JSON. */
  headersJson: string;
  /** Response body JSON. */
  bodyJson:    string;
}
/** Method called by Service Debug. */
export type ServiceDebugMethodItem = {
  /** Method name. */
  name:              string;
  /** Method Skel name. */
  skelName:          string;
  /** Method description. */
  description:       string;
  /** Whether the method is deprecated. */
  deprecated:        boolean;
  /** Method deprecation reason. */
  deprecatedReason:  string;
  /** Input description. */
  inputDescription:  string;
  /** Output description. */
  outputDescription: string;
  /** Input example. */
  example:           string;
  /** Output example. */
  outputExample:     string;
  /** Parameter list. */
  arguments:         Array<SkeletonField>;
  /** Return type. */
  resultType:        string;
}
/** Service called by Service Debug. */
export type ServiceDebugServiceItem = {
  /** Service Skel name. */
  serviceSkelName:  string;
  /** Service schema hash. */
  schemaHash:       string;
  api:              boolean;
  /** Whether the Service is deprecated. */
  deprecated:       boolean;
  /** Service deprecation reason. */
  deprecatedReason: string;
}
/** Rpc service processing capability registration information provided by the application. */
export type ServiceHandlerRegistration = {
  /** Service Skel name. */
  serviceSkelName: string;
  /** Service schema hash. */
  schemaHash:      string;
  /** Service agent access address. */
  endpoint:        string;
}
/** SkeletonActor. */
export type SkeletonActorItem = {
  /** Domain. */
  domain:           string;
  /** Skeleton item hash. */
  schemaHash:       string;
  /** Primary skeleton item hash. */
  mainSchemaHash:   string;
  /** Whether there are multiple valid versions of the skeleton item. */
  isMultiVersion:   boolean;
  /** Whether it is the main version of the skeleton item. */
  isMain:           boolean;
  /** Owning DomainSchema hash. */
  domainSchemaHash: string;
  /** Actor name. */
  name:             string;
  /** Actor Skel name. */
  skelName:         string;
  /** Actor description. */
  description:      string;
  /** Whether the Actor is deprecated. */
  deprecated:       boolean;
  /** Actor deprecation reason. */
  deprecatedReason: string;
  /** Actor access method list. */
  actorVias:        Array<string>;
  /** Whether to enable authentication. */
  authEnabled:      boolean;
  /** Actor identifier field in Info. */
  identifierField:  string;
  /** Authentication credentials. */
  credential:       SkeletonData | null;
  /** Authentication information. */
  info:             SkeletonData | null;
  /** Authentication services. */
  authService:      SkeletonServiceItem | null;
  /** Whether to enable permissions. */
  permEnabled:      boolean;
  /** Permission service. */
  permService:      SkeletonServiceItem | null;
  /** Permission method. */
  permMethod:       SkeletonMethod | null;
  /** Accessible Service List. */
  services:         Array<SkeletonServiceItem>;
  /** Accessible web list. */
  webs:             Array<SkeletonWebItem>;
}
/** Skeleton Actor Reference. */
export type SkeletonActorRef = {
  /** Actor name. */
  name:     string;
  /** Actor Skel name. */
  skelName: string;
  /** Access method. */
  via:      string;
}
/** SkeletonConfig. */
export type SkeletonConfigItem = {
  /** Domain. */
  domain:           string;
  /** Skeleton item hash. */
  schemaHash:       string;
  /** Primary skeleton item hash. */
  mainSchemaHash:   string;
  /** Whether there are multiple valid versions of the skeleton item. */
  isMultiVersion:   boolean;
  /** Whether it is the main version of the skeleton item. */
  isMain:           boolean;
  /** Owning DomainSchema hash. */
  domainSchemaHash: string;
  /** Config name. */
  name:             string;
  /** Config Skel name. */
  skelName:         string;
  /** Config description. */
  description:      string;
  /** Whether the Config is deprecated. */
  deprecated:       boolean;
  /** Config deprecation reason. */
  deprecatedReason: string;
  /** Whether the item is public. */
  pub:              boolean;
  /** Whether the config value is sensitive. */
  sensitive:        boolean;
  /** Config lifecycle. */
  lifecycle:        string;
  /** Field list. */
  fields:           Array<SkeletonField>;
}
/** SkeletonData. */
export type SkeletonData = {
  /** Domain. */
  domain:           string;
  /** Skeleton item hash. */
  schemaHash:       string;
  /** Primary skeleton item hash. */
  mainSchemaHash:   string;
  /** Whether there are multiple valid versions of the skeleton item. */
  isMultiVersion:   boolean;
  /** Whether it is the main version of the skeleton item. */
  isMain:           boolean;
  /** Owning DomainSchema hash. */
  domainSchemaHash: string;
  /** Data name. */
  name:             string;
  /** Data Skel name. */
  skelName:         string;
  /** Data description. */
  description:      string;
  /** Whether the Data or Enum is deprecated. */
  deprecated:       boolean;
  /** Data or Enum deprecation reason. */
  deprecatedReason: string;
  /** Whether it is Enum. */
  enum:             boolean;
  /** Whether the data is sensitive. */
  sensitive:        boolean;
  /** Type parameter list. */
  typeParameters:   Array<string>;
  /** Field list. */
  fields:           Array<SkeletonField>;
  /** List of enumeration items. */
  enumItems:        Array<SkeletonEnumItem>;
}
/** Domain skeleton version. */
export type SkeletonDomain = {
  /** Domain name. */
  domain:         string;
  /** DomainSchema hash. */
  schemaHash:     string;
  /** Primary DomainSchema hash. */
  mainSchemaHash: string;
  /** Whether multiple active versions exist. */
  isMultiVersion: boolean;
  /** Whether this is the primary version. */
  isMain:         boolean;
  /** Total number of skeleton items. */
  total:          number;
  /** Actor list. */
  actors:         Array<SkeletonActorItem>;
  /** Service list. */
  services:       Array<SkeletonServiceItem>;
  /** Resource list. */
  resources:      Array<SkeletonResourceItem>;
  /** Data list. */
  data:           Array<SkeletonData>;
  /** Config list. */
  configs:        Array<SkeletonConfigItem>;
  /** Web list. */
  webs:           Array<SkeletonWebItem>;
  /** Task list. */
  tasks:          Array<SkeletonTask>;
  /** Event list. */
  events:         Array<SkeletonEventItem>;
}
/** Skeleton enumeration items. */
export type SkeletonEnumItem = {
  /** Enumeration item name. */
  name:             string;
  /** Enumeration item description. */
  description:      string;
  /** Whether the enumeration item is deprecated. */
  deprecated:       boolean;
  /** Enumeration item deprecation reason. */
  deprecatedReason: string;
}
/** Skeleton event. */
export type SkeletonEventItem = {
  /** Domain. */
  domain:           string;
  /** Skeleton item hash. */
  schemaHash:       string;
  /** Primary skeleton item hash. */
  mainSchemaHash:   string;
  /** Whether there are multiple valid versions of the skeleton item. */
  isMultiVersion:   boolean;
  /** Whether it is the main version of the skeleton item. */
  isMain:           boolean;
  /** Owning DomainSchema hash. */
  domainSchemaHash: string;
  /** Event name. */
  name:             string;
  /** Event Skel name. */
  skelName:         string;
  /** Event description. */
  description:      string;
  /** Whether the Event is deprecated. */
  deprecated:       boolean;
  /** Event deprecation reason. */
  deprecatedReason: string;
  /** Whether the item is public. */
  pub:              boolean;
  /** Whether the event payload is sensitive. */
  sensitive:        boolean;
  /** Field list. */
  fields:           Array<SkeletonField>;
}
/** Skeleton field. */
export type SkeletonField = {
  /** Field name. */
  name:             string;
  /** Field type. */
  type:             string;
  /** Field description. */
  description:      string;
  /** Whether the field is deprecated. */
  deprecated:       boolean;
  /** Field deprecation reason. */
  deprecatedReason: string;
  /** Field example. */
  example:          string;
  /** Whether the field is sensitive. */
  sensitive:        boolean;
}
/** Skeleton method. */
export type SkeletonMethod = {
  /** Method name. */
  name:               string;
  /** Method Skel name. */
  skelName:           string;
  /** Method description. */
  description:        string;
  /** Whether the method is deprecated. */
  deprecated:         boolean;
  /** Method deprecation reason. */
  deprecatedReason:   string;
  /** Input description. */
  inputDescription:   string;
  /** Output description. */
  outputDescription:  string;
  /** Input example. */
  example:            string;
  /** Authentication mode. */
  authMode:           string;
  /** Permission requirements. */
  require:            SkeletonPermExpr | null;
  /** Output example. */
  outputExample:      string;
  /** Parameter list. */
  arguments:          Array<SkeletonField>;
  /** Whether all input arguments are sensitive. */
  argumentsSensitive: boolean;
  /** Return type. */
  resultType:         string;
  /** Whether the result is sensitive. */
  resultSensitive:    boolean;
}
/** Skeleton permission verification call. */
export type SkeletonPermCheck = {
  /** Resource Skel name. */
  resourceSkelName: string;
  /** Action name. */
  actionName:       string;
  /** Check name. */
  checkName:        string;
  /** Check Service Skel name. */
  serviceSkelName:  string;
  /** Check Method Skel name. */
  methodSkelName:   string;
  /** Parameter list. */
  arguments:        Array<SkeletonPermCheckArgument>;
}
/** Skeleton permission verification parameters. */
export type SkeletonPermCheckArgument = {
  /** Parameter name. */
  name:     string;
  /** Parameter JSON path. */
  jsonPath: string;
  /** Parameter type. */
  type:     string;
}
/** Skeleton permission expression. */
export type SkeletonPermExpr = {
  /** Permission expression pattern. */
  mode:     string;
  /** Permission code. */
  code:     string;
  /** Permission verification call. */
  check:    SkeletonPermCheck | null;
  /** Subexpression. */
  children: Array<SkeletonPermExpr>;
}
/** SkeletonResource Action. */
export type SkeletonResourceAction = {
  /** Action name. */
  name:             string;
  /** Permission code. */
  permissionCode:   string;
  /** Action description. */
  description:      string;
  /** Whether the Action is deprecated. */
  deprecated:       boolean;
  /** Action deprecation reason. */
  deprecatedReason: string;
  /** Check list. */
  checks:           Array<SkeletonResourceCheck>;
}
/** SkeletonResource Check. */
export type SkeletonResourceCheck = {
  /** Check name. */
  name:               string;
  /** Whether the Check is deprecated. */
  deprecated:         boolean;
  /** Check deprecation reason. */
  deprecatedReason:   string;
  /** Check method name. */
  methodName:         string;
  /** Check method Skel name. */
  methodSkelName:     string;
  /** Parameter list. */
  arguments:          Array<SkeletonField>;
  /** Whether all input arguments are sensitive. */
  argumentsSensitive: boolean;
}
/** Skeleton Resource item. */
export type SkeletonResourceItem = {
  /** Domain. */
  domain:           string;
  /** Skeleton item hash. */
  schemaHash:       string;
  /** Primary skeleton item hash. */
  mainSchemaHash:   string;
  /** Whether there are multiple valid versions of the skeleton item. */
  isMultiVersion:   boolean;
  /** Whether it is the main version of the skeleton item. */
  isMain:           boolean;
  /** Owning DomainSchema hash. */
  domainSchemaHash: string;
  /** Resource name. */
  name:             string;
  /** Resource Skel name. */
  skelName:         string;
  /** Resource description. */
  description:      string;
  /** Whether the Resource is deprecated. */
  deprecated:       boolean;
  /** Resource deprecation reason. */
  deprecatedReason: string;
  /** Resource level Check list. */
  checks:           Array<SkeletonResourceCheck>;
  /** Action list. */
  actions:          Array<SkeletonResourceAction>;
  /** Check service. */
  checkService:     SkeletonServiceItem | null;
}
/** Skeleton service items. */
export type SkeletonServiceItem = {
  /** Domain. */
  domain:           string;
  /** Skeleton item hash. */
  schemaHash:       string;
  /** Primary skeleton item hash. */
  mainSchemaHash:   string;
  /** Whether there are multiple valid versions of the skeleton item. */
  isMultiVersion:   boolean;
  /** Whether it is the main version of the skeleton item. */
  isMain:           boolean;
  /** Owning DomainSchema hash. */
  domainSchemaHash: string;
  /** Service name. */
  name:             string;
  /** Service Skel name. */
  skelName:         string;
  /** Service Description. */
  description:      string;
  /** Whether the Service is deprecated. */
  deprecated:       boolean;
  /** Service deprecation reason. */
  deprecatedReason: string;
  /** Whether the item is public. */
  pub:              boolean;
  api:              boolean;
  /** Authentication mode. */
  authMode:         string;
  /** Permission requirements. */
  require:          SkeletonPermExpr | null;
  /** Accessible Actor List. */
  actors:           Array<SkeletonActorRef>;
  /** Method list. */
  methods:          Array<SkeletonMethod>;
}
/** Skeleton task. */
export type SkeletonTask = {
  /** Domain. */
  domain:           string;
  /** Skeleton item hash. */
  schemaHash:       string;
  /** Primary skeleton item hash. */
  mainSchemaHash:   string;
  /** Whether there are multiple valid versions of the skeleton item. */
  isMultiVersion:   boolean;
  /** Whether it is the main version of the skeleton item. */
  isMain:           boolean;
  /** Owning DomainSchema hash. */
  domainSchemaHash: string;
  /** Task name. */
  name:             string;
  /** Task Skel name. */
  skelName:         string;
  /** Task description. */
  description:      string;
  /** Whether the Task is deprecated. */
  deprecated:       boolean;
  /** Task deprecation reason. */
  deprecatedReason: string;
  /** Trigger list. */
  triggers:         Array<SkeletonTrigger>;
}
/** Skeleton task trigger. */
export type SkeletonTrigger = {
  /** Trigger name. */
  name:               string;
  /** Trigger Skel name. */
  skelName:           string;
  /** Trigger description. */
  description:        string;
  /** Whether the Trigger is deprecated. */
  deprecated:         boolean;
  /** Trigger deprecation reason. */
  deprecatedReason:   string;
  /** Input description. */
  inputDescription:   string;
  /** Input example. */
  example:            string;
  /** Parameter list. */
  arguments:          Array<SkeletonField>;
  /** Whether all input arguments are sensitive. */
  argumentsSensitive: boolean;
}
/** Skeleton web page. */
export type SkeletonWebItem = {
  /** Domain. */
  domain:           string;
  /** Skeleton item hash. */
  schemaHash:       string;
  /** Primary skeleton item hash. */
  mainSchemaHash:   string;
  /** Whether there are multiple valid versions of the skeleton item. */
  isMultiVersion:   boolean;
  /** Whether it is the main version of the skeleton item. */
  isMain:           boolean;
  /** Owning DomainSchema hash. */
  domainSchemaHash: string;
  /** Web page name. */
  name:             string;
  /** Web Skel name. */
  skelName:         string;
  /** Web page description. */
  description:      string;
  /** Whether the Web is deprecated. */
  deprecated:       boolean;
  /** Web deprecation reason. */
  deprecatedReason: string;
  /** Accessible Actor List. */
  actors:           Array<SkeletonActorRef>;
}
/** Task Debug initiates a request by default. */
export type TaskDebugDefaultLaunchRequest = {
  /** Trace ID. */
  traceId:       string;
  /** Span ID. */
  spanId:        string;
  /** Default task parameters JSON. */
  argumentsJson: string;
}
/** Task Debug initiates a request. */
export type TaskDebugLaunchRequest = {
  /** Task Skel name. */
  taskSkelName:    string;
  /** Task schema hash. */
  schemaHash:      string;
  /** Trigger Skel name. */
  triggerSkelName: string;
  /** Task parameters JSON. */
  argumentsJson:   string;
  /** Trace ID. */
  traceId:         string | null;
  /** Span ID. */
  spanId:          string | null;
}
/** Task called by Task Debug. */
export type TaskDebugTaskItem = {
  /** Task name. */
  name:             string;
  /** Task Skel name. */
  taskSkelName:     string;
  /** Task schema hash. */
  schemaHash:       string;
  /** Task description. */
  description:      string;
  /** Whether the Task is deprecated. */
  deprecated:       boolean;
  /** Task deprecation reason. */
  deprecatedReason: string;
}
/** Trigger called by Task Debug. */
export type TaskDebugTriggerItem = {
  /** Trigger name. */
  name:             string;
  /** Trigger Skel name. */
  skelName:         string;
  /** Trigger description. */
  description:      string;
  /** Whether the Trigger is deprecated. */
  deprecated:       boolean;
  /** Trigger deprecation reason. */
  deprecatedReason: string;
  /** Input description. */
  inputDescription: string;
  /** Input example. */
  example:          string;
  /** Parameter list. */
  arguments:        Array<SkeletonField>;
}
/** Task execution Cron schedule. */
export type TaskRunnerCronScheduler = {
  /** Trigger Skel name. */
  triggerSkelName: string;
  /** Cron expression. */
  cronExpr:        string;
}
/** Task execution capability registration information provided by the application. */
export type TaskRunnerRegistration = {
  /** Task Skel name. */
  taskSkelName:   string;
  /** Task schema hash. */
  schemaHash:     string;
  /** Execution timeout, in milliseconds. */
  timeoutMs:      number;
  /** Maximum concurrency. */
  concurrency:    number;
  /** Whether to disallow retrying after failure. */
  noRetry:        boolean;
  /** Cron schedule list. */
  cronSchedulers: Array<TaskRunnerCronScheduler>;
}
/** Web processing capability registration information provided by the application. */
export type WebHandlerRegistration = {
  /** Web Skel name. */
  webSkelName: string;
  /** Web schema hash. */
  schemaHash:  string;
  /** Web proxy access address. */
  endpoint:    string;
}
export {};
