// Code generated by skelc. DO NOT EDIT.

import type {
  VrpcClient,
  VrpcRequestOptions,
} from '@yorun-ai/vrpc';
import {
  AppConfigApiServiceSpec,
  AppStatusApiServiceSpec,
  EventDebugApiServiceSpec,
  MaintenanceApiServiceSpec,
  PortalCertApiServiceSpec,
  PortalEntryApiServiceSpec,
  PortalRuleApiServiceSpec,
  PortalSiteApiServiceSpec,
  ServiceDebugApiServiceSpec,
  SkeletonApiServiceSpec,
  TaskDebugApiServiceSpec,
} from './spec';
import type {
  AppConfigItem,
  AppConfigUpdate,
  AppConfigCreation,
  AppStatusView,
  EventDebugEventItem,
  EventDebugDefaultEmitRequest,
  EventDebugEmitRequest,
  SeedPreview,
  SeedItemSelection,
  PortalCert,
  PortalCertCreation,
  PortalCertUpdate,
  PortalEntry,
  PortalEntryAccessUpdate,
  PortalRule,
  PortalRuleCreation,
  PortalRuleUpdate,
  PortalDashboardAccess,
  PortalSite,
  PortalSiteOptions,
  PortalSiteCreation,
  PortalSiteUpdate,
  ServiceDebugAppInstance,
  ServiceDebugServiceItem,
  ServiceDebugMethodItem,
  ServiceDebugDefaultInvokeRequest,
  ServiceDebugInvokeResponse,
  ServiceDebugInvokeRequest,
  SkeletonDomain,
  SkeletonActorItem,
  SkeletonServiceItem,
  SkeletonResourceItem,
  SkeletonWebItem,
  SkeletonTask,
  SkeletonEventItem,
  SkeletonData,
  SkeletonConfigItem,
  TaskDebugTaskItem,
  TaskDebugTriggerItem,
  TaskDebugDefaultLaunchRequest,
  TaskDebugLaunchRequest,
} from './data';
/**
 * Hub's application configuration service, called by Client
 */
export function createAppConfigApiService(client: VrpcClient) {
  return {
    /**
     * List configuration items.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<AppConfigItem> - Configuration item list
     */
    list(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<AppConfigItem>>({
        serviceName: AppConfigApiServiceSpec.serviceName,
        methodName: AppConfigApiServiceSpec.methods.list,
        params,
        options,
      });
    },
    /**
     * Read configuration.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns AppConfigItem - Configuration items
     */
    get(
      params: {
        id: number;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<AppConfigItem>({
        serviceName: AppConfigApiServiceSpec.serviceName,
        methodName: AppConfigApiServiceSpec.methods.get,
        params,
        options,
      });
    },
    /**
     * Modify configuration.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns AppConfigItem - Configuration items
     */
    update(
      params: {
        id: number;
        update: AppConfigUpdate;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<AppConfigItem>({
        serviceName: AppConfigApiServiceSpec.serviceName,
        methodName: AppConfigApiServiceSpec.methods.update,
        params,
        options,
      });
    },
    /**
     * Create configuration.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns AppConfigItem - Configuration items
     */
    create(
      params: {
        creation: AppConfigCreation;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<AppConfigItem>({
        serviceName: AppConfigApiServiceSpec.serviceName,
        methodName: AppConfigApiServiceSpec.methods.create,
        params,
        options,
      });
    },
    /**
     * Delete unused configuration.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns boolean - Whether deletion succeeded
     */
    remove(
      params: {
        id: number;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<boolean>({
        serviceName: AppConfigApiServiceSpec.serviceName,
        methodName: AppConfigApiServiceSpec.methods.remove,
        params,
        options,
      });
    },
  };
}
/**
 * Hub Dashboard's application status service
 */
export function createAppStatusApiService(client: VrpcClient) {
  return {
    /**
     * List application instance statuses currently stored in Redis.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<AppStatusView> -
     */
    list(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<AppStatusView>>({
        serviceName: AppStatusApiServiceSpec.serviceName,
        methodName: AppStatusApiServiceSpec.methods.list,
        params,
        options,
      });
    },
  };
}
/**
 * Hub Dashboard Event Debugging Service
 */
export function createEventDebugApiService(client: VrpcClient) {
  return {
    /**
     * List the events monitored by the application instance.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<EventDebugEventItem> -
     */
    listEvents(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<EventDebugEventItem>>({
        serviceName: EventDebugApiServiceSpec.serviceName,
        methodName: EventDebugApiServiceSpec.methods.listEvents,
        params,
        options,
      });
    },
    /**
     * Generate a default Event send request.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns EventDebugDefaultEmitRequest -
     */
    buildDefaultEmitRequest(
      params: {
        eventSkelName: string;
        schemaHash: string;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<EventDebugDefaultEmitRequest>({
        serviceName: EventDebugApiServiceSpec.serviceName,
        methodName: EventDebugApiServiceSpec.methods.buildDefaultEmitRequest,
        params,
        options,
      });
    },
    /**
     * Send Event.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     */
    emitEvent(
      params: {
        request: EventDebugEmitRequest;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<void>({
        serviceName: EventDebugApiServiceSpec.serviceName,
        methodName: EventDebugApiServiceSpec.methods.emitEvent,
        params,
        options,
      });
    },
  };
}
/**
 * Hub maintenance service
 */
export function createMaintenanceApiService(client: VrpcClient) {
  return {
    /**
     * Preview Seed YAML differences.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns SeedPreview - Seed preview
     */
    previewSeedYaml(
      params: {
        content: string;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<SeedPreview>({
        serviceName: MaintenanceApiServiceSpec.serviceName,
        methodName: MaintenanceApiServiceSpec.methods.previewSeedYaml,
        params,
        options,
      });
    },
    /**
     * Apply Seed YAML entity updates.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns SeedPreview - Updated Seed preview
     */
    applySeedYaml(
      params: {
        content: string;
        selections: Array<SeedItemSelection>;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<SeedPreview>({
        serviceName: MaintenanceApiServiceSpec.serviceName,
        methodName: MaintenanceApiServiceSpec.methods.applySeedYaml,
        params,
        options,
      });
    },
  };
}
/**
 * Hub's Portal site certificate service, called by the Portal admin client
 */
export function createPortalCertApiService(client: VrpcClient) {
  return {
    /**
     * List Portal site certificates.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<PortalCert> - Portal site certificate list
     */
    list(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<PortalCert>>({
        serviceName: PortalCertApiServiceSpec.serviceName,
        methodName: PortalCertApiServiceSpec.methods.list,
        params,
        options,
      });
    },
    /**
     * Read the Portal site certificate.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalCert - Portal site certificate
     */
    get(
      params: {
        id: number;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalCert>({
        serviceName: PortalCertApiServiceSpec.serviceName,
        methodName: PortalCertApiServiceSpec.methods.get,
        params,
        options,
      });
    },
    /**
     * Create Portal site certificate.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalCert - Portal site certificate
     */
    create(
      params: {
        creation: PortalCertCreation;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalCert>({
        serviceName: PortalCertApiServiceSpec.serviceName,
        methodName: PortalCertApiServiceSpec.methods.create,
        params,
        options,
      });
    },
    /**
     * Modify Portal site certificate.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalCert - Portal site certificate
     */
    update(
      params: {
        id: number;
        update: PortalCertUpdate;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalCert>({
        serviceName: PortalCertApiServiceSpec.serviceName,
        methodName: PortalCertApiServiceSpec.methods.update,
        params,
        options,
      });
    },
    /**
     * Delete Portal site certificate.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     */
    remove(
      params: {
        id: number;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<void>({
        serviceName: PortalCertApiServiceSpec.serviceName,
        methodName: PortalCertApiServiceSpec.methods.remove,
        params,
        options,
      });
    },
  };
}
/**
 * Hub's Portal access entry service, called by the Portal admin client
 */
export function createPortalEntryApiService(client: VrpcClient) {
  return {
    /**
     * List Portal access entries.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<PortalEntry> - Portal access entry list
     */
    list(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<PortalEntry>>({
        serviceName: PortalEntryApiServiceSpec.serviceName,
        methodName: PortalEntryApiServiceSpec.methods.list,
        params,
        options,
      });
    },
    /**
     * Modify Portal access configuration.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalEntry - Portal access entry
     */
    updateAccess(
      params: {
        scheme: string;
        host: string;
        port: number;
        update: PortalEntryAccessUpdate;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalEntry>({
        serviceName: PortalEntryApiServiceSpec.serviceName,
        methodName: PortalEntryApiServiceSpec.methods.updateAccess,
        params,
        options,
      });
    },
  };
}
/**
 * Hub's Portal entry rule service, called by the Portal admin client
 */
export function createPortalRuleApiService(client: VrpcClient) {
  return {
    /**
     * List Portal entry rules.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<PortalRule> - Portal entry rule list
     */
    list(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<PortalRule>>({
        serviceName: PortalRuleApiServiceSpec.serviceName,
        methodName: PortalRuleApiServiceSpec.methods.list,
        params,
        options,
      });
    },
    /**
     * Read Portal entry rules.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalRule - Portal entry rules
     */
    get(
      params: {
        id: number;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalRule>({
        serviceName: PortalRuleApiServiceSpec.serviceName,
        methodName: PortalRuleApiServiceSpec.methods.get,
        params,
        options,
      });
    },
    /**
     * Create Portal entry rules.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalRule - Portal entry rules
     */
    create(
      params: {
        creation: PortalRuleCreation;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalRule>({
        serviceName: PortalRuleApiServiceSpec.serviceName,
        methodName: PortalRuleApiServiceSpec.methods.create,
        params,
        options,
      });
    },
    /**
     * Modify Portal entry rules.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalRule - Portal entry rules
     */
    update(
      params: {
        id: number;
        update: PortalRuleUpdate;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalRule>({
        serviceName: PortalRuleApiServiceSpec.serviceName,
        methodName: PortalRuleApiServiceSpec.methods.update,
        params,
        options,
      });
    },
    /**
     * Delete Portal entry rules.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     */
    remove(
      params: {
        id: number;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<void>({
        serviceName: PortalRuleApiServiceSpec.serviceName,
        methodName: PortalRuleApiServiceSpec.methods.remove,
        params,
        options,
      });
    },
    /**
     * Get the Hub Dashboard access entry.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalDashboardAccess - Hub Dashboard access entry
     */
    getDashboardAccess(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalDashboardAccess>({
        serviceName: PortalRuleApiServiceSpec.serviceName,
        methodName: PortalRuleApiServiceSpec.methods.getDashboardAccess,
        params,
        options,
      });
    },
    /**
     * Modify Hub Dashboard access entry.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<PortalRule> - Hub Dashboard entry rules
     */
    updateDashboardAccess(
      params: {
        scheme: string;
        host: string;
        port: number;
        pathPrefix: string;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<PortalRule>>({
        serviceName: PortalRuleApiServiceSpec.serviceName,
        methodName: PortalRuleApiServiceSpec.methods.updateDashboardAccess,
        params,
        options,
      });
    },
  };
}
/**
 * Hub's Portal target site service, called by the Portal admin client
 */
export function createPortalSiteApiService(client: VrpcClient) {
  return {
    /**
     * List Portal target sites.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<PortalSite> - Portal target site list
     */
    list(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<PortalSite>>({
        serviceName: PortalSiteApiServiceSpec.serviceName,
        methodName: PortalSiteApiServiceSpec.methods.list,
        params,
        options,
      });
    },
    /**
     * List Portal target site form options.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalSiteOptions - Portal target site form options
     */
    listOptions(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalSiteOptions>({
        serviceName: PortalSiteApiServiceSpec.serviceName,
        methodName: PortalSiteApiServiceSpec.methods.listOptions,
        params,
        options,
      });
    },
    /**
     * Read the Portal target site.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalSite - Portal target site
     */
    get(
      params: {
        id: number;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalSite>({
        serviceName: PortalSiteApiServiceSpec.serviceName,
        methodName: PortalSiteApiServiceSpec.methods.get,
        params,
        options,
      });
    },
    /**
     * Create Portal target site.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalSite - Portal target site
     */
    create(
      params: {
        creation: PortalSiteCreation;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalSite>({
        serviceName: PortalSiteApiServiceSpec.serviceName,
        methodName: PortalSiteApiServiceSpec.methods.create,
        params,
        options,
      });
    },
    /**
     * Modify Portal target site.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns PortalSite - Portal target site
     */
    update(
      params: {
        id: number;
        update: PortalSiteUpdate;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<PortalSite>({
        serviceName: PortalSiteApiServiceSpec.serviceName,
        methodName: PortalSiteApiServiceSpec.methods.update,
        params,
        options,
      });
    },
    /**
     * Delete Portal target site.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     */
    remove(
      params: {
        id: number;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<void>({
        serviceName: PortalSiteApiServiceSpec.serviceName,
        methodName: PortalSiteApiServiceSpec.methods.remove,
        params,
        options,
      });
    },
  };
}
/**
 * Hub Dashboard Service debugging service
 */
export function createServiceDebugApiService(client: VrpcClient) {
  return {
    /**
     * List application instances.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<ServiceDebugAppInstance> -
     */
    listAppInstances(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<ServiceDebugAppInstance>>({
        serviceName: ServiceDebugApiServiceSpec.serviceName,
        methodName: ServiceDebugApiServiceSpec.methods.listAppInstances,
        params,
        options,
      });
    },
    /**
     * List the services provided by the application instance.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<ServiceDebugServiceItem> -
     */
    listServices(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<ServiceDebugServiceItem>>({
        serviceName: ServiceDebugApiServiceSpec.serviceName,
        methodName: ServiceDebugApiServiceSpec.methods.listServices,
        params,
        options,
      });
    },
    /**
     * List application instances that provide the specified service.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<ServiceDebugAppInstance> -
     */
    listServiceAppInstances(
      params: {
        serviceSkelName: string;
        schemaHash: string;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<ServiceDebugAppInstance>>({
        serviceName: ServiceDebugApiServiceSpec.serviceName,
        methodName: ServiceDebugApiServiceSpec.methods.listServiceAppInstances,
        params,
        options,
      });
    },
    /**
     * List Service methods.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<ServiceDebugMethodItem> -
     */
    listMethods(
      params: {
        serviceSkelName: string;
        schemaHash: string;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<ServiceDebugMethodItem>>({
        serviceName: ServiceDebugApiServiceSpec.serviceName,
        methodName: ServiceDebugApiServiceSpec.methods.listMethods,
        params,
        options,
      });
    },
    /**
     * Generate default Service call request.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns ServiceDebugDefaultInvokeRequest -
     */
    buildDefaultInvokeRequest(
      params: {
        serviceSkelName: string;
        schemaHash: string;
        methodSkelName: string;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<ServiceDebugDefaultInvokeRequest>({
        serviceName: ServiceDebugApiServiceSpec.serviceName,
        methodName: ServiceDebugApiServiceSpec.methods.buildDefaultInvokeRequest,
        params,
        options,
      });
    },
    /**
     * Call Service method.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns ServiceDebugInvokeResponse -
     */
    invokeService(
      params: {
        request: ServiceDebugInvokeRequest;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<ServiceDebugInvokeResponse>({
        serviceName: ServiceDebugApiServiceSpec.serviceName,
        methodName: ServiceDebugApiServiceSpec.methods.invokeService,
        params,
        options,
      });
    },
  };
}
/**
 * Hub's skeleton service, called by the Portal admin client
 */
export function createSkeletonApiService(client: VrpcClient) {
  return {
    /**
     * List Domain skeleton.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<SkeletonDomain> - Domain skeleton list
     */
    listDomains(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<SkeletonDomain>>({
        serviceName: SkeletonApiServiceSpec.serviceName,
        methodName: SkeletonApiServiceSpec.methods.listDomains,
        params,
        options,
      });
    },
    /**
     * List Actor Skeleton.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<SkeletonActorItem> - Actor skeleton list
     */
    listActors(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<SkeletonActorItem>>({
        serviceName: SkeletonApiServiceSpec.serviceName,
        methodName: SkeletonApiServiceSpec.methods.listActors,
        params,
        options,
      });
    },
    /**
     * List Service skeleton.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<SkeletonServiceItem> - Service skeleton list
     */
    listServices(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<SkeletonServiceItem>>({
        serviceName: SkeletonApiServiceSpec.serviceName,
        methodName: SkeletonApiServiceSpec.methods.listServices,
        params,
        options,
      });
    },
    /**
     * List Resource skeleton.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<SkeletonResourceItem> - Resource skeleton list
     */
    listResources(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<SkeletonResourceItem>>({
        serviceName: SkeletonApiServiceSpec.serviceName,
        methodName: SkeletonApiServiceSpec.methods.listResources,
        params,
        options,
      });
    },
    /**
     * List Web Skeletons.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<SkeletonWebItem> - Web skeleton list
     */
    listWebs(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<SkeletonWebItem>>({
        serviceName: SkeletonApiServiceSpec.serviceName,
        methodName: SkeletonApiServiceSpec.methods.listWebs,
        params,
        options,
      });
    },
    /**
     * List Task skeleton.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<SkeletonTask> - Task skeleton list
     */
    listTasks(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<SkeletonTask>>({
        serviceName: SkeletonApiServiceSpec.serviceName,
        methodName: SkeletonApiServiceSpec.methods.listTasks,
        params,
        options,
      });
    },
    /**
     * List Event skeletons.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<SkeletonEventItem> - Event skeleton list
     */
    listEvents(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<SkeletonEventItem>>({
        serviceName: SkeletonApiServiceSpec.serviceName,
        methodName: SkeletonApiServiceSpec.methods.listEvents,
        params,
        options,
      });
    },
    /**
     * List Data skeleton.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<SkeletonData> - Data skeleton list, including Enum
     */
    listData(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<SkeletonData>>({
        serviceName: SkeletonApiServiceSpec.serviceName,
        methodName: SkeletonApiServiceSpec.methods.listData,
        params,
        options,
      });
    },
    /**
     * List Config skeleton.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<SkeletonConfigItem> - Config skeleton list
     */
    listConfigs(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<SkeletonConfigItem>>({
        serviceName: SkeletonApiServiceSpec.serviceName,
        methodName: SkeletonApiServiceSpec.methods.listConfigs,
        params,
        options,
      });
    },
  };
}
/**
 * Hub Dashboard Task Debugging Service
 */
export function createTaskDebugApiService(client: VrpcClient) {
  return {
    /**
     * List the tasks provided by the application instance.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<TaskDebugTaskItem> -
     */
    listTasks(
      params: null,
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<TaskDebugTaskItem>>({
        serviceName: TaskDebugApiServiceSpec.serviceName,
        methodName: TaskDebugApiServiceSpec.methods.listTasks,
        params,
        options,
      });
    },
    /**
     * List Task triggers.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns Array<TaskDebugTriggerItem> -
     */
    listTriggers(
      params: {
        taskSkelName: string;
        schemaHash: string;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<Array<TaskDebugTriggerItem>>({
        serviceName: TaskDebugApiServiceSpec.serviceName,
        methodName: TaskDebugApiServiceSpec.methods.listTriggers,
        params,
        options,
      });
    },
    /**
     * Generate a default Task launch request.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     * @returns TaskDebugDefaultLaunchRequest -
     */
    buildDefaultLaunchRequest(
      params: {
        taskSkelName: string;
        schemaHash: string;
        triggerSkelName: string;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<TaskDebugDefaultLaunchRequest>({
        serviceName: TaskDebugApiServiceSpec.serviceName,
        methodName: TaskDebugApiServiceSpec.methods.buildDefaultLaunchRequest,
        params,
        options,
      });
    },
    /**
     * Initiate Task.
     * @param params - Request parameters, or null for methods without input
     * @param options - Optional invocation options
     */
    launchTask(
      params: {
        request: TaskDebugLaunchRequest;
      },
      options?: VrpcRequestOptions,
    ) {
      return client.invoke<void>({
        serviceName: TaskDebugApiServiceSpec.serviceName,
        methodName: TaskDebugApiServiceSpec.methods.launchTask,
        params,
        options,
      });
    },
  };
}
