// Code generated by skelc. DO NOT EDIT.

export const AppConfigApiServiceSpec = {
  serviceName: 'vine.hub.admin.AppConfigApiService',
  methods: {
    list: 'list',
    get: 'get',
    update: 'update',
    create: 'create',
    remove: 'remove',
  },
} as const;

export const AppStatusApiServiceSpec = {
  serviceName: 'vine.hub.admin.AppStatusApiService',
  methods: {
    list: 'list',
  },
} as const;

export const EventDebugApiServiceSpec = {
  serviceName: 'vine.hub.admin.EventDebugApiService',
  methods: {
    listEvents: 'listEvents',
    buildDefaultEmitRequest: 'buildDefaultEmitRequest',
    emitEvent: 'emitEvent',
  },
} as const;

export const MaintenanceApiServiceSpec = {
  serviceName: 'vine.hub.admin.MaintenanceApiService',
  methods: {
    previewSeedYaml: 'previewSeedYaml',
    applySeedYaml: 'applySeedYaml',
  },
} as const;

export const PortalCertApiServiceSpec = {
  serviceName: 'vine.hub.admin.PortalCertApiService',
  methods: {
    list: 'list',
    get: 'get',
    create: 'create',
    update: 'update',
    remove: 'remove',
  },
} as const;

export const PortalEntryApiServiceSpec = {
  serviceName: 'vine.hub.admin.PortalEntryApiService',
  methods: {
    list: 'list',
    updateAccess: 'updateAccess',
  },
} as const;

export const PortalRuleApiServiceSpec = {
  serviceName: 'vine.hub.admin.PortalRuleApiService',
  methods: {
    list: 'list',
    get: 'get',
    create: 'create',
    update: 'update',
    remove: 'remove',
    getDashboardAccess: 'getDashboardAccess',
    updateDashboardAccess: 'updateDashboardAccess',
  },
} as const;

export const PortalSiteApiServiceSpec = {
  serviceName: 'vine.hub.admin.PortalSiteApiService',
  methods: {
    list: 'list',
    listOptions: 'listOptions',
    get: 'get',
    create: 'create',
    update: 'update',
    remove: 'remove',
  },
} as const;

export const ServiceDebugApiServiceSpec = {
  serviceName: 'vine.hub.admin.ServiceDebugApiService',
  methods: {
    listAppInstances: 'listAppInstances',
    listServices: 'listServices',
    listServiceAppInstances: 'listServiceAppInstances',
    listMethods: 'listMethods',
    buildDefaultInvokeRequest: 'buildDefaultInvokeRequest',
    invokeService: 'invokeService',
  },
} as const;

export const SkeletonApiServiceSpec = {
  serviceName: 'vine.hub.admin.SkeletonApiService',
  methods: {
    listDomains: 'listDomains',
    listActors: 'listActors',
    listServices: 'listServices',
    listResources: 'listResources',
    listWebs: 'listWebs',
    listTasks: 'listTasks',
    listEvents: 'listEvents',
    listData: 'listData',
    listConfigs: 'listConfigs',
  },
} as const;

export const TaskDebugApiServiceSpec = {
  serviceName: 'vine.hub.admin.TaskDebugApiService',
  methods: {
    listTasks: 'listTasks',
    listTriggers: 'listTriggers',
    buildDefaultLaunchRequest: 'buildDefaultLaunchRequest',
    launchTask: 'launchTask',
  },
} as const;
