#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
repo_dir="$(cd -- "${script_dir}/.." && pwd -P)"
output_file="${repo_dir}/THIRD_PARTY_LICENSES.txt"
go_licenses_version="v2.0.1"
temp_dir="$(mktemp -d)"
license_dir="${temp_dir}/licenses"
temp_output_file="${temp_dir}/THIRD_PARTY_LICENSES.txt"

cleanup() {
  rm -rf -- "${temp_dir}"
}
trap cleanup EXIT

cd "${repo_dir}"
GOWORK=off go run "github.com/google/go-licenses/v2@${go_licenses_version}" save \
  ./cmd/vine \
  --save_path "${license_dir}"

{
  printf 'Vine CLI third-party licenses\n'
  printf '=================================\n\n'
  printf 'This file is generated by script/gen-third-party-licenses.sh.\n'
  printf 'It contains notices and license texts for third-party code compiled into the Vine CLI.\n'

  while IFS= read -r license_file; do
    relative_path="${license_file#"${license_dir}/"}"
    if [[ "${relative_path}" == "go.yorun.ai/vine/LICENSE" ]]; then
      continue
    fi

    printf '\n\n-------------------------------------------------------------------------------\n'
    printf '%s\n' "${relative_path}"
    printf '%s\n' '-------------------------------------------------------------------------------'
    sed -e '$a\' "${license_file}"
  done < <(find "${license_dir}" -type f -print | LC_ALL=C sort)
} > "${temp_output_file}"

mv -f -- "${temp_output_file}" "${output_file}"
printf 'Third-party licenses written: %s (%s)\n' "${output_file}" "$(du -h "${output_file}" | awk '{print $1}')"
