#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
repo_dir="$(cd -- "${script_dir}/.." && pwd -P)"
dashboard_dir="${repo_dir}/internal/daemon/hub/src/server/mod/admin/dashboard"
output_file="${repo_dir}/THIRD_PARTY_LICENSES.txt"
dashboard_marker='=== Hub Dashboard third-party licenses ==='
case "${1:-}" in
  ''|--check-go) ;;
  *) echo 'Usage: gen-third-party-licenses.sh [--check-go]' >&2; exit 1 ;;
esac
go_licenses_version="v2.0.1"
temp_dir="$(mktemp -d)"
license_dir="${temp_dir}/licenses"
temp_output_file="${temp_dir}/THIRD_PARTY_LICENSES.txt"
go_licenses_bin="${temp_dir}/go-licenses"

cleanup() {
  rm -rf -- "${temp_dir}"
}
trap cleanup EXIT

cd "${repo_dir}"
GOBIN="${temp_dir}" GOWORK=off go install "github.com/google/go-licenses/v2@${go_licenses_version}"
GOOS=linux GOARCH=amd64 GOWORK=off "${go_licenses_bin}" save \
  ./cmd/vine \
  --save_path "${license_dir}"

{
  printf 'Vine third-party licenses\n'
  printf '=================================\n\n'
  printf 'This file is generated by script/gen-third-party-licenses.sh.\n'
  printf 'It contains notices and license texts for the Go CLI and embedded Hub Dashboard.\n'

  while IFS= read -r license_file; do
    relative_path="${license_file#"${license_dir}/"}"
    if [[ "${relative_path}" == "go.yorun.ai/vine/LICENSE" ]]; then
      continue
    fi

    printf '\n\n-------------------------------------------------------------------------------\n'
    printf '%s\n' "${relative_path}"
    printf '%s\n' '-------------------------------------------------------------------------------'
    LC_ALL=C awk '1' "${license_file}"
  done < <(find "${license_dir}" -type f -print | LC_ALL=C sort)
} > "${temp_output_file}"

if [[ "${1:-}" == --check-go ]]; then
  # Go-only CI does not need to install or rebuild the frontend. The Dashboard
  # packaging job independently checks its section against the actual bundle.
  awk -v marker="${dashboard_marker}" '
    $0 == marker { found = 1; exit }
    { print }
    END { if (!found) exit 1 }
  ' "${output_file}" > "${temp_dir}/committed-go-licenses.txt"
  diff -u "${temp_dir}/committed-go-licenses.txt" "${temp_output_file}"
  echo 'Go license inventory matches the build.'
  exit 0
fi

node "${dashboard_dir}/scripts/build-dashboard.mjs" "${temp_dir}/dashboard" "${temp_dir}/dashboard-licenses.txt"
printf '%s\n' "${dashboard_marker}" >> "${temp_output_file}"
cat "${temp_dir}/dashboard-licenses.txt" >> "${temp_output_file}"

mv -f -- "${temp_output_file}" "${output_file}"
printf 'Third-party licenses written: %s (%s)\n' "${output_file}" "$(du -h "${output_file}" | awk '{print $1}')"
