apiVersion: apps/v1
kind: Deployment
metadata:
  name: link
spec:
  template:
    spec:
      volumes:
        - name: mtls
          secret:
            secretName: vine-link-mtls
            defaultMode: 0440
      containers:
        - name: link
          env:
            - name: VINE_HUB_ENDPOINT
              value: https://hub:7071
            - name: VINE_MTLS_CA_FILE
              value: /run/vine/mtls/ca.pem
            - name: VINE_MTLS_CERT_FILE
              value: /run/vine/mtls/cert.pem
            - name: VINE_MTLS_KEY_FILE
              value: /run/vine/mtls/key.pem
          volumeMounts:
            - name: mtls
              mountPath: /run/vine/mtls
              readOnly: true
