// Code generated by skelc. DO NOT EDIT.

package control

import skeltype "go.yorun.ai/skel/types"

// AppRegistration Link application instance information registered with Hub
type AppRegistration struct {
	// Name Application name
	Name string `json:"name"`
	// InstanceId Application instance ID
	InstanceId skeltype.UUID `json:"instanceId"`
	// Version Application version
	Version string `json:"version"`
	// Endpoint Application access address (e.g. "http://10.1.2.3:23001")
	Endpoint string `json:"endpoint"`
	// ServiceHandlers List of Rpc service processing capabilities provided by the application
	ServiceHandlers []ServiceHandlerRegistration `json:"serviceHandlers"`
	// WebHandlers List of web processing capabilities provided by the application
	WebHandlers []WebHandlerRegistration `json:"webHandlers"`
	// EventListeners List of event listening capabilities provided by the application
	EventListeners []EventListenerRegistration `json:"eventListeners"`
	// TaskRunners List of task execution capabilities provided by the application
	TaskRunners []TaskRunnerRegistration `json:"taskRunners"`
	// DomainDescriptors List of all domain descriptors registered by the application
	DomainDescriptors []skeltype.JSON `json:"domainDescriptors"`
	// DomainSchemas Legacy schema registration input
	//
	// Deprecated: Use domainDescriptors instead.
	DomainSchemas []skeltype.JSON `json:"domainSchemas"`
}

// AppStatus Application instance status information, used for heartbeat refresh
type AppStatus struct {
	// Name Application name
	Name string `json:"name"`
	// InstanceId Application instance ID
	InstanceId skeltype.UUID `json:"instanceId"`
}

// EventListenerRegistration Event listening capability registration information provided by the application
type EventListenerRegistration struct {
	// EventSkelName Event Skel name
	EventSkelName string `json:"eventSkelName"`
	// DescriptorHash Event descriptor hash
	DescriptorHash string `json:"descriptorHash"`
	// TimeoutMs Execution timeout, in milliseconds
	TimeoutMs int `json:"timeoutMs"`
	// Concurrency Maximum concurrency
	Concurrency int `json:"concurrency"`
	// NoRetry Whether to disallow retrying after failure
	NoRetry bool `json:"noRetry"`
}

// Info Hub information
type Info struct {
	// Version Hub Vine runtime version
	Version string `json:"version"`
	// ApiPort Control API service port
	ApiPort int `json:"apiPort"`
	// WatchPort Configuration and service discovery watch port
	WatchPort int `json:"watchPort"`
	// MqEmbedded Whether MQ is embedded in Hub
	MqEmbedded bool `json:"mqEmbedded"`
	// MqNatsPort Embedded NATS service port
	MqNatsPort int `json:"mqNatsPort"`
	// MqNatsEndpoint External NATS service endpoint
	MqNatsEndpoint string `json:"mqNatsEndpoint"`
	// LockMode Lock mode: embedded, redis or disable
	LockMode string `json:"lockMode"`
	// LockRedisEndpoint External Redis endpoint for locks
	LockRedisEndpoint string `json:"lockRedisEndpoint"`
	// RedisPort Redis service port
	//
	// Deprecated: Use watchPort instead.
	RedisPort int `json:"redisPort"`
	// NatsPort NATS service port
	//
	// Deprecated: Use mqNatsPort instead.
	NatsPort int `json:"natsPort"`
	// MqEndpoint External NATS service endpoint
	//
	// Deprecated: Use mqNatsEndpoint instead.
	MqEndpoint string `json:"mqEndpoint"`
}

// PortalRegistration Portal instance registration information provided by Portal
type PortalRegistration struct {
	// InstanceId Portal instance ID
	InstanceId skeltype.UUID `json:"instanceId"`
	// Version Portal Vine runtime version
	Version string `json:"version"`
}

// PortalStatus Portal instance status information, used for heartbeat refresh
type PortalStatus struct {
	// InstanceId Portal instance ID
	InstanceId skeltype.UUID `json:"instanceId"`
}

// ServiceHandlerRegistration Rpc service processing capability registration information provided by the application
type ServiceHandlerRegistration struct {
	// ServiceSkelName Service Skel name
	ServiceSkelName string `json:"serviceSkelName"`
	// DescriptorHash Service descriptor hash
	DescriptorHash string `json:"descriptorHash"`
	// Endpoint Service agent access address
	Endpoint string `json:"endpoint"`
}

// TaskRunnerCronScheduler Task execution Cron schedule
type TaskRunnerCronScheduler struct {
	// TriggerSkelName Trigger Skel name
	TriggerSkelName string `json:"triggerSkelName"`
	// CronExpr Cron expression
	CronExpr string `json:"cronExpr"`
}

// TaskRunnerRegistration Task execution capability registration information provided by the application
type TaskRunnerRegistration struct {
	// TaskSkelName Task Skel name
	TaskSkelName string `json:"taskSkelName"`
	// DescriptorHash Task descriptor hash
	DescriptorHash string `json:"descriptorHash"`
	// TimeoutMs Execution timeout, in milliseconds
	TimeoutMs int `json:"timeoutMs"`
	// Concurrency Maximum concurrency
	Concurrency int `json:"concurrency"`
	// NoRetry Whether to disallow retrying after failure
	NoRetry bool `json:"noRetry"`
	// CronSchedulers Cron schedule list
	CronSchedulers []TaskRunnerCronScheduler `json:"cronSchedulers"`
}

// WebHandlerRegistration Web processing capability registration information provided by the application
type WebHandlerRegistration struct {
	// WebSkelName Web Skel name
	WebSkelName string `json:"webSkelName"`
	// DescriptorHash Web descriptor hash
	DescriptorHash string `json:"descriptorHash"`
	// Endpoint Web proxy access address
	Endpoint string `json:"endpoint"`
}
