// Code generated by skelc. DO NOT EDIT.

package control

import (
	rpc "go.yorun.ai/vine/internal/core/rpc/spec"
	"go.yorun.ai/vine/internal/core/skel"
)

// AppRegistration Link application instance information registered with Hub
type AppRegistration struct {
	// Name Application name
	Name string `json:"name"`
	// InstanceId Application instance ID
	InstanceId skel.UUID `json:"instanceId"`
	// Version Application version
	Version string `json:"version"`
	// Endpoint Application access address (e.g. "http://10.1.2.3:23001")
	Endpoint string `json:"endpoint"`
	// ServiceHandlers List of Rpc service processing capabilities provided by the application
	ServiceHandlers []ServiceHandlerRegistration `json:"serviceHandlers"`
	// WebHandlers List of web processing capabilities provided by the application
	WebHandlers []WebHandlerRegistration `json:"webHandlers"`
	// EventListeners List of event listening capabilities provided by the application
	EventListeners []EventListenerRegistration `json:"eventListeners"`
	// TaskRunners List of task execution capabilities provided by the application
	TaskRunners []TaskRunnerRegistration `json:"taskRunners"`
	// DomainSchemas List of all DomainSchemas registered by the application
	DomainSchemas []skel.JSON `json:"domainSchemas"`
}

func (v *AppRegistration) Validate(path string) error {
	if err := rpc.CheckValueNotNil(v, path); err != nil {
		return err
	}
	if err := rpc.CheckValueNotNil(v.ServiceHandlers, rpc.JoinPath(path, "ServiceHandlers")); err != nil {
		return err
	}
	if err := rpc.CheckValueNotNil(v.WebHandlers, rpc.JoinPath(path, "WebHandlers")); err != nil {
		return err
	}
	if err := rpc.CheckValueNotNil(v.EventListeners, rpc.JoinPath(path, "EventListeners")); err != nil {
		return err
	}
	if err := rpc.CheckValueNotNil(v.TaskRunners, rpc.JoinPath(path, "TaskRunners")); err != nil {
		return err
	}
	for i0 := range v.TaskRunners {
		if err := (&v.TaskRunners[i0]).Validate(rpc.JoinIndex(rpc.JoinPath(path, "TaskRunners"), i0)); err != nil {
			return err
		}
	}
	if err := rpc.CheckValueNotNil(v.DomainSchemas, rpc.JoinPath(path, "DomainSchemas")); err != nil {
		return err
	}
	return nil
}

// AppStatus Application instance status information, used for heartbeat refresh
type AppStatus struct {
	// Name Application name
	Name string `json:"name"`
	// InstanceId Application instance ID
	InstanceId skel.UUID `json:"instanceId"`
}

// EventListenerRegistration Event listening capability registration information provided by the application
type EventListenerRegistration struct {
	// EventSkelName Event Skel name
	EventSkelName string `json:"eventSkelName"`
	// SchemaHash Event schema hash
	SchemaHash string `json:"schemaHash"`
	// TimeoutMs Execution timeout, in milliseconds
	TimeoutMs int `json:"timeoutMs"`
	// Concurrency Maximum concurrency
	Concurrency int `json:"concurrency"`
	// NoRetry Whether to disallow retrying after failure
	NoRetry bool `json:"noRetry"`
}

// Info Hub information
type Info struct {
	// ApiPort Control API service port
	ApiPort int `json:"apiPort"`
	// RedisPort Redis service port
	RedisPort int `json:"redisPort"`
	// NatsPort NATS service port
	NatsPort int `json:"natsPort"`
	// MqEndpoint Standalone MQ service address
	MqEndpoint string `json:"mqEndpoint"`
}

// ServiceHandlerRegistration Rpc service processing capability registration information provided by the application
type ServiceHandlerRegistration struct {
	// ServiceSkelName Service Skel name
	ServiceSkelName string `json:"serviceSkelName"`
	// SchemaHash Service schema hash
	SchemaHash string `json:"schemaHash"`
	// Endpoint Service agent access address
	Endpoint string `json:"endpoint"`
}

// TaskRunnerCronScheduler Task execution Cron schedule
type TaskRunnerCronScheduler struct {
	// TriggerSkelName Trigger Skel name
	TriggerSkelName string `json:"triggerSkelName"`
	// CronExpr Cron expression
	CronExpr string `json:"cronExpr"`
}

// TaskRunnerRegistration Task execution capability registration information provided by the application
type TaskRunnerRegistration struct {
	// TaskSkelName Task Skel name
	TaskSkelName string `json:"taskSkelName"`
	// SchemaHash Task schema hash
	SchemaHash string `json:"schemaHash"`
	// TimeoutMs Execution timeout, in milliseconds
	TimeoutMs int `json:"timeoutMs"`
	// Concurrency Maximum concurrency
	Concurrency int `json:"concurrency"`
	// NoRetry Whether to disallow retrying after failure
	NoRetry bool `json:"noRetry"`
	// CronSchedulers Cron schedule list
	CronSchedulers []TaskRunnerCronScheduler `json:"cronSchedulers"`
}

func (v *TaskRunnerRegistration) Validate(path string) error {
	if err := rpc.CheckValueNotNil(v, path); err != nil {
		return err
	}
	if err := rpc.CheckValueNotNil(v.CronSchedulers, rpc.JoinPath(path, "CronSchedulers")); err != nil {
		return err
	}
	return nil
}

// WebHandlerRegistration Web processing capability registration information provided by the application
type WebHandlerRegistration struct {
	// WebSkelName Web Skel name
	WebSkelName string `json:"webSkelName"`
	// SchemaHash Web schema hash
	SchemaHash string `json:"schemaHash"`
	// Endpoint Web proxy access address
	Endpoint string `json:"endpoint"`
}
