// Code generated by skelc. DO NOT EDIT.

package control

import (
	"go.yorun.ai/skel/descriptor"
	"go.yorun.ai/vine/core/skel"
)

func init() {
	skel.RegisterDomainDescriptor(_DomainDescriptor)
}

var _DomainDescriptor = &descriptor.Domain{
	Name:        "vine.hub.control",
	Description: "Internal control API for Link and Portal",
	Hash:        "9cf55b12",
	Full:        true,
	Generated:   &descriptor.GeneratedInfo{CompilerVersion: "v0.31.1"},

	Data: []*descriptor.Data{
		{Name: "AppRegistration", SkelName: "vine.hub.control.AppRegistration", Description: "Link application instance information registered with Hub", Hash: "86418575", Members: []*descriptor.Member{
			{Name: "name", Description: "Application name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "instanceId", Description: "Application instance ID", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarUUID}},
			{Name: "version", Description: "Application version", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "endpoint", Description: "Application access address", Example: "\"http://10.1.2.3:23001\"", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "serviceHandlers", Description: "List of Rpc service processing capabilities provided by the application", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "ServiceHandlerRegistration", SkelName: "vine.hub.control.ServiceHandlerRegistration"}}},
			{Name: "webHandlers", Description: "List of web processing capabilities provided by the application", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "WebHandlerRegistration", SkelName: "vine.hub.control.WebHandlerRegistration"}}},
			{Name: "eventListeners", Description: "List of event listening capabilities provided by the application", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "EventListenerRegistration", SkelName: "vine.hub.control.EventListenerRegistration"}}},
			{Name: "taskRunners", Description: "List of task execution capabilities provided by the application", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "TaskRunnerRegistration", SkelName: "vine.hub.control.TaskRunnerRegistration"}}},
			{Name: "domainDescriptors", Description: "List of all domain descriptors registered by the application", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarJSON}}},
			{Name: "domainSchemas", Description: "Legacy schema registration input", Deprecated: true, DeprecatedReason: "Use domainDescriptors instead", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarJSON}}},
		}},
		{Name: "AppStatus", SkelName: "vine.hub.control.AppStatus", Description: "Application instance status information, used for heartbeat refresh", Hash: "72939602", Members: []*descriptor.Member{
			{Name: "name", Description: "Application name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "instanceId", Description: "Application instance ID", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarUUID}},
		}},
		{Name: "EventListenerRegistration", SkelName: "vine.hub.control.EventListenerRegistration", Description: "Event listening capability registration information provided by the application", Hash: "4c32cf0b", Members: []*descriptor.Member{
			{Name: "eventSkelName", Description: "Event Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "descriptorHash", Description: "Event descriptor hash", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "timeoutMs", Description: "Execution timeout, in milliseconds", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "concurrency", Description: "Maximum concurrency", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "noRetry", Description: "Whether to disallow retrying after failure", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}},
		}},
		{Name: "Info", SkelName: "vine.hub.control.Info", Description: "Hub information", Hash: "64a3f6c4", Members: []*descriptor.Member{
			{Name: "version", Description: "Hub Vine runtime version", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "apiPort", Description: "Control API service port", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "watchPort", Description: "Configuration and service discovery watch port", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "mqEmbedded", Description: "Whether MQ is embedded in Hub", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}},
			{Name: "mqNatsPort", Description: "Embedded NATS service port", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "mqNatsEndpoint", Description: "External NATS service endpoint", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "lockMode", Description: "Lock mode: embedded, redis or disable", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "lockRedisEndpoint", Description: "External Redis endpoint for locks", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "redisPort", Description: "Redis service port", Deprecated: true, DeprecatedReason: "Use watchPort instead", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "natsPort", Description: "NATS service port", Deprecated: true, DeprecatedReason: "Use mqNatsPort instead", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "mqEndpoint", Description: "External NATS service endpoint", Deprecated: true, DeprecatedReason: "Use mqNatsEndpoint instead", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
		{Name: "PortalRegistration", SkelName: "vine.hub.control.PortalRegistration", Description: "Portal instance registration information provided by Portal", Hash: "5a987267", Members: []*descriptor.Member{
			{Name: "instanceId", Description: "Portal instance ID", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarUUID}},
			{Name: "version", Description: "Portal Vine runtime version", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
		{Name: "PortalStatus", SkelName: "vine.hub.control.PortalStatus", Description: "Portal instance status information, used for heartbeat refresh", Hash: "e8c669a5", Members: []*descriptor.Member{
			{Name: "instanceId", Description: "Portal instance ID", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarUUID}},
		}},
		{Name: "ServiceHandlerRegistration", SkelName: "vine.hub.control.ServiceHandlerRegistration", Description: "Rpc service processing capability registration information provided by the application", Hash: "3f833c34", Members: []*descriptor.Member{
			{Name: "serviceSkelName", Description: "Service Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "descriptorHash", Description: "Service descriptor hash", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "endpoint", Description: "Service agent access address", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
		{Name: "TaskRunnerCronScheduler", SkelName: "vine.hub.control.TaskRunnerCronScheduler", Description: "Task execution Cron schedule", Hash: "d39e62de", Members: []*descriptor.Member{
			{Name: "triggerSkelName", Description: "Trigger Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "cronExpr", Description: "Cron expression", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
		{Name: "TaskRunnerRegistration", SkelName: "vine.hub.control.TaskRunnerRegistration", Description: "Task execution capability registration information provided by the application", Hash: "4887a98c", Members: []*descriptor.Member{
			{Name: "taskSkelName", Description: "Task Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "descriptorHash", Description: "Task descriptor hash", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "timeoutMs", Description: "Execution timeout, in milliseconds", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "concurrency", Description: "Maximum concurrency", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			{Name: "noRetry", Description: "Whether to disallow retrying after failure", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}},
			{Name: "cronSchedulers", Description: "Cron schedule list", Type: &descriptor.Type{Kind: descriptor.TypeKindList, Element: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "TaskRunnerCronScheduler", SkelName: "vine.hub.control.TaskRunnerCronScheduler"}}},
		}},
		{Name: "WebHandlerRegistration", SkelName: "vine.hub.control.WebHandlerRegistration", Description: "Web processing capability registration information provided by the application", Hash: "18d9098d", Members: []*descriptor.Member{
			{Name: "webSkelName", Description: "Web Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "descriptorHash", Description: "Web descriptor hash", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "endpoint", Description: "Web proxy access address", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
	},

	Services: []*descriptor.Service{
		{Name: "InfoService", SkelName: "vine.hub.control.InfoService", Description: "Hub's information service, called by Link", Hash: "1c4fd8ce", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "getInfo", SkelName: "getInfo", Description: "Read Hub information", Hash: "7d949d6d", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, OutputDescription: "Hub information", ResultType: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "Info", SkelName: "vine.hub.control.Info"}},
		}},
		{Name: "LockService", SkelName: "vine.hub.control.LockService", Description: "Distributed lease lock service", Hash: "19321bbe", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "acquire", SkelName: "acquire", Description: "Acquire a lock using a unique attempt token", Hash: "f085a1e5", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, ResultType: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}, Arguments: []*descriptor.Member{
				{Name: "key", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "token", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "ttlMillis", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			}},
			{Name: "renew", SkelName: "renew", Description: "Renew a lock owned by the token", Hash: "1b8b3625", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, ResultType: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}, Arguments: []*descriptor.Member{
				{Name: "key", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "token", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "ttlMillis", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarInt}},
			}},
			{Name: "release", SkelName: "release", Description: "Release a lock owned by the token", Hash: "2da2617f", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, ResultType: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}, Arguments: []*descriptor.Member{
				{Name: "key", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "token", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			}},
		}},
		{Name: "PortalRegistryService", SkelName: "vine.hub.control.PortalRegistryService", Description: "Hub's Portal registration service, called by Portal", Hash: "d3a88a51", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "register", SkelName: "register", Description: "Register a Portal instance", Hash: "661d736c", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, Arguments: []*descriptor.Member{
				{Name: "registration", Description: "Portal instance registration information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "PortalRegistration", SkelName: "vine.hub.control.PortalRegistration"}},
			}},
			{Name: "unregister", SkelName: "unregister", Description: "Unregister a Portal instance", Hash: "9d4d34bf", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, Arguments: []*descriptor.Member{
				{Name: "instanceId", Description: "Portal instance ID", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarUUID}},
			}},
			{Name: "heartbeat", SkelName: "heartbeat", Description: "Portal instance heartbeat", Hash: "f5ae4f0f", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, OutputDescription: "Whether the current Portal instance is still registered in the Hub", ResultType: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}, Arguments: []*descriptor.Member{
				{Name: "status", Description: "Portal instance status", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "PortalStatus", SkelName: "vine.hub.control.PortalStatus"}},
			}},
		}},
		{Name: "RegistryService", SkelName: "vine.hub.control.RegistryService", Description: "Hub's application registration service, called by Link", Hash: "ee06f954", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "register", SkelName: "register", Description: "Register application instance", Hash: "755adb3a", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, Arguments: []*descriptor.Member{
				{Name: "registration", Description: "Application instance registration information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "AppRegistration", SkelName: "vine.hub.control.AppRegistration"}},
			}},
			{Name: "unregister", SkelName: "unregister", Description: "Unregister an application instance", Hash: "252099ac", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, Arguments: []*descriptor.Member{
				{Name: "name", Description: "Application name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
				{Name: "instanceId", Description: "Application instance ID", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarUUID}},
			}},
			{Name: "heartbeat", SkelName: "heartbeat", Description: "Application instance heartbeat", Hash: "1f40e708", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, OutputDescription: "Whether the current instance is still registered in the Hub", ResultType: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarBoolean}, Arguments: []*descriptor.Member{
				{Name: "status", Description: "Application instance ID", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "AppStatus", SkelName: "vine.hub.control.AppStatus"}},
			}},
		}},
	},
}
