// Code generated by skelc. DO NOT EDIT.

// Package control Internal control API for Link and Portal
//
// This package is fully managed by skelc. Do not edit generated files or add
// handwritten Go files to it. Neither skelc nor Vine guarantees compilation,
// runtime behavior, or compatibility for generated packages containing
// unmanaged files.
package control
