// Code generated by skelc. DO NOT EDIT.

package control

import "go.yorun.ai/vine/internal/core/skel"

func init() {
	skel.RegisterDomainSchema(_DomainSchema)
}

var _DomainSchema = &skel.DomainSchema{
	Domain:      "vine.hub.control",
	Description: "Internal control API for Link and Portal",
	Hash:        "55e23029",
	Full:        true,
	Generated: &skel.GeneratedInfo{
		CompilerVersion: "v0.14.1",
	},

	Data: []*skel.DataSchema{
		{
			Name:        "AppRegistration",
			SkelName:    "vine.hub.control.AppRegistration",
			Description: "Link application instance information registered with Hub",
			Hash:        "2569befb",
			Members: []*skel.MemberSchema{
				{
					Name:        "name",
					Description: "Application name",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "instanceId",
					Description: "Application instance ID",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarUuid,
					},
				},
				{
					Name:        "version",
					Description: "Application version",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "endpoint",
					Description: "Application access address",
					Example:     "\"http://10.1.2.3:23001\"",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "serviceHandlers",
					Description: "List of Rpc service processing capabilities provided by the application",
					Type: &skel.TypeSchema{
						Kind: skel.TypeKindList,
						Element: &skel.TypeSchema{
							Kind:     skel.TypeKindData,
							Name:     "ServiceHandlerRegistration",
							SkelName: "vine.hub.control.ServiceHandlerRegistration",
						},
					},
				},
				{
					Name:        "webHandlers",
					Description: "List of web processing capabilities provided by the application",
					Type: &skel.TypeSchema{
						Kind: skel.TypeKindList,
						Element: &skel.TypeSchema{
							Kind:     skel.TypeKindData,
							Name:     "WebHandlerRegistration",
							SkelName: "vine.hub.control.WebHandlerRegistration",
						},
					},
				},
				{
					Name:        "eventListeners",
					Description: "List of event listening capabilities provided by the application",
					Type: &skel.TypeSchema{
						Kind: skel.TypeKindList,
						Element: &skel.TypeSchema{
							Kind:     skel.TypeKindData,
							Name:     "EventListenerRegistration",
							SkelName: "vine.hub.control.EventListenerRegistration",
						},
					},
				},
				{
					Name:        "taskRunners",
					Description: "List of task execution capabilities provided by the application",
					Type: &skel.TypeSchema{
						Kind: skel.TypeKindList,
						Element: &skel.TypeSchema{
							Kind:     skel.TypeKindData,
							Name:     "TaskRunnerRegistration",
							SkelName: "vine.hub.control.TaskRunnerRegistration",
						},
					},
				},
				{
					Name:        "domainSchemas",
					Description: "List of all DomainSchemas registered by the application",
					Type: &skel.TypeSchema{
						Kind: skel.TypeKindList,
						Element: &skel.TypeSchema{
							Kind:   skel.TypeKindScalar,
							Scalar: skel.ScalarJson,
						},
					},
				},
			},
		},
		{
			Name:        "AppStatus",
			SkelName:    "vine.hub.control.AppStatus",
			Description: "Application instance status information, used for heartbeat refresh",
			Hash:        "72939602",
			Members: []*skel.MemberSchema{
				{
					Name:        "name",
					Description: "Application name",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "instanceId",
					Description: "Application instance ID",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarUuid,
					},
				},
			},
		},
		{
			Name:        "EventListenerRegistration",
			SkelName:    "vine.hub.control.EventListenerRegistration",
			Description: "Event listening capability registration information provided by the application",
			Hash:        "690c1407",
			Members: []*skel.MemberSchema{
				{
					Name:        "eventSkelName",
					Description: "Event Skel name",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "schemaHash",
					Description: "Event schema hash",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "timeoutMs",
					Description: "Execution timeout, in milliseconds",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarInt,
					},
				},
				{
					Name:        "concurrency",
					Description: "Maximum concurrency",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarInt,
					},
				},
				{
					Name:        "noRetry",
					Description: "Whether to disallow retrying after failure",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarBool,
					},
				},
			},
		},
		{
			Name:        "Info",
			SkelName:    "vine.hub.control.Info",
			Description: "Hub information",
			Hash:        "739bccb5",
			Members: []*skel.MemberSchema{
				{
					Name:        "apiPort",
					Description: "Control API service port",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarInt,
					},
				},
				{
					Name:        "redisPort",
					Description: "Redis service port",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarInt,
					},
				},
				{
					Name:        "natsPort",
					Description: "NATS service port",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarInt,
					},
				},
				{
					Name:        "mqEndpoint",
					Description: "Standalone MQ service address",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
			},
		},
		{
			Name:        "ServiceHandlerRegistration",
			SkelName:    "vine.hub.control.ServiceHandlerRegistration",
			Description: "Rpc service processing capability registration information provided by the application",
			Hash:        "3928d52a",
			Members: []*skel.MemberSchema{
				{
					Name:        "serviceSkelName",
					Description: "Service Skel name",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "schemaHash",
					Description: "Service schema hash",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "endpoint",
					Description: "Service agent access address",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
			},
		},
		{
			Name:        "TaskRunnerCronScheduler",
			SkelName:    "vine.hub.control.TaskRunnerCronScheduler",
			Description: "Task execution Cron schedule",
			Hash:        "d39e62de",
			Members: []*skel.MemberSchema{
				{
					Name:        "triggerSkelName",
					Description: "Trigger Skel name",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "cronExpr",
					Description: "Cron expression",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
			},
		},
		{
			Name:        "TaskRunnerRegistration",
			SkelName:    "vine.hub.control.TaskRunnerRegistration",
			Description: "Task execution capability registration information provided by the application",
			Hash:        "84566b62",
			Members: []*skel.MemberSchema{
				{
					Name:        "taskSkelName",
					Description: "Task Skel name",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "schemaHash",
					Description: "Task schema hash",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "timeoutMs",
					Description: "Execution timeout, in milliseconds",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarInt,
					},
				},
				{
					Name:        "concurrency",
					Description: "Maximum concurrency",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarInt,
					},
				},
				{
					Name:        "noRetry",
					Description: "Whether to disallow retrying after failure",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarBool,
					},
				},
				{
					Name:        "cronSchedulers",
					Description: "Cron schedule list",
					Type: &skel.TypeSchema{
						Kind: skel.TypeKindList,
						Element: &skel.TypeSchema{
							Kind:     skel.TypeKindData,
							Name:     "TaskRunnerCronScheduler",
							SkelName: "vine.hub.control.TaskRunnerCronScheduler",
						},
					},
				},
			},
		},
		{
			Name:        "WebHandlerRegistration",
			SkelName:    "vine.hub.control.WebHandlerRegistration",
			Description: "Web processing capability registration information provided by the application",
			Hash:        "14bd9ab2",
			Members: []*skel.MemberSchema{
				{
					Name:        "webSkelName",
					Description: "Web Skel name",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "schemaHash",
					Description: "Web schema hash",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name:        "endpoint",
					Description: "Web proxy access address",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
			},
		},
	},

	Services: []*skel.ServiceSchema{
		{
			Name:        "InfoService",
			SkelName:    "vine.hub.control.InfoService",
			Description: "Hub's information service, called by Link",
			Hash:        "0d4b717f",
			Pub:         true,
			AuthMode:    skel.AuthModeUnset,
			Methods: []*skel.MethodSchema{
				{
					Name:              "getInfo",
					SkelName:          "getInfo",
					Description:       "Read Hub information",
					Hash:              "3929d753",
					AuthMode:          skel.AuthModeUnset,
					OutputDescription: "Hub information",
					ResultType: &skel.TypeSchema{
						Kind:     skel.TypeKindData,
						Name:     "Info",
						SkelName: "vine.hub.control.Info",
					},
				},
			},
		},
		{
			Name:        "RegistryService",
			SkelName:    "vine.hub.control.RegistryService",
			Description: "Hub's application registration service, called by Link",
			Hash:        "bde422d8",
			Pub:         true,
			AuthMode:    skel.AuthModeUnset,
			Methods: []*skel.MethodSchema{
				{
					Name:        "register",
					SkelName:    "register",
					Description: "Register application instance",
					Hash:        "1f651461",
					AuthMode:    skel.AuthModeUnset,
					Arguments: []*skel.MemberSchema{
						{
							Name:        "registration",
							Description: "Application instance registration information",
							Type: &skel.TypeSchema{
								Kind:     skel.TypeKindData,
								Name:     "AppRegistration",
								SkelName: "vine.hub.control.AppRegistration",
							},
						},
					},
				},
				{
					Name:        "unregister",
					SkelName:    "unregister",
					Description: "Unregister an application instance",
					Hash:        "252099ac",
					AuthMode:    skel.AuthModeUnset,
					Arguments: []*skel.MemberSchema{
						{
							Name:        "name",
							Description: "Application name",
							Type: &skel.TypeSchema{
								Kind:   skel.TypeKindScalar,
								Scalar: skel.ScalarString,
							},
						},
						{
							Name:        "instanceId",
							Description: "Application instance ID",
							Type: &skel.TypeSchema{
								Kind:   skel.TypeKindScalar,
								Scalar: skel.ScalarUuid,
							},
						},
					},
				},
				{
					Name:              "heartbeat",
					SkelName:          "heartbeat",
					Description:       "Application instance heartbeat",
					Hash:              "1f40e708",
					AuthMode:          skel.AuthModeUnset,
					OutputDescription: "Whether the current instance is still registered in the Hub",
					Arguments: []*skel.MemberSchema{
						{
							Name:        "status",
							Description: "Application instance ID",
							Type: &skel.TypeSchema{
								Kind:     skel.TypeKindData,
								Name:     "AppStatus",
								SkelName: "vine.hub.control.AppStatus",
							},
						},
					},
					ResultType: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarBool,
					},
				},
			},
		},
	},
}
