// Code generated by skelc. DO NOT EDIT.

package control

import (
	"reflect"

	"go.yorun.ai/vine/internal/core/ex"
	rpcclient "go.yorun.ai/vine/internal/core/rpc/client"
	rpcspec "go.yorun.ai/vine/internal/core/rpc/spec"
	"go.yorun.ai/vine/internal/core/skel"
)

func init() {
	rpcspec.Register(_InfoServiceSpec)
	rpcspec.Register(_LockServiceSpec)
	rpcspec.Register(_PortalRegistryServiceSpec)
	rpcspec.Register(_RegistryServiceSpec)
}

// InfoServiceServer Hub's information service, called by Link

// InfoService / Spec

var (
	_InfoServiceSpec = &rpcspec.ServiceSpec{
		Type:              rpcspec.ServiceSpecTypeBoth,
		Name:              "InfoService",
		SkelName:          "vine.hub.control.InfoService",
		Hash:              "1c4fd8ce",
		ServerType:        reflect.TypeFor[InfoServiceServer](),
		DefaultServerType: reflect.TypeFor[*DefaultInfoServiceServer](),
		ClientType:        reflect.TypeFor[InfoServiceClient](),
		ClientCtor:        NewInfoServiceClient,

		ERServerType:        reflect.TypeFor[InfoServiceServerER](),
		WrapperERServerCtor: _NewWrapperInfoServiceServerER,
		DefaultERServerType: reflect.TypeFor[*DefaultInfoServiceServerER](),
		ERClientType:        reflect.TypeFor[InfoServiceClientER](),
		ERClientCtor:        NewInfoServiceClientER,
		Methods: []*rpcspec.MethodSpec{
			_InfoServiceGetInfoSpec,
		},
	}
	_InfoServiceGetInfoSpec = &rpcspec.MethodSpec{
		Name:                        "GetInfo",
		SkelName:                    "getInfo",
		ArgumentsType:               nil,
		ResultType:                  reflect.TypeFor[Info](),
		ArgumentsSensitive:          false,
		ResultSensitive:             false,
		ArgumentsContainsBinaryType: false,
		ResultContainsBinaryType:    false,
		MethodFuncs: []any{
			InfoServiceClient.GetInfo,
			InfoServiceClientER.GetInfo,
			InfoServiceServer.GetInfo,
			InfoServiceServerER.GetInfo,
		},
	}
)

// InfoService / Server

type InfoServiceServer interface {
	// GetInfo Read Hub information.
	//   @returns Info - Hub information
	GetInfo() Info

	mustBeInfoServiceServer()
}

// InfoService / Server / DefaultServer

type DefaultInfoServiceServer struct{}

func (*DefaultInfoServiceServer) GetInfo() Info {
	ex.PanicNew(ex.InvalidRequest, "method getInfo is not implemented")
	return Info{}
}

func (*DefaultInfoServiceServer) mustBeInfoServiceServer() {}

// InfoService / ERServer

type InfoServiceServerER interface {
	GetInfo() (Info, ex.Error)

	mustBeInfoServiceServerER()
}

// InfoService / ERServer / WrapperERServer

type _WrapperInfoServiceServerER struct {
	DefaultInfoServiceServer
	serverImpl InfoServiceServer
}

func _NewWrapperInfoServiceServerER(serverImpl InfoServiceServer) InfoServiceServerER {
	return &_WrapperInfoServiceServerER{
		serverImpl: serverImpl,
	}
}

func (service *_WrapperInfoServiceServerER) server() InfoServiceServer {
	if service.serverImpl == nil {
		return &service.DefaultInfoServiceServer
	}
	return service.serverImpl
}

func (service *_WrapperInfoServiceServerER) GetInfo() (ret Info, err ex.Error) {
	defer func() { err = ex.Recover(recover()) }()
	ret = service.server().GetInfo()
	return
}

func (*_WrapperInfoServiceServerER) mustBeInfoServiceServerER() {}

// InfoService / ERServer / DefaultERServer

type DefaultInfoServiceServerER struct {
	_WrapperInfoServiceServerER
}

// InfoService / Client

type InfoServiceClient interface {
	// GetInfo Read Hub information.
	//   @returns Info - Hub information
	GetInfo(_ivOpts ...rpcclient.InvokeOption) Info
}

type _InfoServiceClient struct {
	clientER InfoServiceClientER
}

func NewInfoServiceClient(clientER InfoServiceClientER) InfoServiceClient {
	return &_InfoServiceClient{clientER: clientER}
}

func (client *_InfoServiceClient) GetInfo(_ivOpts ...rpcclient.InvokeOption) Info {
	ret, err := client.clientER.GetInfo(_ivOpts...)
	ex.PanicIfError(err)
	return ret
}

// InfoService / ERClient

type InfoServiceClientER interface {
	// GetInfo Read Hub information.
	//   @returns Info - Hub information
	GetInfo(_ivOpts ...rpcclient.InvokeOption) (Info, ex.Error)
}

type _InfoServiceClientER struct {
	rpcClient *rpcclient.Client
}

func NewInfoServiceClientER(rpcClient *rpcclient.Client) InfoServiceClientER {
	return &_InfoServiceClientER{
		rpcClient: rpcClient,
	}
}

func (client *_InfoServiceClientER) GetInfo(_ivOpts ...rpcclient.InvokeOption) (Info, ex.Error) {
	return client.rpcClient.InvokeAs[Info](_InfoServiceGetInfoSpec.Info(), nil, _ivOpts...)
}

// LockServiceServer Distributed lease lock service

// LockService / Spec

var (
	_LockServiceSpec = &rpcspec.ServiceSpec{
		Type:              rpcspec.ServiceSpecTypeBoth,
		Name:              "LockService",
		SkelName:          "vine.hub.control.LockService",
		Hash:              "19321bbe",
		ServerType:        reflect.TypeFor[LockServiceServer](),
		DefaultServerType: reflect.TypeFor[*DefaultLockServiceServer](),
		ClientType:        reflect.TypeFor[LockServiceClient](),
		ClientCtor:        NewLockServiceClient,

		ERServerType:        reflect.TypeFor[LockServiceServerER](),
		WrapperERServerCtor: _NewWrapperLockServiceServerER,
		DefaultERServerType: reflect.TypeFor[*DefaultLockServiceServerER](),
		ERClientType:        reflect.TypeFor[LockServiceClientER](),
		ERClientCtor:        NewLockServiceClientER,
		Methods: []*rpcspec.MethodSpec{
			_LockServiceAcquireSpec,
			_LockServiceRenewSpec,
			_LockServiceReleaseSpec,
		},
	}
	_LockServiceAcquireSpec = &rpcspec.MethodSpec{
		Name:                        "Acquire",
		SkelName:                    "acquire",
		ArgumentsType:               reflect.TypeFor[_LockServiceAcquireArguments](),
		ResultType:                  reflect.TypeFor[bool](),
		ArgumentsSensitive:          false,
		ResultSensitive:             false,
		ArgumentsContainsBinaryType: false,
		ResultContainsBinaryType:    false,
		MethodFuncs: []any{
			LockServiceClient.Acquire,
			LockServiceClientER.Acquire,
			LockServiceServer.Acquire,
			LockServiceServerER.Acquire,
		},
	}
	_LockServiceRenewSpec = &rpcspec.MethodSpec{
		Name:                        "Renew",
		SkelName:                    "renew",
		ArgumentsType:               reflect.TypeFor[_LockServiceRenewArguments](),
		ResultType:                  reflect.TypeFor[bool](),
		ArgumentsSensitive:          false,
		ResultSensitive:             false,
		ArgumentsContainsBinaryType: false,
		ResultContainsBinaryType:    false,
		MethodFuncs: []any{
			LockServiceClient.Renew,
			LockServiceClientER.Renew,
			LockServiceServer.Renew,
			LockServiceServerER.Renew,
		},
	}
	_LockServiceReleaseSpec = &rpcspec.MethodSpec{
		Name:                        "Release",
		SkelName:                    "release",
		ArgumentsType:               reflect.TypeFor[_LockServiceReleaseArguments](),
		ResultType:                  reflect.TypeFor[bool](),
		ArgumentsSensitive:          false,
		ResultSensitive:             false,
		ArgumentsContainsBinaryType: false,
		ResultContainsBinaryType:    false,
		MethodFuncs: []any{
			LockServiceClient.Release,
			LockServiceClientER.Release,
			LockServiceServer.Release,
			LockServiceServerER.Release,
		},
	}
)

// LockService / Arguments

type _LockServiceAcquireArguments struct {
	Key       string `json:"key" skel:"index(0)"`
	Token     string `json:"token" skel:"index(1)"`
	TtlMillis int    `json:"ttlMillis" skel:"index(2)"`
}

type _LockServiceRenewArguments struct {
	Key       string `json:"key" skel:"index(0)"`
	Token     string `json:"token" skel:"index(1)"`
	TtlMillis int    `json:"ttlMillis" skel:"index(2)"`
}

type _LockServiceReleaseArguments struct {
	Key   string `json:"key" skel:"index(0)"`
	Token string `json:"token" skel:"index(1)"`
}

// LockService / Server

type LockServiceServer interface {
	// Acquire Acquire a lock using a unique attempt token.
	Acquire(key string, token string, ttlMillis int) bool
	// Renew Renew a lock owned by the token.
	Renew(key string, token string, ttlMillis int) bool
	// Release Release a lock owned by the token.
	Release(key string, token string) bool

	mustBeLockServiceServer()
}

// LockService / Server / DefaultServer

type DefaultLockServiceServer struct{}

func (*DefaultLockServiceServer) Acquire(string, string, int) bool {
	ex.PanicNew(ex.InvalidRequest, "method acquire is not implemented")
	return false
}

func (*DefaultLockServiceServer) Renew(string, string, int) bool {
	ex.PanicNew(ex.InvalidRequest, "method renew is not implemented")
	return false
}

func (*DefaultLockServiceServer) Release(string, string) bool {
	ex.PanicNew(ex.InvalidRequest, "method release is not implemented")
	return false
}

func (*DefaultLockServiceServer) mustBeLockServiceServer() {}

// LockService / ERServer

type LockServiceServerER interface {
	Acquire(key string, token string, ttlMillis int) (bool, ex.Error)
	Renew(key string, token string, ttlMillis int) (bool, ex.Error)
	Release(key string, token string) (bool, ex.Error)

	mustBeLockServiceServerER()
}

// LockService / ERServer / WrapperERServer

type _WrapperLockServiceServerER struct {
	DefaultLockServiceServer
	serverImpl LockServiceServer
}

func _NewWrapperLockServiceServerER(serverImpl LockServiceServer) LockServiceServerER {
	return &_WrapperLockServiceServerER{
		serverImpl: serverImpl,
	}
}

func (service *_WrapperLockServiceServerER) server() LockServiceServer {
	if service.serverImpl == nil {
		return &service.DefaultLockServiceServer
	}
	return service.serverImpl
}

func (service *_WrapperLockServiceServerER) Acquire(key string, token string, ttlMillis int) (ret bool, err ex.Error) {
	defer func() { err = ex.Recover(recover()) }()
	ret = service.server().Acquire(key, token, ttlMillis)
	return
}

func (service *_WrapperLockServiceServerER) Renew(key string, token string, ttlMillis int) (ret bool, err ex.Error) {
	defer func() { err = ex.Recover(recover()) }()
	ret = service.server().Renew(key, token, ttlMillis)
	return
}

func (service *_WrapperLockServiceServerER) Release(key string, token string) (ret bool, err ex.Error) {
	defer func() { err = ex.Recover(recover()) }()
	ret = service.server().Release(key, token)
	return
}

func (*_WrapperLockServiceServerER) mustBeLockServiceServerER() {}

// LockService / ERServer / DefaultERServer

type DefaultLockServiceServerER struct {
	_WrapperLockServiceServerER
}

// LockService / Client

type LockServiceClient interface {
	// Acquire Acquire a lock using a unique attempt token.
	Acquire(key string, token string, ttlMillis int, _ivOpts ...rpcclient.InvokeOption) bool
	// Renew Renew a lock owned by the token.
	Renew(key string, token string, ttlMillis int, _ivOpts ...rpcclient.InvokeOption) bool
	// Release Release a lock owned by the token.
	Release(key string, token string, _ivOpts ...rpcclient.InvokeOption) bool
}

type _LockServiceClient struct {
	clientER LockServiceClientER
}

func NewLockServiceClient(clientER LockServiceClientER) LockServiceClient {
	return &_LockServiceClient{clientER: clientER}
}

func (client *_LockServiceClient) Acquire(key string, token string, ttlMillis int, _ivOpts ...rpcclient.InvokeOption) bool {
	ret, err := client.clientER.Acquire(key, token, ttlMillis, _ivOpts...)
	ex.PanicIfError(err)
	return ret
}

func (client *_LockServiceClient) Renew(key string, token string, ttlMillis int, _ivOpts ...rpcclient.InvokeOption) bool {
	ret, err := client.clientER.Renew(key, token, ttlMillis, _ivOpts...)
	ex.PanicIfError(err)
	return ret
}

func (client *_LockServiceClient) Release(key string, token string, _ivOpts ...rpcclient.InvokeOption) bool {
	ret, err := client.clientER.Release(key, token, _ivOpts...)
	ex.PanicIfError(err)
	return ret
}

// LockService / ERClient

type LockServiceClientER interface {
	// Acquire Acquire a lock using a unique attempt token.
	Acquire(key string, token string, ttlMillis int, _ivOpts ...rpcclient.InvokeOption) (bool, ex.Error)
	// Renew Renew a lock owned by the token.
	Renew(key string, token string, ttlMillis int, _ivOpts ...rpcclient.InvokeOption) (bool, ex.Error)
	// Release Release a lock owned by the token.
	Release(key string, token string, _ivOpts ...rpcclient.InvokeOption) (bool, ex.Error)
}

type _LockServiceClientER struct {
	rpcClient *rpcclient.Client
}

func NewLockServiceClientER(rpcClient *rpcclient.Client) LockServiceClientER {
	return &_LockServiceClientER{
		rpcClient: rpcClient,
	}
}

func (client *_LockServiceClientER) Acquire(key string, token string, ttlMillis int, _ivOpts ...rpcclient.InvokeOption) (bool, ex.Error) {
	return client.rpcClient.InvokeAs[bool](_LockServiceAcquireSpec.Info(), &_LockServiceAcquireArguments{
		Key:       key,
		Token:     token,
		TtlMillis: ttlMillis,
	}, _ivOpts...)
}

func (client *_LockServiceClientER) Renew(key string, token string, ttlMillis int, _ivOpts ...rpcclient.InvokeOption) (bool, ex.Error) {
	return client.rpcClient.InvokeAs[bool](_LockServiceRenewSpec.Info(), &_LockServiceRenewArguments{
		Key:       key,
		Token:     token,
		TtlMillis: ttlMillis,
	}, _ivOpts...)
}

func (client *_LockServiceClientER) Release(key string, token string, _ivOpts ...rpcclient.InvokeOption) (bool, ex.Error) {
	return client.rpcClient.InvokeAs[bool](_LockServiceReleaseSpec.Info(), &_LockServiceReleaseArguments{
		Key:   key,
		Token: token,
	}, _ivOpts...)
}

// PortalRegistryServiceServer Hub's Portal registration service, called by Portal

// PortalRegistryService / Spec

var (
	_PortalRegistryServiceSpec = &rpcspec.ServiceSpec{
		Type:              rpcspec.ServiceSpecTypeBoth,
		Name:              "PortalRegistryService",
		SkelName:          "vine.hub.control.PortalRegistryService",
		Hash:              "d3a88a51",
		ServerType:        reflect.TypeFor[PortalRegistryServiceServer](),
		DefaultServerType: reflect.TypeFor[*DefaultPortalRegistryServiceServer](),
		ClientType:        reflect.TypeFor[PortalRegistryServiceClient](),
		ClientCtor:        NewPortalRegistryServiceClient,

		ERServerType:        reflect.TypeFor[PortalRegistryServiceServerER](),
		WrapperERServerCtor: _NewWrapperPortalRegistryServiceServerER,
		DefaultERServerType: reflect.TypeFor[*DefaultPortalRegistryServiceServerER](),
		ERClientType:        reflect.TypeFor[PortalRegistryServiceClientER](),
		ERClientCtor:        NewPortalRegistryServiceClientER,
		Methods: []*rpcspec.MethodSpec{
			_PortalRegistryServiceRegisterSpec,
			_PortalRegistryServiceUnregisterSpec,
			_PortalRegistryServiceHeartbeatSpec,
		},
	}
	_PortalRegistryServiceRegisterSpec = &rpcspec.MethodSpec{
		Name:                        "Register",
		SkelName:                    "register",
		ArgumentsType:               reflect.TypeFor[_PortalRegistryServiceRegisterArguments](),
		ResultType:                  nil,
		ArgumentsSensitive:          false,
		ResultSensitive:             false,
		ArgumentsContainsBinaryType: false,
		ResultContainsBinaryType:    false,
		MethodFuncs: []any{
			PortalRegistryServiceClient.Register,
			PortalRegistryServiceClientER.Register,
			PortalRegistryServiceServer.Register,
			PortalRegistryServiceServerER.Register,
		},
	}
	_PortalRegistryServiceUnregisterSpec = &rpcspec.MethodSpec{
		Name:                        "Unregister",
		SkelName:                    "unregister",
		ArgumentsType:               reflect.TypeFor[_PortalRegistryServiceUnregisterArguments](),
		ResultType:                  nil,
		ArgumentsSensitive:          false,
		ResultSensitive:             false,
		ArgumentsContainsBinaryType: false,
		ResultContainsBinaryType:    false,
		MethodFuncs: []any{
			PortalRegistryServiceClient.Unregister,
			PortalRegistryServiceClientER.Unregister,
			PortalRegistryServiceServer.Unregister,
			PortalRegistryServiceServerER.Unregister,
		},
	}
	_PortalRegistryServiceHeartbeatSpec = &rpcspec.MethodSpec{
		Name:                        "Heartbeat",
		SkelName:                    "heartbeat",
		ArgumentsType:               reflect.TypeFor[_PortalRegistryServiceHeartbeatArguments](),
		ResultType:                  reflect.TypeFor[bool](),
		ArgumentsSensitive:          false,
		ResultSensitive:             false,
		ArgumentsContainsBinaryType: false,
		ResultContainsBinaryType:    false,
		MethodFuncs: []any{
			PortalRegistryServiceClient.Heartbeat,
			PortalRegistryServiceClientER.Heartbeat,
			PortalRegistryServiceServer.Heartbeat,
			PortalRegistryServiceServerER.Heartbeat,
		},
	}
)

// PortalRegistryService / Arguments

type _PortalRegistryServiceRegisterArguments struct {
	Registration PortalRegistration `json:"registration" skel:"index(0)"`
}

type _PortalRegistryServiceUnregisterArguments struct {
	InstanceId skel.UUID `json:"instanceId" skel:"index(0)"`
}

type _PortalRegistryServiceHeartbeatArguments struct {
	Status PortalStatus `json:"status" skel:"index(0)"`
}

// PortalRegistryService / Server

type PortalRegistryServiceServer interface {
	// Register Register a Portal instance.
	//   @param registration - Portal instance registration information
	Register(registration PortalRegistration)
	// Unregister Unregister a Portal instance.
	//   @param instanceId - Portal instance ID
	Unregister(instanceId skel.UUID)
	// Heartbeat Portal instance heartbeat.
	//   @param status - Portal instance status
	//   @returns bool - Whether the current Portal instance is still registered in the Hub
	Heartbeat(status PortalStatus) bool

	mustBePortalRegistryServiceServer()
}

// PortalRegistryService / Server / DefaultServer

type DefaultPortalRegistryServiceServer struct{}

func (*DefaultPortalRegistryServiceServer) Register(PortalRegistration) {
	ex.PanicNew(ex.InvalidRequest, "method register is not implemented")
}

func (*DefaultPortalRegistryServiceServer) Unregister(skel.UUID) {
	ex.PanicNew(ex.InvalidRequest, "method unregister is not implemented")
}

func (*DefaultPortalRegistryServiceServer) Heartbeat(PortalStatus) bool {
	ex.PanicNew(ex.InvalidRequest, "method heartbeat is not implemented")
	return false
}

func (*DefaultPortalRegistryServiceServer) mustBePortalRegistryServiceServer() {}

// PortalRegistryService / ERServer

type PortalRegistryServiceServerER interface {
	Register(registration PortalRegistration) ex.Error
	Unregister(instanceId skel.UUID) ex.Error
	Heartbeat(status PortalStatus) (bool, ex.Error)

	mustBePortalRegistryServiceServerER()
}

// PortalRegistryService / ERServer / WrapperERServer

type _WrapperPortalRegistryServiceServerER struct {
	DefaultPortalRegistryServiceServer
	serverImpl PortalRegistryServiceServer
}

func _NewWrapperPortalRegistryServiceServerER(serverImpl PortalRegistryServiceServer) PortalRegistryServiceServerER {
	return &_WrapperPortalRegistryServiceServerER{
		serverImpl: serverImpl,
	}
}

func (service *_WrapperPortalRegistryServiceServerER) server() PortalRegistryServiceServer {
	if service.serverImpl == nil {
		return &service.DefaultPortalRegistryServiceServer
	}
	return service.serverImpl
}

func (service *_WrapperPortalRegistryServiceServerER) Register(registration PortalRegistration) (err ex.Error) {
	defer func() { err = ex.Recover(recover()) }()
	service.server().Register(registration)
	return
}

func (service *_WrapperPortalRegistryServiceServerER) Unregister(instanceId skel.UUID) (err ex.Error) {
	defer func() { err = ex.Recover(recover()) }()
	service.server().Unregister(instanceId)
	return
}

func (service *_WrapperPortalRegistryServiceServerER) Heartbeat(status PortalStatus) (ret bool, err ex.Error) {
	defer func() { err = ex.Recover(recover()) }()
	ret = service.server().Heartbeat(status)
	return
}

func (*_WrapperPortalRegistryServiceServerER) mustBePortalRegistryServiceServerER() {}

// PortalRegistryService / ERServer / DefaultERServer

type DefaultPortalRegistryServiceServerER struct {
	_WrapperPortalRegistryServiceServerER
}

// PortalRegistryService / Client

type PortalRegistryServiceClient interface {
	// Register Register a Portal instance.
	//   @param registration - Portal instance registration information
	Register(registration PortalRegistration, _ivOpts ...rpcclient.InvokeOption)
	// Unregister Unregister a Portal instance.
	//   @param instanceId - Portal instance ID
	Unregister(instanceId skel.UUID, _ivOpts ...rpcclient.InvokeOption)
	// Heartbeat Portal instance heartbeat.
	//   @param status - Portal instance status
	//   @returns bool - Whether the current Portal instance is still registered in the Hub
	Heartbeat(status PortalStatus, _ivOpts ...rpcclient.InvokeOption) bool
}

type _PortalRegistryServiceClient struct {
	clientER PortalRegistryServiceClientER
}

func NewPortalRegistryServiceClient(clientER PortalRegistryServiceClientER) PortalRegistryServiceClient {
	return &_PortalRegistryServiceClient{clientER: clientER}
}

func (client *_PortalRegistryServiceClient) Register(registration PortalRegistration, _ivOpts ...rpcclient.InvokeOption) {
	err := client.clientER.Register(registration, _ivOpts...)
	ex.PanicIfError(err)
}

func (client *_PortalRegistryServiceClient) Unregister(instanceId skel.UUID, _ivOpts ...rpcclient.InvokeOption) {
	err := client.clientER.Unregister(instanceId, _ivOpts...)
	ex.PanicIfError(err)
}

func (client *_PortalRegistryServiceClient) Heartbeat(status PortalStatus, _ivOpts ...rpcclient.InvokeOption) bool {
	ret, err := client.clientER.Heartbeat(status, _ivOpts...)
	ex.PanicIfError(err)
	return ret
}

// PortalRegistryService / ERClient

type PortalRegistryServiceClientER interface {
	// Register Register a Portal instance.
	//   @param registration - Portal instance registration information
	Register(registration PortalRegistration, _ivOpts ...rpcclient.InvokeOption) ex.Error
	// Unregister Unregister a Portal instance.
	//   @param instanceId - Portal instance ID
	Unregister(instanceId skel.UUID, _ivOpts ...rpcclient.InvokeOption) ex.Error
	// Heartbeat Portal instance heartbeat.
	//   @param status - Portal instance status
	//   @returns bool - Whether the current Portal instance is still registered in the Hub
	Heartbeat(status PortalStatus, _ivOpts ...rpcclient.InvokeOption) (bool, ex.Error)
}

type _PortalRegistryServiceClientER struct {
	rpcClient *rpcclient.Client
}

func NewPortalRegistryServiceClientER(rpcClient *rpcclient.Client) PortalRegistryServiceClientER {
	return &_PortalRegistryServiceClientER{
		rpcClient: rpcClient,
	}
}

func (client *_PortalRegistryServiceClientER) Register(registration PortalRegistration, _ivOpts ...rpcclient.InvokeOption) ex.Error {
	_, err := client.rpcClient.Invoke(_PortalRegistryServiceRegisterSpec.Info(), &_PortalRegistryServiceRegisterArguments{
		Registration: registration,
	}, _ivOpts...)
	return err
}

func (client *_PortalRegistryServiceClientER) Unregister(instanceId skel.UUID, _ivOpts ...rpcclient.InvokeOption) ex.Error {
	_, err := client.rpcClient.Invoke(_PortalRegistryServiceUnregisterSpec.Info(), &_PortalRegistryServiceUnregisterArguments{
		InstanceId: instanceId,
	}, _ivOpts...)
	return err
}

func (client *_PortalRegistryServiceClientER) Heartbeat(status PortalStatus, _ivOpts ...rpcclient.InvokeOption) (bool, ex.Error) {
	return client.rpcClient.InvokeAs[bool](_PortalRegistryServiceHeartbeatSpec.Info(), &_PortalRegistryServiceHeartbeatArguments{
		Status: status,
	}, _ivOpts...)
}

// RegistryServiceServer Hub's application registration service, called by Link

// RegistryService / Spec

var (
	_RegistryServiceSpec = &rpcspec.ServiceSpec{
		Type:              rpcspec.ServiceSpecTypeBoth,
		Name:              "RegistryService",
		SkelName:          "vine.hub.control.RegistryService",
		Hash:              "bde422d8",
		ServerType:        reflect.TypeFor[RegistryServiceServer](),
		DefaultServerType: reflect.TypeFor[*DefaultRegistryServiceServer](),
		ClientType:        reflect.TypeFor[RegistryServiceClient](),
		ClientCtor:        NewRegistryServiceClient,

		ERServerType:        reflect.TypeFor[RegistryServiceServerER](),
		WrapperERServerCtor: _NewWrapperRegistryServiceServerER,
		DefaultERServerType: reflect.TypeFor[*DefaultRegistryServiceServerER](),
		ERClientType:        reflect.TypeFor[RegistryServiceClientER](),
		ERClientCtor:        NewRegistryServiceClientER,
		Methods: []*rpcspec.MethodSpec{
			_RegistryServiceRegisterSpec,
			_RegistryServiceUnregisterSpec,
			_RegistryServiceHeartbeatSpec,
		},
	}
	_RegistryServiceRegisterSpec = &rpcspec.MethodSpec{
		Name:                        "Register",
		SkelName:                    "register",
		ArgumentsType:               reflect.TypeFor[_RegistryServiceRegisterArguments](),
		ResultType:                  nil,
		ArgumentsSensitive:          false,
		ResultSensitive:             false,
		ArgumentsContainsBinaryType: false,
		ResultContainsBinaryType:    false,
		MethodFuncs: []any{
			RegistryServiceClient.Register,
			RegistryServiceClientER.Register,
			RegistryServiceServer.Register,
			RegistryServiceServerER.Register,
		},
	}
	_RegistryServiceUnregisterSpec = &rpcspec.MethodSpec{
		Name:                        "Unregister",
		SkelName:                    "unregister",
		ArgumentsType:               reflect.TypeFor[_RegistryServiceUnregisterArguments](),
		ResultType:                  nil,
		ArgumentsSensitive:          false,
		ResultSensitive:             false,
		ArgumentsContainsBinaryType: false,
		ResultContainsBinaryType:    false,
		MethodFuncs: []any{
			RegistryServiceClient.Unregister,
			RegistryServiceClientER.Unregister,
			RegistryServiceServer.Unregister,
			RegistryServiceServerER.Unregister,
		},
	}
	_RegistryServiceHeartbeatSpec = &rpcspec.MethodSpec{
		Name:                        "Heartbeat",
		SkelName:                    "heartbeat",
		ArgumentsType:               reflect.TypeFor[_RegistryServiceHeartbeatArguments](),
		ResultType:                  reflect.TypeFor[bool](),
		ArgumentsSensitive:          false,
		ResultSensitive:             false,
		ArgumentsContainsBinaryType: false,
		ResultContainsBinaryType:    false,
		MethodFuncs: []any{
			RegistryServiceClient.Heartbeat,
			RegistryServiceClientER.Heartbeat,
			RegistryServiceServer.Heartbeat,
			RegistryServiceServerER.Heartbeat,
		},
	}
)

// RegistryService / Arguments

type _RegistryServiceRegisterArguments struct {
	Registration AppRegistration `json:"registration" skel:"index(0)"`
}

type _RegistryServiceUnregisterArguments struct {
	Name       string    `json:"name" skel:"index(0)"`
	InstanceId skel.UUID `json:"instanceId" skel:"index(1)"`
}

type _RegistryServiceHeartbeatArguments struct {
	Status AppStatus `json:"status" skel:"index(0)"`
}

// RegistryService / Server

type RegistryServiceServer interface {
	// Register Register application instance.
	//   @param registration - Application instance registration information
	Register(registration AppRegistration)
	// Unregister Unregister an application instance.
	//   @param name - Application name
	//   @param instanceId - Application instance ID
	Unregister(name string, instanceId skel.UUID)
	// Heartbeat Application instance heartbeat.
	//   @param status - Application instance ID
	//   @returns bool - Whether the current instance is still registered in the Hub
	Heartbeat(status AppStatus) bool

	mustBeRegistryServiceServer()
}

// RegistryService / Server / DefaultServer

type DefaultRegistryServiceServer struct{}

func (*DefaultRegistryServiceServer) Register(AppRegistration) {
	ex.PanicNew(ex.InvalidRequest, "method register is not implemented")
}

func (*DefaultRegistryServiceServer) Unregister(string, skel.UUID) {
	ex.PanicNew(ex.InvalidRequest, "method unregister is not implemented")
}

func (*DefaultRegistryServiceServer) Heartbeat(AppStatus) bool {
	ex.PanicNew(ex.InvalidRequest, "method heartbeat is not implemented")
	return false
}

func (*DefaultRegistryServiceServer) mustBeRegistryServiceServer() {}

// RegistryService / ERServer

type RegistryServiceServerER interface {
	Register(registration AppRegistration) ex.Error
	Unregister(name string, instanceId skel.UUID) ex.Error
	Heartbeat(status AppStatus) (bool, ex.Error)

	mustBeRegistryServiceServerER()
}

// RegistryService / ERServer / WrapperERServer

type _WrapperRegistryServiceServerER struct {
	DefaultRegistryServiceServer
	serverImpl RegistryServiceServer
}

func _NewWrapperRegistryServiceServerER(serverImpl RegistryServiceServer) RegistryServiceServerER {
	return &_WrapperRegistryServiceServerER{
		serverImpl: serverImpl,
	}
}

func (service *_WrapperRegistryServiceServerER) server() RegistryServiceServer {
	if service.serverImpl == nil {
		return &service.DefaultRegistryServiceServer
	}
	return service.serverImpl
}

func (service *_WrapperRegistryServiceServerER) Register(registration AppRegistration) (err ex.Error) {
	defer func() { err = ex.Recover(recover()) }()
	service.server().Register(registration)
	return
}

func (service *_WrapperRegistryServiceServerER) Unregister(name string, instanceId skel.UUID) (err ex.Error) {
	defer func() { err = ex.Recover(recover()) }()
	service.server().Unregister(name, instanceId)
	return
}

func (service *_WrapperRegistryServiceServerER) Heartbeat(status AppStatus) (ret bool, err ex.Error) {
	defer func() { err = ex.Recover(recover()) }()
	ret = service.server().Heartbeat(status)
	return
}

func (*_WrapperRegistryServiceServerER) mustBeRegistryServiceServerER() {}

// RegistryService / ERServer / DefaultERServer

type DefaultRegistryServiceServerER struct {
	_WrapperRegistryServiceServerER
}

// RegistryService / Client

type RegistryServiceClient interface {
	// Register Register application instance.
	//   @param registration - Application instance registration information
	Register(registration AppRegistration, _ivOpts ...rpcclient.InvokeOption)
	// Unregister Unregister an application instance.
	//   @param name - Application name
	//   @param instanceId - Application instance ID
	Unregister(name string, instanceId skel.UUID, _ivOpts ...rpcclient.InvokeOption)
	// Heartbeat Application instance heartbeat.
	//   @param status - Application instance ID
	//   @returns bool - Whether the current instance is still registered in the Hub
	Heartbeat(status AppStatus, _ivOpts ...rpcclient.InvokeOption) bool
}

type _RegistryServiceClient struct {
	clientER RegistryServiceClientER
}

func NewRegistryServiceClient(clientER RegistryServiceClientER) RegistryServiceClient {
	return &_RegistryServiceClient{clientER: clientER}
}

func (client *_RegistryServiceClient) Register(registration AppRegistration, _ivOpts ...rpcclient.InvokeOption) {
	err := client.clientER.Register(registration, _ivOpts...)
	ex.PanicIfError(err)
}

func (client *_RegistryServiceClient) Unregister(name string, instanceId skel.UUID, _ivOpts ...rpcclient.InvokeOption) {
	err := client.clientER.Unregister(name, instanceId, _ivOpts...)
	ex.PanicIfError(err)
}

func (client *_RegistryServiceClient) Heartbeat(status AppStatus, _ivOpts ...rpcclient.InvokeOption) bool {
	ret, err := client.clientER.Heartbeat(status, _ivOpts...)
	ex.PanicIfError(err)
	return ret
}

// RegistryService / ERClient

type RegistryServiceClientER interface {
	// Register Register application instance.
	//   @param registration - Application instance registration information
	Register(registration AppRegistration, _ivOpts ...rpcclient.InvokeOption) ex.Error
	// Unregister Unregister an application instance.
	//   @param name - Application name
	//   @param instanceId - Application instance ID
	Unregister(name string, instanceId skel.UUID, _ivOpts ...rpcclient.InvokeOption) ex.Error
	// Heartbeat Application instance heartbeat.
	//   @param status - Application instance ID
	//   @returns bool - Whether the current instance is still registered in the Hub
	Heartbeat(status AppStatus, _ivOpts ...rpcclient.InvokeOption) (bool, ex.Error)
}

type _RegistryServiceClientER struct {
	rpcClient *rpcclient.Client
}

func NewRegistryServiceClientER(rpcClient *rpcclient.Client) RegistryServiceClientER {
	return &_RegistryServiceClientER{
		rpcClient: rpcClient,
	}
}

func (client *_RegistryServiceClientER) Register(registration AppRegistration, _ivOpts ...rpcclient.InvokeOption) ex.Error {
	_, err := client.rpcClient.Invoke(_RegistryServiceRegisterSpec.Info(), &_RegistryServiceRegisterArguments{
		Registration: registration,
	}, _ivOpts...)
	return err
}

func (client *_RegistryServiceClientER) Unregister(name string, instanceId skel.UUID, _ivOpts ...rpcclient.InvokeOption) ex.Error {
	_, err := client.rpcClient.Invoke(_RegistryServiceUnregisterSpec.Info(), &_RegistryServiceUnregisterArguments{
		Name:       name,
		InstanceId: instanceId,
	}, _ivOpts...)
	return err
}

func (client *_RegistryServiceClientER) Heartbeat(status AppStatus, _ivOpts ...rpcclient.InvokeOption) (bool, ex.Error) {
	return client.rpcClient.InvokeAs[bool](_RegistryServiceHeartbeatSpec.Info(), &_RegistryServiceHeartbeatArguments{
		Status: status,
	}, _ivOpts...)
}
