// Code generated by skelc. DO NOT EDIT.

package skeled

import (
	"go.yorun.ai/skel/descriptor"
	"go.yorun.ai/vine/core/skel"
)

func init() {
	skel.RegisterDomainDescriptor(_DomainDescriptor)
}

var _DomainDescriptor = &descriptor.Domain{
	Name:        "vine.app",
	Description: "Internal API for vine framework",
	Hash:        "bea736f6",
	Full:        true,
	Generated:   &descriptor.GeneratedInfo{CompilerVersion: "v0.31.0"},

	Data: []*descriptor.Data{
		{Name: "EventOn", SkelName: "vine.app.EventOn", Description: "Link triggers event processing information to the App", Hash: "e2794713", Members: []*descriptor.Member{
			{Name: "metadata", Description: "Event meta information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "EventOnMeta", SkelName: "vine.app.EventOnMeta"}},
			{Name: "eventSkelName", Description: "Event Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "eventJson", Description: "Event JSON", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
		{Name: "EventOnMeta", SkelName: "vine.app.EventOnMeta", Description: "Link triggers event processing meta-information to the App", Hash: "39feb0b1", Members: []*descriptor.Member{
			{Name: "traceId", Description: "Trace ID of the current calling link", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "traceSpan", Description: "Trace Span of the current calling link", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appName", Description: "The application name that sent the event", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appVersion", Description: "The application version that sent the event", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appInstanceId", Description: "The application instance ID that sent the event", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarUUID}},
			{Name: "emittedAt", Description: "The time the event was sent", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarTimestamp}},
		}},
		{Name: "TaskRun", SkelName: "vine.app.TaskRun", Description: "Link triggers task execution information to the App", Hash: "1669399b", Members: []*descriptor.Member{
			{Name: "metadata", Description: "Task trigger meta information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "TaskRunMeta", SkelName: "vine.app.TaskRunMeta"}},
			{Name: "taskSkelName", Description: "Task Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "triggerSkelName", Description: "Task trigger Skel name", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "argumentsJson", Description: "Task parameters JSON", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
		}},
		{Name: "TaskRunMeta", SkelName: "vine.app.TaskRunMeta", Description: "Link triggers meta-information of task execution to App", Hash: "3a7960ca", Members: []*descriptor.Member{
			{Name: "traceId", Description: "Trace ID of the current calling link", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "traceSpan", Description: "Trace Span of the current calling link", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appName", Description: "Application name that initiated the task", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appVersion", Description: "The application version that initiated the task", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarString}},
			{Name: "appInstanceId", Description: "The application instance ID that initiated the task", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarUUID}},
			{Name: "launchedAt", Description: "Task launch time", Type: &descriptor.Type{Kind: descriptor.TypeKindScalar, Scalar: descriptor.ScalarTimestamp}},
		}},
	},

	Services: []*descriptor.Service{
		{Name: "ConsoleService", SkelName: "vine.app.ConsoleService", Description: "App's console service, called by Link", Hash: "ef0ecbc5", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "ping", SkelName: "ping", Description: "Application health check", Hash: "f08a8610", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired},
		}},
		{Name: "EventService", SkelName: "vine.app.EventService", Description: "App's event processing service, called by Link", Hash: "d6668714", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "onEvent", SkelName: "onEvent", Description: "Trigger event processing", Hash: "15692206", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, Arguments: []*descriptor.Member{
				{Name: "on", Description: "Event handling information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "EventOn", SkelName: "vine.app.EventOn"}},
			}},
		}},
		{Name: "TaskService", SkelName: "vine.app.TaskService", Description: "App's task execution service, called by Link", Hash: "1974ce48", Pub: true, AuthMode: descriptor.AuthModeRequired, Methods: []*descriptor.Method{
			{Name: "runTask", SkelName: "runTask", Description: "Trigger task execution", Hash: "a440c23c", AuthMode: descriptor.AuthModeInherit, EffectiveAuthMode: descriptor.AuthModeRequired, Arguments: []*descriptor.Member{
				{Name: "run", Description: "Task execution information", Type: &descriptor.Type{Kind: descriptor.TypeKindData, Name: "TaskRun", SkelName: "vine.app.TaskRun"}},
			}},
		}},
	},
}
